from __future__ import annotations


EXTRA_MATERIALS = [
    {"name": "定魄灵砂", "quality_level": 3, "description": "带着沉静神魂波动的细砂，多用来炼制定心、守神一类灵物。"},
    {"name": "霓裳花露", "quality_level": 3, "description": "只在朝霞最盛时凝成的花露，灵气温润而轻盈。"},
    {"name": "承运木心", "quality_level": 4, "description": "千年灵木最深处的心材，能稳住气运与因果牵引。"},
    {"name": "星命玉枝", "quality_level": 4, "description": "被夜色浸透的玉化枝条，常见于推演命数类器物。"},
    {"name": "龙门真水", "quality_level": 5, "description": "逆流而上的灵水结晶，最适合炼制蜕变、问心类奇药。"},
    {"name": "天眷符骨", "quality_level": 5, "description": "自古阵遗骸中析出的符骨，常用来承载高阶机缘符纹。"},
]


EXTRA_ARTIFACTS = [
    {
        "name": "定海镇心佩",
        "rarity": "上品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "bracelet",
        "description": "佩在腕间后心神如定海针落底，最能稳住道心与护体。",
        "defense_bonus": 18,
        "qi_blood_bonus": 54,
        "fortune_bonus": 4,
        "cultivation_bonus": 6,
        "min_realm_stage": "筑基",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "流霞问心簪",
        "rarity": "极品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "helmet",
        "description": "簪尾拖着流霞细芒，能稳神、养气，也更易在人前留下道韵气象。",
        "comprehension_bonus": 12,
        "fortune_bonus": 10,
        "true_yuan_bonus": 72,
        "cultivation_bonus": 10,
        "min_realm_stage": "结丹",
        "min_realm_layer": 2,
        "enabled": True,
    },
]


EXTRA_PILLS = [
    {
        "name": "定心明台丹",
        "rarity": "上品",
        "pill_type": "willpower",
        "effect_value": 14,
        "poison_delta": 3,
        "description": "药性沉静，能让道心更稳，面对凶险时不易溃散。",
        "materials": [("定魄灵砂", 1), ("凝露花", 1), ("玄冰胆", 1)],
        "success": 58,
    },
    {
        "name": "流霞驻颜丹",
        "rarity": "上品",
        "pill_type": "charisma",
        "effect_value": 12,
        "poison_delta": 3,
        "description": "气色与灵韵俱增，在坊市与群中都更容易博得好感。",
        "materials": [("霓裳花露", 2), ("灵雾草心", 1), ("太乙木心", 1)],
        "success": 56,
    },
    {
        "name": "承运问天丹",
        "rarity": "极品",
        "pill_type": "karma",
        "effect_value": 10,
        "poison_delta": 4,
        "description": "可微调自身运势走向，让机缘落点更偏向己身。",
        "materials": [("承运木心", 1), ("星命玉枝", 1), ("太华灵液", 1)],
        "success": 46,
    },
    {
        "name": "太和解厄丹",
        "rarity": "极品",
        "pill_type": "clear_poison",
        "effect_value": 36,
        "poison_delta": 1,
        "description": "专门化解丹毒与探索残留的浊煞。",
        "materials": [("龙门真水", 1), ("造化玉露", 1), ("无垢净沙", 1)],
        "success": 44,
    },
    {
        "name": "聚宝含光丹",
        "rarity": "中品",
        "pill_type": "stone",
        "effect_value": 96,
        "poison_delta": 2,
        "description": "丹成之后会析出灵石般的精纯灵辉，适合应急补财。",
        "materials": [("星河砂", 1), ("暖玉粉", 1), ("寒水露", 1)],
        "success": 68,
    },
]


EXTRA_TALISMANS = [
    {
        "name": "回澜符",
        "rarity": "上品",
        "defense_bonus": 18,
        "true_yuan_bonus": 26,
        "duel_rate_bonus": 3,
        "description": "符成如水纹倒卷，擅长在硬拼时缓冲对手的冲势。",
        "combat_config": {
            "skills": [
                {
                    "name": "回澜护潮",
                    "kind": "shield",
                    "chance": 30,
                    "flat_shield": 22,
                    "ratio_percent": 18,
                    "text": "回澜符水纹翻涌，将来势层层卸开。",
                }
            ]
        },
        "materials": [("定魄灵砂", 1), ("玄龟骨晶", 1), ("龙门真水", 1)],
        "success": 54,
    },
    {
        "name": "惊鸿符",
        "rarity": "极品",
        "attack_bonus": 20,
        "body_movement_bonus": 20,
        "duel_rate_bonus": 5,
        "description": "灵符一燃便似惊鸿掠水，适合抢先手与突进追击。",
        "combat_config": {
            "skills": [
                {
                    "name": "惊鸿掠影",
                    "kind": "extra_damage",
                    "chance": 32,
                    "flat_damage": 20,
                    "ratio_percent": 20,
                    "text": "惊鸿符划开一抹长影，下一击几乎同时落下。",
                }
            ]
        },
        "materials": [("霓裳花露", 1), ("星命玉枝", 1), ("璇玑星砂", 1)],
        "success": 42,
    },
]


EXTRA_RECIPES = [
    {
        "name": "定海镇心佩炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "定海镇心佩",
        "result_quantity": 1,
        "base_success_rate": 50,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "定魄灵砂", "quantity": 2},
            {"material_name": "玄龟甲片", "quantity": 1},
            {"material_name": "地脉岩芯", "quantity": 1},
        ],
    },
    {
        "name": "流霞问心簪炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "流霞问心簪",
        "result_quantity": 1,
        "base_success_rate": 42,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "霓裳花露", "quantity": 2},
            {"material_name": "承运木心", "quantity": 1},
            {"material_name": "星辉砂", "quantity": 1},
        ],
    },
    {
        "name": "回澜符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "回澜符",
        "result_quantity": 2,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "定魄灵砂", "quantity": 1},
            {"material_name": "龙门真水", "quantity": 1},
            {"material_name": "玄龟骨晶", "quantity": 1},
        ],
    },
    {
        "name": "惊鸿符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "惊鸿符",
        "result_quantity": 2,
        "base_success_rate": 44,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "霓裳花露", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
            {"material_name": "璇玑星砂", "quantity": 1},
        ],
    },
    {
        "name": "定心明台丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "定心明台丹",
        "result_quantity": 1,
        "base_success_rate": 60,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "定魄灵砂", "quantity": 1},
            {"material_name": "凝露花", "quantity": 1},
            {"material_name": "玄冰胆", "quantity": 1},
        ],
    },
    {
        "name": "流霞驻颜丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "流霞驻颜丹",
        "result_quantity": 1,
        "base_success_rate": 58,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "霓裳花露", "quantity": 2},
            {"material_name": "灵雾草心", "quantity": 1},
            {"material_name": "太乙木心", "quantity": 1},
        ],
    },
    {
        "name": "承运问天丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "承运问天丹",
        "result_quantity": 1,
        "base_success_rate": 48,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "承运木心", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
            {"material_name": "太华灵液", "quantity": 1},
        ],
    },
]


EXTRA_SCENES = [
    {
        "name": "流霞古渡",
        "description": "半空残桥与古渡相接，朝夕霞光会把许多隐秘材料照得显形。",
        "max_minutes": 46,
        "min_realm_stage": "筑基",
        "min_realm_layer": 3,
        "min_combat_power": 2200,
        "event_pool": [
            {
                "name": "霞桥残匣",
                "description": "断桥下卡着一只旧匣，里面居然还护着一页丹谱。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "流霞驻颜丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 36,
            },
            {
                "name": "霞羽掠空",
                "description": "流霞中闪过一抹轻影，追上后你悟到一线迅捷符意。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "talisman",
                "bonus_reward_ref_id_name": "惊鸿符",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 22,
            },
            {
                "name": "渡口逆浪",
                "description": "古渡忽起逆浪，桥身一阵乱晃，险些把你卷下去。",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 18,
                "stone_bonus_max": 34,
                "stone_loss_min": 6,
                "stone_loss_max": 16,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "霓裳花露", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 8, "event_text": "你在霞雾间凝出了一瓶霓裳花露。"},
            {"reward_kind": "material", "reward_ref_id_name": "定魄灵砂", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 9, "event_text": "桥缝里积着一层细细的定魄灵砂。"},
            {"reward_kind": "material", "reward_ref_id_name": "星辉砂", "quantity_min": 1, "quantity_max": 2, "weight": 3, "stone_reward": 10, "event_text": "暮色落下时，桥面竟析出几粒星辉砂。"},
        ],
    },
    {
        "name": "天书阁遗址",
        "description": "破碎阁楼仍有天书气机环绕，最适合收集命数、神识与机缘类宝材。",
        "max_minutes": 60,
        "min_realm_stage": "元婴",
        "min_realm_layer": 1,
        "min_combat_power": 4200,
        "event_pool": [
            {
                "name": "命盘残页",
                "description": "高阁梁柱间夹着一页尚未完全风化的命盘残页。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "承运问天丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 28,
            },
            {
                "name": "问心遗器",
                "description": "旧案几上有一支灵光未散的发簪，似乎仍认主未远。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "artifact",
                "bonus_reward_ref_id_name": "流霞问心簪",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 12,
            },
            {
                "name": "天书逆卷",
                "description": "残破书页忽然倒卷成风，阁中阵势像要把你一同绞进去。",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 28,
                "stone_bonus_max": 54,
                "stone_loss_min": 12,
                "stone_loss_max": 24,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "承运木心", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 12, "event_text": "阁中残柱剥出一截承运木心。"},
            {"reward_kind": "material", "reward_ref_id_name": "星命玉枝", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 14, "event_text": "书架深处竟压着一段星命玉枝。"},
            {"reward_kind": "material", "reward_ref_id_name": "天眷符骨", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 18, "event_text": "阁楼阵眼附近散落着一块天眷符骨。"},
        ],
    },
]


DEFAULT_ENCOUNTER_TEMPLATES = [
    {
        "name": "天降残页",
        "description": "半空突然飘落一页未烧尽的古卷残纸。",
        "button_text": "抢残页",
        "success_text": "🎉 {user} 手快如电，抢到了【{encounter}】，收获 {reward}。",
        "broadcast_text": "一页古卷残纸自半空飘落，谁先接住，谁就能得其中机缘。",
        "weight": 8,
        "active_seconds": 90,
        "reward_stone_min": 30,
        "reward_stone_max": 66,
        "reward_cultivation_min": 24,
        "reward_cultivation_max": 60,
        "reward_item_kind": "recipe",
        "reward_item_ref_name": "流霞驻颜丹丹谱",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_karma": 1,
        "enabled": True,
    },
    {
        "name": "行脚商遗包",
        "description": "有人匆匆赶路时掉下一只鼓鼓囊囊的旧布包。",
        "button_text": "捡布包",
        "success_text": "🧳 {user} 一把夺过遗包，里面竟装着 {reward}。",
        "broadcast_text": "路边滚来一只行脚商遗落的布包，包口还在往外漏灵光。",
        "weight": 7,
        "active_seconds": 80,
        "reward_stone_min": 48,
        "reward_stone_max": 120,
        "reward_item_kind": "material",
        "reward_item_ref_name": "定魄灵砂",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "reward_charisma": 1,
        "enabled": True,
    },
    {
        "name": "祖师传音",
        "description": "冥冥中似有祖师留音自耳边响起。",
        "button_text": "静听传音",
        "success_text": "🕯️ {user} 静下心来听完祖师传音，道心得到磨炼，收获 {reward}。",
        "broadcast_text": "群中忽闻古老道音回荡，像是某位祖师隔空留下一缕点拨。",
        "weight": 6,
        "active_seconds": 75,
        "reward_cultivation_min": 66,
        "reward_cultivation_max": 144,
        "reward_willpower": 2,
        "reward_karma": 1,
        "enabled": True,
    },
    {
        "name": "灵宠献果",
        "description": "一只机灵小兽丢下一枚还带着温热灵气的果子。",
        "button_text": "接灵果",
        "success_text": "🍑 {user} 抢到了灵果，小兽甩尾就跑，只留下 {reward}。",
        "broadcast_text": "不知从哪窜出一只灵宠，把灵果往人群里一丢，转眼就没影了。",
        "weight": 8,
        "active_seconds": 70,
        "reward_stone_min": 18,
        "reward_stone_max": 36,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "定心明台丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_willpower": 1,
        "enabled": True,
    },
    {
        "name": "桃花仙会请帖",
        "description": "粉霞一卷，地上竟多出一张烫金请帖。",
        "button_text": "夺请帖",
        "success_text": "🌸 {user} 抢下仙会请帖，仪态与灵韵都更添几分，收获 {reward}。",
        "broadcast_text": "桃花香气忽然弥漫，地上出现一张只认先到者的仙会请帖。",
        "weight": 5,
        "active_seconds": 85,
        "min_realm_stage": "筑基",
        "min_realm_layer": 1,
        "reward_stone_min": 36,
        "reward_stone_max": 88,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "流霞驻颜丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_charisma": 3,
        "enabled": True,
    },
    {
        "name": "陨星裂匣",
        "description": "一只被陨火烧裂的旧匣从天而降，里面灵压紊乱。",
        "button_text": "开星匣",
        "success_text": "☄️ {user} 顶着灼热灵压掀开星匣，收下了 {reward}。",
        "broadcast_text": "群中忽然坠下一只燃着尾焰的裂匣，匣中像藏着尚未熄灭的天外余辉。",
        "weight": 4,
        "active_seconds": 60,
        "min_realm_stage": "结丹",
        "min_realm_layer": 1,
        "min_combat_power": 2600,
        "reward_stone_min": 88,
        "reward_stone_max": 166,
        "reward_item_kind": "material",
        "reward_item_ref_name": "天眷符骨",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "reward_karma": 2,
        "enabled": True,
    },
    {
        "name": "问天签",
        "description": "一支古签自虚空坠下，像在等人伸手接住。",
        "button_text": "接问天签",
        "success_text": "🎐 {user} 接住问天签，命数似乎朝着自己偏了一寸，收获 {reward}。",
        "broadcast_text": "一支刻着古篆的问天签忽然落下，签尾还缠着一缕未散的命数之力。",
        "weight": 5,
        "active_seconds": 72,
        "min_realm_stage": "结丹",
        "min_realm_layer": 3,
        "reward_cultivation_min": 88,
        "reward_cultivation_max": 180,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "承运问天丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_karma": 3,
        "enabled": True,
    },
    {
        "name": "仙府钥影",
        "description": "空中一闪而过的钥匙虚影，似乎只会为强者停留片刻。",
        "button_text": "夺钥影",
        "success_text": "🗝️ {user} 抢下钥影，竟从中拆出了 {reward}。",
        "broadcast_text": "一枚仙府钥匙的虚影在群中一闪即逝，谁能先稳住它，谁就有机会得府中旧藏。",
        "weight": 3,
        "active_seconds": 55,
        "min_realm_stage": "元婴",
        "min_realm_layer": 1,
        "min_combat_power": 4200,
        "reward_stone_min": 168,
        "reward_stone_max": 288,
        "reward_cultivation_min": 160,
        "reward_cultivation_max": 260,
        "reward_item_kind": "artifact",
        "reward_item_ref_name": "流霞问心簪",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_willpower": 2,
        "reward_charisma": 2,
        "reward_karma": 2,
        "enabled": True,
    },
]
