from __future__ import annotations

EXTRA_ARTIFACTS = [
    {
        "name": "潮音珊瑚佩",
        "rarity": "中品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "bracelet",
        "description": "以潮音珊瑚打磨成佩，入手清凉，佩之可稳心定气，斗法时更擅借势卸力。",
        "defense_bonus": 12,
        "true_yuan_bonus": 18,
        "fortune_bonus": 2,
        "min_realm_stage": "筑基",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "听潮玉壶",
        "rarity": "上品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "necklace",
        "description": "玉壶内藏一缕海潮回音，斗法前摇动壶身，便能借潮息润养真元、澄明神识。",
        "defense_bonus": 10,
        "divine_sense_bonus": 12,
        "true_yuan_bonus": 28,
        "fortune_bonus": 4,
        "cultivation_bonus": 4,
        "min_realm_stage": "结丹",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "月魄垂纶钩",
        "rarity": "极品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以月魄蚌珠与海眼寒晶共炼而成，钩锋极细却锋芒内敛，最擅破开护体灵光后追击。",
        "attack_bonus": 22,
        "body_movement_bonus": 16,
        "fortune_bonus": 8,
        "duel_rate_bonus": 4,
        "combat_config": {
            "skills": [
                {
                    "name": "垂纶裂波",
                    "kind": "armor_break",
                    "chance": 28,
                    "defense_ratio_percent": 16,
                    "duration": 2,
                    "text": "月魄垂纶钩一点即收，护体灵波被硬生生扯开一道裂口。",
                }
            ]
        },
        "min_realm_stage": "结丹",
        "min_realm_layer": 5,
        "enabled": True,
    },
    {
        "name": "星潮引灵灯",
        "rarity": "仙品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "bracelet",
        "description": "灯芯以星渊潮核点燃，燃起时如一盏悬在海上的孤灯，最擅引聚灵机与海潮气数。",
        "comprehension_bonus": 12,
        "divine_sense_bonus": 14,
        "fortune_bonus": 12,
        "true_yuan_bonus": 40,
        "cultivation_bonus": 8,
        "min_realm_stage": "化神",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "定海镇心佩",
        "rarity": "上品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "bracelet",
        "description": "此佩以定魄神铁铸就，佩之如镇海神针入心，万千幻象不能动其分毫，心神恒定如一，乃守护道心之无上灵器。",
        "defense_bonus": 18,
        "qi_blood_bonus": 54,
        "fortune_bonus": 4,
        "cultivation_bonus": 6,
        "min_realm_stage": "筑基",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "流霞问心簪",
        "rarity": "极品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "helmet",
        "description": "此簪以流霞仙丝编织而成，尾端拖曳七彩虹光，簪身流转间如云霞缥缈，佩戴者可养气凝神，于举手投足间尽显道韵天成。",
        "comprehension_bonus": 12,
        "fortune_bonus": 10,
        "true_yuan_bonus": 72,
        "cultivation_bonus": 10,
        "min_realm_stage": "结丹",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "照骨问心镜",
        "rarity": "极品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "necklace",
        "description": "此镜为上古心镜所化，镜面如冰晶清澈，照之可见骨相亦可见心魔，镜光一转即可捕捉对手气机流转之破绽，于决战之中洞悉先机。",
        "defense_bonus": 16,
        "divine_sense_bonus": 18,
        "fortune_bonus": 8,
        "duel_rate_bonus": 4,
        "cultivation_bonus": 6,
        "combat_config": {
            "passives": [
                {
                    "name": "镜光照影",
                    "kind": "armor_break",
                    "chance": 24,
                    "defense_ratio_percent": 14,
                    "duration": 2,
                    "text": "照骨问心镜映出灵压裂纹，护体破绽被当场放大。",
                }
            ]
        },
        "min_realm_stage": "结丹",
        "min_realm_layer": 5,
        "enabled": True,
    },
    {
        "name": "赤霄逐日弓",
        "rarity": "仙品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此弓以赤霄神木为身，浸以九日真火精华，弓弦以凤筋所铸，开弦之时如天火降临，箭出则如流星逐日，灼热难当，势不可挡。",
        "attack_bonus": 32,
        "true_yuan_bonus": 36,
        "body_movement_bonus": 18,
        "duel_rate_bonus": 6,
        "combat_config": {
            "skills": [
                {
                    "name": "逐日离弦",
                    "kind": "extra_damage",
                    "chance": 32,
                    "flat_damage": 24,
                    "ratio_percent": 22,
                    "text": "赤霄逐日弓一声绷响，火线般的箭影已经直逼面门。",
                }
            ],
            "opening_text": "弓弦被缓缓拉满，四周空气像被烧得发颤。",
        },
        "min_realm_stage": "化神",
        "min_realm_layer": 1,
        "enabled": True,
    },
    # ========== 新增：凡品法宝 ==========
    {
        "name": "玄铁短剑",
        "rarity": "凡品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以玄铁锻造，剑身如墨，虽为新手练手之物，却已初具灵性，剑出如虹。",
        "attack_bonus": 8,
        "defense_bonus": 2,
        "min_realm_stage": "凡人",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "布衣护腕",
        "rarity": "凡品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "bracelet",
        "description": "以灵蚕丝织就粗布为底，护腕处绣有简单符文，可挡无形之伤，护持经脉。",
        "defense_bonus": 4,
        "qi_blood_bonus": 10,
        "min_realm_stage": "凡人",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "翠竹杖",
        "rarity": "凡品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以灵山翠竹削制而成，竹身节节分明，蕴含清风之气，虽朴素却已初具灵韵。",
        "attack_bonus": 6,
        "body_movement_bonus": 4,
        "min_realm_stage": "凡人",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "草灵镯",
        "rarity": "凡品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "bracelet",
        "description": "以灵草精华编织而成的手镯，草脉之中蕴含生机，佩戴可缓慢恢复体力。",
        "qi_blood_bonus": 12,
        "cultivation_bonus": 2,
        "min_realm_stage": "凡人",
        "min_realm_layer": 1,
        "enabled": True,
    },
    # ========== 新增：下品法宝 ==========
    {
        "name": "寒霜剑",
        "rarity": "下品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以寒铁为骨，玄冰为魂，剑成之日有霜华覆面，挥剑时寒气如龙，冻彻心扉。",
        "attack_bonus": 14,
        "body_movement_bonus": 4,
        "min_realm_stage": "炼气",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "烈阳刀",
        "rarity": "下品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以烈阳石精心锻造的长刀，刀身如熔岩流淌，挥舞时带有滚滚热浪，触之即灼。",
        "attack_bonus": 16,
        "duel_rate_bonus": 2,
        "min_realm_stage": "炼气",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "清风靴",
        "rarity": "下品",
        "artifact_type": "support",
        "artifact_role": "movement",
        "equip_slot": "boots",
        "description": "以风灵石配合灵蚕丝编织而成，上足如踏清风，落地无声，行走如羽。",
        "body_movement_bonus": 12,
        "defense_bonus": 2,
        "min_realm_stage": "炼气",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "震雷锤",
        "rarity": "下品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以雷击桃木为锤身，镶嵌导电精钢为锤面，引天雷之力灌注，挥舞时风雷相随，威势惊人。",
        "attack_bonus": 18,
        "duel_rate_bonus": 3,
        "min_realm_stage": "炼气",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "霜风剑",
        "rarity": "下品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以寒铁为胚，寒霜草汁淬火，剑身泛淡蓝寒光，挥剑时寒风呼啸，冰封敌人经脉。",
        "attack_bonus": 15,
        "defense_bonus": 4,
        "min_realm_stage": "炼气",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "厚土盾",
        "rarity": "下品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "shield",
        "description": "以千年阴沉木为基，覆以厚实玄武岩片，盾面如大地厚重，防护之时稳如磐石。",
        "defense_bonus": 20,
        "qi_blood_bonus": 25,
        "min_realm_stage": "炼气",
        "min_realm_layer": 3,
        "enabled": True,
    },
    # ========== 新增：中品法宝 ==========
    {
        "name": "冰魄剑",
        "rarity": "中品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以北极冰魄珠为剑胚，剑身如寒潭深蓝，出剑时寒气如龙，触之即冻。",
        "attack_bonus": 22,
        "defense_bonus": 6,
        "duel_rate_bonus": 3,
        "min_realm_stage": "炼气",
        "min_realm_layer": 5,
        "enabled": True,
    },
    {
        "name": "火鸾羽扇",
        "rarity": "中品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以火鸾真羽配合精金锻造，展开时如火凤展翼，摇扇间烈焰横空，敌人触之即燃。",
        "attack_bonus": 24,
        "body_movement_bonus": 6,
        "min_realm_stage": "筑基",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "金刚护甲",
        "rarity": "中品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "chest",
        "description": "以金芒砂配合万年寒铁锻造，甲胄表面如金色流光，披挂于身坚不可摧。",
        "defense_bonus": 28,
        "qi_blood_bonus": 40,
        "min_realm_stage": "筑基",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "木灵珠",
        "rarity": "中品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "necklace",
        "description": "以千年古木之心精心雕琢，珠子内绿色灵光流转，佩戴后可感受天地灵韵。",
        "cultivation_bonus": 8,
        "true_yuan_bonus": 30,
        "min_realm_stage": "筑基",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "神鹤剑",
        "rarity": "中品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以仙鹤妖禽的腿骨为剑胚，鹤羽为穗，剑身如雪白洁，挥剑时如仙鹤掠水，轻灵而致命。",
        "attack_bonus": 23,
        "body_movement_bonus": 8,
        "duel_rate_bonus": 3,
        "min_realm_stage": "筑基",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "焰虎斧",
        "rarity": "中品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以火牛角配合烈阳石锻造，斧身纹路如虎纹燃烧，挥舞时如有火虎咆哮，烈焰缠斧。",
        "attack_bonus": 26,
        "defense_bonus": 4,
        "min_realm_stage": "筑基",
        "min_realm_layer": 4,
        "enabled": True,
    },
    {
        "name": "玄风盾",
        "rarity": "中品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "shield",
        "description": "以风灵石精炼为核心，妖狐尾毛编织为面，盾成时有玄风绕盾，可卸力卸法，柔中克刚。",
        "defense_bonus": 24,
        "body_movement_bonus": 6,
        "min_realm_stage": "筑基",
        "min_realm_layer": 5,
        "enabled": True,
    },
    {
        "name": "根灵甲",
        "rarity": "中品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "chest",
        "description": "以树灵精魄融入护甲，内蕴生生不息之机，披挂后伤势恢复加快，宛如草木逢春。",
        "defense_bonus": 22,
        "qi_blood_bonus": 35,
        "cultivation_bonus": 4,
        "min_realm_stage": "筑基",
        "min_realm_layer": 3,
        "enabled": True,
    },
    # ========== 新增：上品法宝 ==========
    {
        "name": "玄冰剑",
        "rarity": "上品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以万年玄冰精髓锻造，剑身如万年寒潭，深蓝而剔透，挥剑时万物皆可冰封。",
        "attack_bonus": 32,
        "defense_bonus": 10,
        "duel_rate_bonus": 4,
        "min_realm_stage": "结丹",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "烈凤杖",
        "rarity": "上品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以烈凤心血淬炼，杖身如浴火凤凰之羽，蕴含极致火属，攻击时真火如凤舞九天。",
        "attack_bonus": 36,
        "true_yuan_bonus": 40,
        "duel_rate_bonus": 5,
        "combat_config": {
            "skills": [
                {
                    "name": "烈凤燎原",
                    "kind": "extra_damage",
                    "chance": 28,
                    "flat_damage": 22,
                    "ratio_percent": 18,
                    "text": "烈凤杖一挥，凤凰真火化作火海席卷对手。",
                }
            ],
        },
        "min_realm_stage": "结丹",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "太白神盾",
        "rarity": "上品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "shield",
        "description": "以九天神铁配合太白精金锻造，盾面如银河倾泻，披挂时万法不侵，天雷难破。",
        "defense_bonus": 38,
        "qi_blood_bonus": 60,
        "duel_rate_bonus": 3,
        "combat_config": {
            "passives": [
                {
                    "name": "太白护体",
                    "kind": "shield",
                    "chance": 24,
                    "flat_shield": 30,
                    "ratio_percent": 16,
                    "text": "太白神盾化出一层金色护罩，将攻击卸去大半。",
                }
            ],
        },
        "min_realm_stage": "元婴",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "幽冥魂锁",
        "rarity": "上品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "necklace",
        "description": "以九幽幽冥深处的魂晶雕琢而成，链身如墨夜色，佩戴时可锁敌之魂，令其判断失误。",
        "divine_sense_bonus": 16,
        "comprehension_bonus": 10,
        "duel_rate_bonus": 4,
        "combat_config": {
            "skills": [
                {
                    "name": "幽冥困魂",
                    "kind": "armor_break",
                    "chance": 26,
                    "defense_ratio_percent": 16,
                    "duration": 2,
                    "text": "幽冥魂锁锁住对手神魂，防御出现破绽。",
                }
            ],
        },
        "min_realm_stage": "元婴",
        "min_realm_layer": 2,
        "enabled": True,
    },
    {
        "name": "寒月剑",
        "rarity": "上品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以九转雪莲精华淬炼剑胚，剑身如寒月凝霜，挥剑时月华倾泻，冰寒之意令空气都凝结成霜。",
        "attack_bonus": 34,
        "defense_bonus": 12,
        "duel_rate_bonus": 5,
        "min_realm_stage": "元婴",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "丹凤扇",
        "rarity": "上品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以凤尾草融合朱雀血脉精华编织成扇面，扇骨以精金铸就，展开时如丹凤朝阳，火焰如羽。",
        "attack_bonus": 38,
        "body_movement_bonus": 12,
        "duel_rate_bonus": 4,
        "combat_config": {
            "skills": [
                {
                    "name": "丹凤朝阳",
                    "kind": "extra_damage",
                    "chance": 26,
                    "flat_damage": 20,
                    "ratio_percent": 16,
                    "text": "丹凤扇展开，火焰化作凤凰向阳飞去。",
                }
            ],
        },
        "min_realm_stage": "元婴",
        "min_realm_layer": 4,
        "enabled": True,
    },
    {
        "name": "玄冥甲",
        "rarity": "上品",
        "artifact_type": "support",
        "artifact_role": "guardian",
        "equip_slot": "chest",
        "description": "以玄武岩配合幽冥粉锻造，甲身漆黑如墨，隐有幽光流转，披挂后如幽冥护体，万法不侵。",
        "defense_bonus": 42,
        "qi_blood_bonus": 70,
        "duel_rate_bonus": 4,
        "min_realm_stage": "元婴",
        "min_realm_layer": 5,
        "enabled": True,
    },
    # ========== 新增：极品法宝 ==========
    {
        "name": "九幽寒莲杖",
        "rarity": "极品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "以九幽深渊的寒莲为源，杖身散发幽冷蓝光，一击可冻裂金丹修士护体灵光。",
        "attack_bonus": 42,
        "defense_bonus": 16,
        "true_yuan_bonus": 50,
        "duel_rate_bonus": 6,
        "combat_config": {
            "skills": [
                {
                    "name": "九幽冰封",
                    "kind": "extra_damage",
                    "chance": 32,
                    "flat_damage": 28,
                    "ratio_percent": 20,
                    "text": "九幽寒莲杖点出，万物凝结成冰。",
                }
            ],
        },
        "min_realm_stage": "化神",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "涅槃火羽扇",
        "rarity": "极品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此扇以凤凰涅槃重生之时脱落的真羽所铸，羽脉之中蕴含轮回之力，摇扇之间真火燎原，攻击自带重生之效，令敌闻风丧胆。",
        "attack_bonus": 44,
        "body_movement_bonus": 20,
        "duel_rate_bonus": 7,
        "combat_config": {
            "skills": [
                {
                    "name": "涅槃再生",
                    "kind": "heal",
                    "chance": 20,
                    "flat_heal": 24,
                    "ratio_percent": 12,
                    "text": "涅槃火羽扇扇出，伤口以肉眼可见的速度愈合。",
                }
            ],
        },
        "min_realm_stage": "化神",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "建木扶桑冠",
        "rarity": "极品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "helmet",
        "description": "此冠以建木神种培育的扶桑古木之心精心雕琢，冠形如扶桑神木参天，佩戴者可汲取天地初开之灵气，修炼速度倍增，道行精进如飞。",
        "cultivation_bonus": 20,
        "comprehension_bonus": 14,
        "fortune_bonus": 8,
        "min_realm_stage": "须弥",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "天裂剑",
        "rarity": "极品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此剑以天罚雷种淬炼剑胚，剑身有天雷纹路流转，一剑挥出如天雷勾动地火，剑光过处天裂地陷。",
        "attack_bonus": 46,
        "defense_bonus": 18,
        "true_yuan_bonus": 55,
        "duel_rate_bonus": 8,
        "combat_config": {
            "skills": [
                {
                    "name": "天雷降临",
                    "kind": "extra_damage",
                    "chance": 34,
                    "flat_damage": 32,
                    "ratio_percent": 22,
                    "text": "天裂剑引动九天雷劫，雷光如柱轰向敌人。",
                }
            ],
        },
        "min_realm_stage": "炼虚",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "轮回镜",
        "rarity": "极品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "necklace",
        "description": "以六道轮回砂配合轮回冥晶铸就镜面，镜中映照万物轮回，佩戴者可借轮回之力，令对手深陷轮回幻象。",
        "divine_sense_bonus": 22,
        "comprehension_bonus": 16,
        "fortune_bonus": 10,
        "combat_config": {
            "skills": [
                {
                    "name": "轮回困神",
                    "kind": "armor_break",
                    "chance": 30,
                    "defense_ratio_percent": 18,
                    "duration": 2,
                    "text": "轮回镜映出六道轮回之影，对手神魂被卷入轮回漩涡。",
                }
            ],
        },
        "min_realm_stage": "炼虚",
        "min_realm_layer": 2,
        "enabled": True,
    },
    # ========== 新增：仙品法宝 ==========
    {
        "name": "鸿蒙紫莲剑",
        "rarity": "仙品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此剑以鸿蒙初开时诞生的紫莲精华凝聚淬炼，剑身流转混沌紫气，剑光一出可撕裂苍穹，一剑之威足以开天辟地，乃仙家剑道之极致。",
        "attack_bonus": 56,
        "defense_bonus": 24,
        "true_yuan_bonus": 80,
        "duel_rate_bonus": 10,
        "combat_config": {
            "skills": [
                {
                    "name": "鸿蒙一剑",
                    "kind": "extra_damage",
                    "chance": 38,
                    "flat_damage": 40,
                    "ratio_percent": 26,
                    "text": "鸿蒙紫莲剑一剑斩出，鸿蒙紫气随剑而动，天地变色。",
                }
            ],
            "opening_text": "剑身上浮现鸿蒙异象，一剑之威可毁天灭地。",
        },
        "min_realm_stage": "芥子",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "凤凰真血冠",
        "rarity": "仙品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "helmet",
        "description": "此冠以凤凰一族至高真血反复淬炼而成，冠顶有凤羽环绕，熠熠生辉，佩戴者可得凤凰真火护体，纵遭致命之伤亦可涅槃重生，绝境翻盘。",
        "cultivation_bonus": 26,
        "qi_blood_bonus": 120,
        "duel_rate_bonus": 8,
        "combat_config": {
            "skills": [
                {
                    "name": "真血护体",
                    "kind": "shield",
                    "chance": 32,
                    "flat_shield": 50,
                    "ratio_percent": 24,
                    "text": "凤凰真血冠激活，浴火重生，伤势瞬间复原。",
                }
            ],
        },
        "min_realm_stage": "芥子",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "灭仙剑",
        "rarity": "仙品",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此剑以混沌灵根为胚，天道雷种为锋，剑身缠绕混沌祖气，一剑可灭仙神，剑出之时诸天仙神都要避其锋芒。",
        "attack_bonus": 62,
        "defense_bonus": 28,
        "true_yuan_bonus": 90,
        "duel_rate_bonus": 12,
        "combat_config": {
            "skills": [
                {
                    "name": "混沌灭仙",
                    "kind": "extra_damage",
                    "chance": 42,
                    "flat_damage": 50,
                    "ratio_percent": 30,
                    "text": "灭仙剑一剑斩出，混沌之气如潮水般涌向敌人。",
                }
            ],
            "opening_text": "灭仙剑出鞘，天地间顿时黯然失色，仿佛诸神都要陨落。",
        },
        "min_realm_stage": "合体",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "星辰琴",
        "rarity": "仙品",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "weapon",
        "description": "以天玄真银为琴身，鲲鹏巨羽为琴弦，弹奏时星辰之力从天而降，琴音可令山河倒转，乾坤逆转。",
        "attack_bonus": 48,
        "cultivation_bonus": 30,
        "comprehension_bonus": 20,
        "combat_config": {
            "skills": [
                {
                    "name": "星辰之泪",
                    "kind": "heal",
                    "chance": 28,
                    "flat_heal": 40,
                    "ratio_percent": 20,
                    "text": "星辰琴音律大作，点点星辉如泪滴落，疗愈琴者身心。",
                }
            ],
        },
        "min_realm_stage": "合体",
        "min_realm_layer": 2,
        "enabled": True,
    },
    # ========== 新增：先天至宝法宝 ==========
    {
        "name": "开天斧",
        "rarity": "先天至宝",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此斧以混沌初开时凝结的开天神石铸就，斧身厚重如山岳，斧刃流转鸿蒙之气，一斧劈下可裂开天地，毁天灭地，乃先天第一攻伐至宝。",
        "attack_bonus": 88,
        "defense_bonus": 40,
        "true_yuan_bonus": 150,
        "duel_rate_bonus": 15,
        "combat_config": {
            "skills": [
                {
                    "name": "开天辟地",
                    "kind": "extra_damage",
                    "chance": 45,
                    "flat_damage": 80,
                    "ratio_percent": 35,
                    "text": "开天斧携开天辟地之威斩下，苍穹碎裂，万物归虚。",
                }
            ],
            "opening_text": "巨斧高举，开天辟地的力量在斧刃上汇聚。",
        },
        "min_realm_stage": "混元一体",
        "min_realm_layer": 1,
        "enabled": True,
    },
    {
        "name": "造化玉蝶镯",
        "rarity": "先天至宝",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "bracelet",
        "description": "此镯以造化玉蝶之内丹融合天道法则精华而成，镯体晶莹如泪，蕴含重塑命运之力，佩戴者可借造化之力改写因果，逆天改命，令天地法则为之改变。",
        "cultivation_bonus": 40,
        "comprehension_bonus": 30,
        "fortune_bonus": 20,
        "duel_rate_bonus": 12,
        "combat_config": {
            "skills": [
                {
                    "name": "造化弄人",
                    "kind": "armor_break",
                    "chance": 40,
                    "defense_ratio_percent": 30,
                    "duration": 3,
                    "text": "造化玉蝶镯轻鸣，对手的命运被悄然改写。",
                }
            ],
        },
        "min_realm_stage": "混元一体",
        "min_realm_layer": 3,
        "enabled": True,
    },
    {
        "name": "盘古战鼓",
        "rarity": "先天至宝",
        "artifact_type": "battle",
        "artifact_role": "battle",
        "equip_slot": "weapon",
        "description": "此鼓以盘古精血浸泡的混沌雷种为鼓面，创世神铁铸就鼓身，敲响之时如盘古开天，鼓声可震碎诸天万界。",
        "attack_bonus": 95,
        "defense_bonus": 45,
        "true_yuan_bonus": 180,
        "duel_rate_bonus": 18,
        "combat_config": {
            "skills": [
                {
                    "name": "开天鼓震",
                    "kind": "extra_damage",
                    "chance": 50,
                    "flat_damage": 100,
                    "ratio_percent": 40,
                    "text": "盘古战鼓轰然作响，开天辟地的力量随鼓声席卷诸天。",
                }
            ],
            "opening_text": "战鼓擂动，混沌激荡，仿佛要重开天地。",
        },
        "min_realm_stage": "混元一体",
        "min_realm_layer": 5,
        "enabled": True,
    },
    {
        "name": "女娲石",
        "rarity": "先天至宝",
        "artifact_type": "support",
        "artifact_role": "support",
        "equip_slot": "necklace",
        "description": "此石以女娲补天遗留的天道玉髓为核心，融合大道金莲精华，佩戴者可获女娲护佑，断肢可重续，魂魄可重聚，天地难灭其身。",
        "cultivation_bonus": 50,
        "qi_blood_bonus": 200,
        "fortune_bonus": 30,
        "combat_config": {
            "skills": [
                {
                    "name": "女娲补天",
                    "kind": "heal",
                    "chance": 45,
                    "flat_heal": 80,
                    "ratio_percent": 35,
                    "text": "女娲石绽放五彩光芒，佩戴者伤势以肉眼可见的速度愈合。",
                }
            ],
        },
        "min_realm_stage": "混元一体",
        "min_realm_layer": 7,
        "enabled": True,
    },
]


