from __future__ import annotations

DEFAULT_ENCOUNTER_TEMPLATES = [
    # ========== 凡品奇遇 ==========
    {
        "name": "天降残页",
        "description": "半空飘落一页泛黄古卷，灵力将散未散，等有心人拾取。",
        "button_text": "抢残页",
        "success_text": "🎉 {user} 手快如电！古卷入手的刹那，隐约窥见先人炼药心得 {reward}。",
        "broadcast_text": "一页古卷残纸自半空飘落，墨迹斑驳却隐隐透着灵光。",
        "weight": 10,
        "active_seconds": 90,
        "reward_stone_min": 20,
        "reward_stone_max": 50,
        "reward_cultivation_min": 15,
        "reward_cultivation_max": 40,
        "reward_item_kind": "recipe",
        "reward_item_ref_name": "聚灵丹丹谱",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "行脚商遗包",
        "description": "鼓鼓囊囊的旧布包滚落路边，包口微张，隐约透出灵光。",
        "button_text": "捡布包",
        "success_text": "🧳 {user} 一把夺过布包！里面竟是 {reward}，商人已消失在人海。",
        "broadcast_text": "行脚商人匆匆而过，一只旧布包滚落路旁，包口正往外溢着点点灵光。",
        "weight": 9,
        "active_seconds": 80,
        "reward_stone_min": 30,
        "reward_stone_max": 70,
        "reward_item_kind": "material",
        "reward_item_ref_name": "灵露滴",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 3,
        "enabled": True,
    },
    {
        "name": "萤火指引",
        "description": "点点萤火在前方聚集成路，似乎在指引什么。",
        "button_text": "跟萤火",
        "success_text": "✨ {user} 跟随萤火指引，竟在草叶间发现 {reward}，萤火却已散去。",
        "broadcast_text": "灵山中的萤火忽然聚成一线，在前方若隐若现地闪烁。",
        "weight": 8,
        "active_seconds": 70,
        "reward_stone_min": 15,
        "reward_stone_max": 35,
        "reward_item_kind": "material",
        "reward_item_ref_name": "引路萤火",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "enabled": True,
    },
    {
        "name": "晨露凝珠",
        "description": "草叶上凝结的露珠格外剔透，蕴含微弱灵气。",
        "button_text": "收晨露",
        "success_text": "💧 {user} 俯身收取晨露，得 {reward}，身心俱爽。",
        "broadcast_text": "朝阳初升，草叶上的露珠折射出七彩微光，灵韵不凡。",
        "weight": 9,
        "active_seconds": 65,
        "reward_stone_min": 12,
        "reward_stone_max": 28,
        "reward_item_kind": "material",
        "reward_item_ref_name": "灵露滴",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "reward_cultivation_min": 10,
        "reward_cultivation_max": 25,
        "enabled": True,
    },
    # ========== 下品奇遇 ==========
    {
        "name": "祖师传音",
        "description": "冥冥中似有祖师留音自耳边响起，似在点拨修行。",
        "button_text": "静听传音",
        "success_text": "🕯️ {user} 盘膝静心聆听，祖师低语入耳，道心渐明，收获 {reward}。",
        "broadcast_text": "群中忽闻古老道音回荡，似有祖师隔空传法，字字珠玑。",
        "weight": 7,
        "active_seconds": 75,
        "reward_cultivation_min": 50,
        "reward_cultivation_max": 120,
        "enabled": True,
    },
    {
        "name": "灵宠献果",
        "description": "一只机灵小兽叼着灵果窜过，丢下果子便遁入山林。",
        "button_text": "接灵果",
        "success_text": "🍑 {user} 稳稳接住灵果，小兽甩尾远遁，只留 {reward}。",
        "broadcast_text": "机灵小兽口衔灵果跃过人群，将果一丢便没入灵山，不知所踪。",
        "weight": 8,
        "active_seconds": 70,
        "reward_stone_min": 25,
        "reward_stone_max": 55,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "清心丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "桃花仙会请帖",
        "description": "粉霞漫天飞舞，地上竟多出一张泛着金光的请帖。",
        "button_text": "夺请帖",
        "success_text": "🌸 {user} 拨开人群抢下请帖，仪态与灵韵骤增，还意外获得 {reward}。",
        "broadcast_text": "桃花香气忽然弥漫全场，一张烫金请帖凭空出现在地上，只待有缘人。",
        "weight": 6,
        "active_seconds": 85,
        "min_realm_stage": "筑基",
        "min_realm_layer": 1,
        "reward_stone_min": 40,
        "reward_stone_max": 80,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "疗伤丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "寒泉凝结",
        "description": "寒泉边凝结着点点冰晶，散发着清凉灵韵。",
        "button_text": "采冰晶",
        "success_text": "❄️ {user} 小心采下寒泉冰晶，获得 {reward}，指尖却已冻得发红。",
        "broadcast_text": "寒泉之畔水汽凝结，点点冰晶散发着幽蓝寒光，极为诱人。",
        "weight": 7,
        "active_seconds": 68,
        "reward_stone_min": 35,
        "reward_stone_max": 65,
        "reward_item_kind": "material",
        "reward_item_ref_name": "霜凌草",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "enabled": True,
    },
    {
        "name": "阳花绽放",
        "description": "崖壁缝隙间，一朵火红灵花正迎着骄阳绽放。",
        "button_text": "摘阳花",
        "success_text": "🌺 {user} 攀崖摘下烈阳花，获得 {reward}，掌心传来阵阵热意。",
        "broadcast_text": "烈日当空，崖壁缝隙中竟绽开一朵火红灵花，灵光灼灼。",
        "weight": 7,
        "active_seconds": 72,
        "reward_stone_min": 38,
        "reward_stone_max": 70,
        "reward_item_kind": "material",
        "reward_item_ref_name": "烈阳花",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "enabled": True,
    },
    # ========== 中品奇遇 ==========
    {
        "name": "冰魄凝光",
        "description": "寒潭深处一抹幽蓝光芒闪烁，似有冰魄将出未出。",
        "button_text": "探寒潭",
        "success_text": "🧊 {user} 探入寒潭深处，冰魄入手的刹那 {reward}，寒气透骨。",
        "broadcast_text": "寒潭深处泛起幽蓝波光，一枚千年冰魄似在潭底沉睡。",
        "weight": 5,
        "active_seconds": 70,
        "min_realm_stage": "结丹",
        "min_realm_layer": 1,
        "reward_stone_min": 60,
        "reward_stone_max": 120,
        "reward_item_kind": "material",
        "reward_item_ref_name": "冰魄珠",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "火鸾残羽",
        "description": "空中飘落一根火红羽毛，余烬未熄，蕴含火鸾灵韵。",
        "button_text": "截鸾羽",
        "success_text": "🔥 {user} 截住火鸾残羽，获得 {reward}，指尖传来灼灼热意。",
        "broadcast_text": "天边划过一道赤红流光，一根羽毛裹着火焰坠入人群，尚未烧尽。",
        "weight": 5,
        "active_seconds": 65,
        "min_realm_stage": "结丹",
        "min_realm_layer": 3,
        "reward_stone_min": 70,
        "reward_stone_max": 130,
        "reward_item_kind": "material",
        "reward_item_ref_name": "火鸾羽",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "天师遗符",
        "description": "古修遗址中散落着几片泛黄符骨，符文若隐若现。",
        "button_text": "寻符骨",
        "success_text": "📜 {user} 拂去符骨尘土，获得 {reward}，隐约窥见上古天师手段。",
        "broadcast_text": "古修遗迹中微光闪烁，符骨上的鬼画符文似在诉说古老传承。",
        "weight": 5,
        "active_seconds": 75,
        "min_realm_stage": "元婴",
        "min_realm_layer": 1,
        "reward_stone_min": 55,
        "reward_stone_max": 100,
        "reward_item_kind": "material",
        "reward_item_ref_name": "鬼画符骨",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "enabled": True,
    },
    {
        "name": "陨星裂匣",
        "description": "一只被陨火烧裂的旧匣从天而降，里面灵压紊乱却诱人。",
        "button_text": "开星匣",
        "success_text": "☄️ {user} 顶着灼热灵压掀开星匣，获得 {reward}，余温犹在手心。",
        "broadcast_text": "群中忽然坠下一只燃着尾焰的裂匣，匣中灵光若隐若现。",
        "weight": 4,
        "active_seconds": 60,
        "min_realm_stage": "结丹",
        "min_realm_layer": 1,
        "min_combat_power": 2600,
        "reward_stone_min": 80,
        "reward_stone_max": 150,
        "reward_item_kind": "material",
        "reward_item_ref_name": "天眷符骨",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "enabled": True,
    },
    {
        "name": "镜湖匣光",
        "description": "一抹镜色匣光贴着地面滑来，灵动而飘忽。",
        "button_text": "截镜匣",
        "success_text": "🪞 {user} 先一步截住镜匣，获得 {reward}，匣光已在掌心化开。",
        "broadcast_text": "镜色光芒一闪，一只古匣沿地面滑出，匣盖缝隙正溢着灵辉。",
        "weight": 4,
        "active_seconds": 68,
        "min_realm_stage": "结丹",
        "min_realm_layer": 4,
        "reward_stone_min": 65,
        "reward_stone_max": 120,
        "reward_item_kind": "recipe",
        "reward_item_ref_name": "照影符符谱",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    # ========== 上品奇遇 ==========
    {
        "name": "玄冰破天",
        "description": "寒光自九天而落，一块散发幽蓝光芒的玄冰精髓坠入凡尘。",
        "button_text": "接玄冰",
        "success_text": "🌨️ {user} 伸手接住玄冰精髓，获得 {reward}，寒气刺骨却舍不得放手。",
        "broadcast_text": "九天之上寒光乍现，一块玄冰精髓裹着风雪坠入人间，灵光冲霄。",
        "weight": 3,
        "active_seconds": 60,
        "min_realm_stage": "元婴",
        "min_realm_layer": 5,
        "min_combat_power": 4500,
        "reward_stone_min": 120,
        "reward_stone_max": 200,
        "reward_item_kind": "material",
        "reward_item_ref_name": "玄冰精髓",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "凤心血滴",
        "description": "火红光芒划破长空，一滴散发极致火意的心血悬浮半空。",
        "button_text": "收心血",
        "success_text": "💎 {user} 收入凤心血滴，获得 {reward}，周身温度骤然攀升。",
        "broadcast_text": "火凤虚影掠过虚空，一滴心头精血凝于半空，火光映红半边天。",
        "weight": 3,
        "active_seconds": 55,
        "min_realm_stage": "化神",
        "min_realm_layer": 1,
        "min_combat_power": 5000,
        "reward_stone_min": 150,
        "reward_stone_max": 260,
        "reward_item_kind": "material",
        "reward_item_ref_name": "烈凤心血",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "白虎破军",
        "description": "庚金之气凝聚成肃杀光芒，一块白虎神金从天而降。",
        "button_text": "夺神金",
        "success_text": "⚔️ {user} 夺下白虎神金，获得 {reward}，肃杀之气令人胆寒。",
        "broadcast_text": "白虎星宿骤然亮起，一道庚金光芒破空而降，神金落入凡尘。",
        "weight": 3,
        "active_seconds": 58,
        "min_realm_stage": "化神",
        "min_realm_layer": 3,
        "min_combat_power": 5200,
        "reward_stone_min": 140,
        "reward_stone_max": 240,
        "reward_item_kind": "material",
        "reward_item_ref_name": "白虎神金",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "问天签",
        "description": "一支古签自虚空坠下，刻满命数符文，似在择主。",
        "button_text": "接问天签",
        "success_text": "🎐 {user} 接住问天签，命数之力涌入体内，获得 {reward}。",
        "broadcast_text": "虚空中雷声隐隐，一支刻满古篆的问天签破空而降，命数之力缠绕。",
        "weight": 4,
        "active_seconds": 72,
        "min_realm_stage": "结丹",
        "min_realm_layer": 3,
        "reward_cultivation_min": 80,
        "reward_cultivation_max": 160,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "承运问天丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "仙府钥影",
        "description": "一枚散发仙光的钥匙虚影在空中闪烁，似只为强者停留。",
        "button_text": "夺钥影",
        "success_text": "🗝️ {user} 抢下钥影，获得 {reward}，似乎窥见了仙府一角。",
        "broadcast_text": "仙光乍现，一枚古朴钥匙虚影在空中时隐时现，只有有缘者方能触及。",
        "weight": 3,
        "active_seconds": 55,
        "min_realm_stage": "元婴",
        "min_realm_layer": 1,
        "min_combat_power": 4200,
        "reward_stone_min": 150,
        "reward_stone_max": 280,
        "reward_cultivation_min": 120,
        "reward_cultivation_max": 220,
        "reward_item_kind": "artifact",
        "reward_item_ref_name": "流霞问心簪",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    # ========== 极品奇遇 ==========
    {
        "name": "九幽寒莲",
        "description": "幽冥深处绽放一朵散发幽光的寒莲，亿年凝结一朵。",
        "button_text": "采寒莲",
        "success_text": "🌸 {user} 踏入九幽深处采得寒莲，获得 {reward}，幽冥之力环绕周身。",
        "broadcast_text": "九幽幽光冲天而起，一朵亿年寒莲在冥冥中绽放，只待有缘人。",
        "weight": 2,
        "active_seconds": 50,
        "min_realm_stage": "化神",
        "min_realm_layer": 7,
        "min_combat_power": 6000,
        "reward_stone_min": 200,
        "reward_stone_max": 350,
        "reward_item_kind": "material",
        "reward_item_ref_name": "九幽寒莲",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "涅槃火羽",
        "description": "浴火凤凰的羽毛自九天落下，真火仍在羽尖流转。",
        "button_text": "收凤羽",
        "success_text": "🔥 {user} 收得涅槃火羽，获得 {reward}，真火入体暖流涌动。",
        "broadcast_text": "凤凰虚影横贯长空，一根浴火羽毛带着涅槃真火缓缓降落。",
        "weight": 2,
        "active_seconds": 52,
        "min_realm_stage": "化神",
        "min_realm_layer": 7,
        "min_combat_power": 6200,
        "reward_stone_min": 220,
        "reward_stone_max": 380,
        "reward_item_kind": "material",
        "reward_item_ref_name": "涅槃火羽",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "建木之种",
        "description": "一枚散发生机的神木种子自虚空坠落，生命气息扑面而来。",
        "button_text": "接神种",
        "success_text": "🌳 {user} 接住建木之种，获得 {reward}，生机之力在掌心流转。",
        "broadcast_text": "上古神木建木虚影一闪，一枚蕴含开天辟地之力的种子从天而降。",
        "weight": 2,
        "active_seconds": 48,
        "min_realm_stage": "炼虚",
        "min_realm_layer": 1,
        "min_combat_power": 6500,
        "reward_stone_min": 250,
        "reward_stone_max": 420,
        "reward_item_kind": "material",
        "reward_item_ref_name": "建木之种",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 200,
        "reward_cultivation_max": 350,
        "enabled": True,
    },
    {
        "name": "天罚雷种",
        "description": "紫色雷光在劫云中跳动，天罚雷种似在等待有缘人。",
        "button_text": "收雷种",
        "success_text": "⚡ {user} 引雷入体收入雷种，获得 {reward}，天雷之力在经脉中奔涌。",
        "broadcast_text": "劫云密布的天空裂开一道紫色缝隙，天罚雷种在雷光中若隐若现。",
        "weight": 2,
        "active_seconds": 45,
        "min_realm_stage": "炼虚",
        "min_realm_layer": 4,
        "min_combat_power": 7000,
        "reward_stone_min": 280,
        "reward_stone_max": 450,
        "reward_item_kind": "material",
        "reward_item_ref_name": "天罚雷种",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "火陨灵核",
        "description": "一颗散发炽热的赤红灵核裹着火焰坠入人群中央。",
        "button_text": "夺灵核",
        "success_text": "💥 {user} 顶着灼浪抢下灵核，获得 {reward}，火属灵力汹涌澎湃。",
        "broadcast_text": "天边坠下一颗火红灵核，焰光冲天，热浪朝四周席卷而去。",
        "weight": 3,
        "active_seconds": 54,
        "min_realm_stage": "元婴",
        "min_realm_layer": 3,
        "min_combat_power": 3600,
        "reward_stone_min": 90,
        "reward_stone_max": 180,
        "reward_item_kind": "material",
        "reward_item_ref_name": "曜金雷髓",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 2,
        "enabled": True,
    },
    # ========== 仙品奇遇 ==========
    {
        "name": "鸿蒙紫莲",
        "description": "鸿蒙紫气化作一朵圣莲，散发超越仙界的至高气息。",
        "button_text": "摘紫莲",
        "success_text": "💜 {user} 摘下鸿蒙紫莲，获得 {reward}，混沌之气在周身环绕。",
        "broadcast_text": "鸿蒙圣境微启大门，一朵散发紫金色光芒的圣莲自虚空降临。",
        "weight": 1,
        "active_seconds": 40,
        "min_realm_stage": "合体",
        "min_realm_layer": 1,
        "min_combat_power": 8000,
        "reward_stone_min": 400,
        "reward_stone_max": 650,
        "reward_item_kind": "material",
        "reward_item_ref_name": "鸿蒙紫莲",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 400,
        "reward_cultivation_max": 600,
        "enabled": True,
    },
    {
        "name": "凤凰真血",
        "description": "凤凰一族至高无上的精血，蕴含令万物涅槃重生的力量。",
        "button_text": "承真血",
        "success_text": "🦅 {user} 承接凤凰真血，获得 {reward}，体内似有涅槃之火燃起。",
        "broadcast_text": "凤凰真灵虚影笼罩天际，一滴散发金红光芒的真血缓缓降落。",
        "weight": 1,
        "active_seconds": 42,
        "min_realm_stage": "合体",
        "min_realm_layer": 3,
        "min_combat_power": 8300,
        "reward_stone_min": 450,
        "reward_stone_max": 700,
        "reward_item_kind": "material",
        "reward_item_ref_name": "凤凰真血",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 450,
        "reward_cultivation_max": 650,
        "enabled": True,
    },
    {
        "name": "轮回祖符",
        "description": "轮回法则本源凝聚的祖符，散发幽深而浩瀚的气息。",
        "button_text": "悟轮回",
        "success_text": "♾️ {user} 感悟轮回祖符，获得 {reward}，轮回之力在识海中浮现。",
        "broadcast_text": "六道轮回之力骤然汇聚，一枚散发幽光的祖符自虚空中凝化而出。",
        "weight": 1,
        "active_seconds": 45,
        "min_realm_stage": "合体",
        "min_realm_layer": 5,
        "min_combat_power": 8500,
        "reward_stone_min": 480,
        "reward_stone_max": 750,
        "reward_item_kind": "material",
        "reward_item_ref_name": "轮回祖符",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
    {
        "name": "混沌祖气",
        "description": "混沌初开时的祖气，蕴含万法之源的神秘力量。",
        "button_text": "吸祖气",
        "success_text": "🌌 {user} 吸入混沌祖气，获得 {reward}，周身泛起混沌微光。",
        "broadcast_text": "混沌深处裂开一道缝隙，一缕散发苍茫气息的祖气缓缓溢出。",
        "weight": 1,
        "active_seconds": 38,
        "min_realm_stage": "合体",
        "min_realm_layer": 1,
        "min_combat_power": 8200,
        "reward_stone_min": 420,
        "reward_stone_max": 680,
        "reward_item_kind": "material",
        "reward_item_ref_name": "混沌祖气",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 380,
        "reward_cultivation_max": 580,
        "enabled": True,
    },
    {
        "name": "大道符纸",
        "description": "以大道之力书写的符纸，蕴含天道法则的无上威能。",
        "button_text": "悟天机",
        "success_text": "📜 {user} 参悟大道符纸，获得 {reward}，天道法则在心中烙下印记。",
        "broadcast_text": "天机台骤然亮起，一张散发金光的符纸自九霄飘落，上书大道真言。",
        "weight": 1,
        "active_seconds": 44,
        "min_realm_stage": "渡劫",
        "min_realm_layer": 1,
        "min_combat_power": 9000,
        "reward_stone_min": 500,
        "reward_stone_max": 800,
        "reward_item_kind": "material",
        "reward_item_ref_name": "大道符纸",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 500,
        "reward_cultivation_max": 700,
        "enabled": True,
    },
    # ========== 先天至宝奇遇 ==========
    {
        "name": "开天神石",
        "description": "开天辟地时诞生的第一块神石，散发创世之力的混沌光芒。",
        "button_text": "掌创世",
        "success_text": "🪨 {user} 握住开天神石，获得 {reward}，创世之力在掌中轰鸣。",
        "broadcast_text": "天地为之变色，一块散发创世光芒的神石自混沌中破空而出。",
        "weight": 1,
        "active_seconds": 35,
        "min_realm_stage": "渡劫",
        "min_realm_layer": 7,
        "min_combat_power": 10000,
        "reward_stone_min": 800,
        "reward_stone_max": 1200,
        "reward_item_kind": "material",
        "reward_item_ref_name": "开天神石",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 800,
        "reward_cultivation_max": 1200,
        "enabled": True,
    },
    {
        "name": "盘古精血",
        "description": "盘古大神遗落的精血，蕴含力之极致的洪荒力量。",
        "button_text": "承盘古",
        "success_text": "💪 {user} 承接盘古精血，获得 {reward}，肉身似有开天之势。",
        "broadcast_text": "洪荒气息笼罩天地，一滴散发苍茫威压的精血自上古时空滴落。",
        "weight": 1,
        "active_seconds": 32,
        "min_realm_stage": "渡劫",
        "min_realm_layer": 9,
        "min_combat_power": 11000,
        "reward_stone_min": 1000,
        "reward_stone_max": 1500,
        "reward_item_kind": "material",
        "reward_item_ref_name": "盘古精血",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 1000,
        "reward_cultivation_max": 1500,
        "enabled": True,
    },
    {
        "name": "造化玉蝶",
        "description": "造化神器残片，传说可重塑天地法则的神秘存在。",
        "button_text": "握造化",
        "success_text": "🦋 {user} 握住造化玉蝶，获得 {reward}，造化之力在指尖流转。",
        "broadcast_text": "造化之力骤然涌现，一只散发柔和光芒的玉蝶自虚空中缓缓凝化。",
        "weight": 1,
        "active_seconds": 30,
        "min_realm_stage": "真仙",
        "min_realm_layer": 1,
        "min_combat_power": 12000,
        "reward_stone_min": 1200,
        "reward_stone_max": 1800,
        "reward_item_kind": "material",
        "reward_item_ref_name": "造化玉蝶",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 1200,
        "reward_cultivation_max": 1800,
        "enabled": True,
    },
    {
        "name": "命运之种",
        "description": "命运法则的具象化，传说可改写命数的无上神物。",
        "button_text": "逆命轮",
        "success_text": "🌟 {user} 执掌命运之种，获得 {reward}，命数之力在掌心汇聚。",
        "broadcast_text": "命运长河骤然浮现，一枚散发命运法则的种子在河面上沉浮。",
        "weight": 1,
        "active_seconds": 28,
        "min_realm_stage": "真仙",
        "min_realm_layer": 3,
        "min_combat_power": 13000,
        "reward_stone_min": 1500,
        "reward_stone_max": 2200,
        "reward_item_kind": "material",
        "reward_item_ref_name": "命运之种",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 1500,
        "reward_cultivation_max": 2000,
        "enabled": True,
    },
    {
        "name": "时空源晶",
        "description": "时空法则凝聚的晶体，可令时光倒流的逆天神物。",
        "button_text": "握时空",
        "success_text": "⏳ {user} 握住时空源晶，获得 {reward}，时空法则在眼前流转。",
        "broadcast_text": "时空裂缝骤然裂开，一枚散发银蓝光芒的晶体从中缓缓飘出。",
        "weight": 1,
        "active_seconds": 30,
        "min_realm_stage": "真仙",
        "min_realm_layer": 5,
        "min_combat_power": 14000,
        "reward_stone_min": 1800,
        "reward_stone_max": 2500,
        "reward_item_kind": "material",
        "reward_item_ref_name": "时空源晶",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "reward_cultivation_min": 1800,
        "reward_cultivation_max": 2500,
        "enabled": True,
    },
    {
        "name": "古藤择主",
        "description": "一枚散发生机的古藤种子在空中旋转，似在寻找命定之人。",
        "button_text": "收藤种",
        "success_text": "🌿 {user} 收住古藤种子，获得 {reward}，木属灵韵沁入心脾。",
        "broadcast_text": "木香浮动间，一枚古藤种子悬于半空，灵光流转似在择主。",
        "weight": 4,
        "active_seconds": 64,
        "min_realm_stage": "结丹",
        "min_realm_layer": 2,
        "reward_stone_min": 40,
        "reward_stone_max": 90,
        "reward_item_kind": "pill",
        "reward_item_ref_name": "离魄归元丹",
        "reward_item_quantity_min": 1,
        "reward_item_quantity_max": 1,
        "enabled": True,
    },
]
