from __future__ import annotations

EXTRA_PILLS = [
    {
        "name": "碧波养元丹",
        "rarity": "下品",
        "pill_type": "cultivation",
        "effect_value": 42,
        "poison_delta": 1,
        "description": "以浅溪灵韵炼成的温和小丹，药力如细浪拍岸，适合日常稳步增补修为。",
        "materials": [("溪纹石", 1), ("银鳞藻", 2), ("归元草", 1)],
        "success": 74,
    },
    {
        "name": "寒月澄心丹",
        "rarity": "中品",
        "pill_type": "divine_sense",
        "effect_value": 9,
        "poison_delta": 2,
        "description": "月魄蚌珠与寒潭藻心同炉，服下后识海如被月光洗过一般清澈安宁。",
        "materials": [("月魄蚌珠", 1), ("寒潭藻心", 1), ("净水莲心", 1)],
        "success": 66,
    },
    {
        "name": "海魄归元丹",
        "rarity": "上品",
        "pill_type": "true_yuan",
        "effect_value": 16,
        "poison_delta": 3,
        "description": "丹中蕴着沉静海息，服后真元回流如潮，最适合久战之后温养经脉与丹田。",
        "materials": [("潮音珊瑚", 1), ("龙门真水", 1), ("星潮玄砂", 1)],
        "success": 54,
    },
    {
        "name": "潮生承运丹",
        "rarity": "极品",
        "pill_type": "fortune",
        "effect_value": 12,
        "poison_delta": 4,
        "description": "药力一涨一落，仿佛潮生潮退，服下后冥冥中更易与机缘暗合。",
        "materials": [("海眼寒晶", 1), ("星潮玄砂", 1), ("承运木心", 1)],
        "success": 46,
    },
    {
        "name": "星渊悟道丹",
        "rarity": "仙品",
        "pill_type": "comprehension",
        "effect_value": 18,
        "poison_delta": 4,
        "description": "以星渊潮核为主药，服下后念头如群星映海，最适合在瓶颈前参悟大道。",
        "materials": [("星渊潮核", 1), ("海眼寒晶", 1), ("天道精华", 1)],
        "success": 30,
    },
    {
        "name": "定心明台丹",
        "rarity": "上品",
        "pill_type": "willpower",
        "effect_value": 14,
        "poison_delta": 3,
        "description": "服下此丹，周身灵光如镜台高悬，心魔不侵，道心稳如磐石，纵使刀山火海亦不能动其分毫。",
        "materials": [("定魄灵砂", 1), ("凝露花", 1), ("玄冰胆", 1)],
        "success": 58,
    },
    {
        "name": "流霞驻颜丹",
        "rarity": "上品",
        "pill_type": "charisma",
        "effect_value": 12,
        "poison_delta": 3,
        "description": "丹成之日有流霞环绕，服下后容颜如玉，灵韵自生，一颦一笑间尽显倾城之姿。",
        "materials": [("霓裳花露", 2), ("灵雾草心", 1), ("太乙木心", 1)],
        "success": 56,
    },
    {
        "name": "承运问天丹",
        "rarity": "极品",
        "pill_type": "karma",
        "effect_value": 10,
        "poison_delta": 4,
        "description": "此丹蕴含天命玄机，服下后可借天之运，改命之数，令机缘如影随形。",
        "materials": [("承运木心", 1), ("星命玉枝", 1), ("太华灵液", 1)],
        "success": 46,
    },
    {
        "name": "太和解厄丹",
        "rarity": "极品",
        "pill_type": "clear_poison",
        "effect_value": 60,
        "poison_delta": 0,
        "description": "以天地至清之气为引，化体内浊毒于无形，服下此丹如清泉洗心，百毒不侵。",
        "materials": [("龙门真水", 1), ("造化玉露", 1), ("无垢净沙", 1)],
        "success": 44,
    },
    {
        "name": "聚宝含光丹",
        "rarity": "中品",
        "pill_type": "fortune",
        "effect_value": 8,
        "poison_delta": 2,
        "description": "丹成之时有宝光内敛，药力更偏向聚运引财，服下后更易与宝缘和机缘暗合。",
        "materials": [("星河砂", 1), ("暖玉粉", 1), ("寒水露", 1)],
        "success": 68,
    },
    {
        "name": "镜心澄神丹",
        "rarity": "极品",
        "pill_type": "divine_sense",
        "effect_value": 18,
        "poison_delta": 4,
        "description": "此丹以镜为名，服后神识如明镜高悬，纤毫毕现，斗法秘境之细节尽在掌握。",
        "materials": [("镜尘玄晶", 1), ("定魄灵砂", 1), ("星命玉枝", 1)],
        "success": 48,
    },
    {
        "name": "离魄归元丹",
        "rarity": "极品",
        "pill_type": "defense",
        "effect_value": 18,
        "poison_delta": 4,
        "description": "此丹蕴含归元之力，服后经脉如归大海，护体灵光凝而不散，纵万法轰击亦不能破。",
        "materials": [("离魄藤种", 1), ("龙门真水", 1), ("承运木心", 1)],
        "success": 46,
    },
    {
        "name": "曜金焚脉丹",
        "rarity": "仙品",
        "pill_type": "attack",
        "effect_value": 20,
        "poison_delta": 5,
        "description": "此丹以雷火之力淬炼，服下后经脉如被金火焚烧，短时间内战力暴涨，可毁天灭地。",
        "materials": [("曜金雷髓", 1), ("烬天火纹石", 1), ("赤霄铜髓", 1)],
        "success": 40,
    },
    # ========== 新增：凡品丹药 ==========
    {
        "name": "醒神丹",
        "rarity": "凡品",
        "pill_type": "comprehension",
        "effect_value": 3,
        "poison_delta": 1,
        "description": "以灵露化水，枯草为引，服下后神识渐明，悟道之路由此开启。",
        "materials": [("灵露滴", 2), ("枯叶草", 1)],
        "success": 78,
    },
    {
        "name": "强身丹",
        "rarity": "凡品",
        "pill_type": "qi_blood",
        "effect_value": 5,
        "poison_delta": 1,
        "description": "碎石研磨成粉，残月凝露化液，服下后气血充盈，筑基之路由此起步。",
        "materials": [("碎石粉", 2), ("残月水", 1)],
        "success": 76,
    },
    # ========== 新增：下品丹药 ==========
    {
        "name": "冰心丹",
        "rarity": "下品",
        "pill_type": "divine_sense",
        "effect_value": 6,
        "poison_delta": 2,
        "description": "以霜凌草为主材，服后心如冰清，神识如寒潭映月，万念俱寂。",
        "materials": [("霜凌草", 1), ("残月水", 1), ("灵露滴", 1)],
        "success": 72,
    },
    {
        "name": "烈阳丹",
        "rarity": "下品",
        "pill_type": "attack",
        "effect_value": 6,
        "poison_delta": 2,
        "description": "烈阳花为君，灵火淬炼，服后体内如燃起一团烈火，战意昂扬。",
        "materials": [("烈阳花", 1), ("碎石粉", 1), ("引路萤火", 1)],
        "success": 70,
    },
    {
        "name": "清风丹",
        "rarity": "下品",
        "pill_type": "body_movement",
        "effect_value": 6,
        "poison_delta": 2,
        "description": "轻盈如风，提升身法与闪避。",
        "materials": [("风灵石", 1), ("银丝草", 1), ("裂木甲", 1)],
        "success": 71,
    },
    {
        "name": "续命丹",
        "rarity": "下品",
        "pill_type": "cultivation",
        "effect_value": 30,
        "poison_delta": 1,
        "description": "补充少量修为，是最常用的修炼丹药。",
        "materials": [("枯叶草", 2), ("续骨藤", 1)],
        "success": 74,
    },
    {
        "name": "化瘀丹",
        "rarity": "下品",
        "pill_type": "clear_poison",
        "effect_value": 18,
        "poison_delta": 0,
        "description": "化解轻微丹毒与淤气。",
        "materials": [("化毒草", 1), ("清心兰", 1)],
        "success": 73,
    },
    # ========== 新增：中品丹药 ==========
    {
        "name": "冰魄丹",
        "rarity": "中品",
        "pill_type": "divine_sense",
        "effect_value": 10,
        "poison_delta": 3,
        "description": "寒冰之力凝聚，服后神识大增且清明。",
        "materials": [("冰魄珠", 1), ("霜凌草", 1), ("净水莲心", 1)],
        "success": 64,
    },
    {
        "name": "火鸾丹",
        "rarity": "中品",
        "pill_type": "attack",
        "effect_value": 10,
        "poison_delta": 3,
        "description": "火鸾之力灌注，大幅提升攻击力。",
        "materials": [("火鸾羽", 1), ("烈阳花", 1), ("龙涎香", 1)],
        "success": 62,
    },
    {
        "name": "木灵丹",
        "rarity": "中品",
        "pill_type": "cultivation",
        "effect_value": 60,
        "poison_delta": 2,
        "description": "蕴含生生不息之气，修为加速累积。",
        "materials": [("木灵精", 1), ("凤尾草", 1), ("千年阴沉木", 1)],
        "success": 66,
    },
    {
        "name": "金芒丹",
        "rarity": "中品",
        "pill_type": "defense",
        "effect_value": 10,
        "poison_delta": 3,
        "description": "金属性防御大增，护体灵光更固。",
        "materials": [("金芒砂", 1), ("寒铁", 1), ("玄武岩", 1)],
        "success": 63,
    },
    {
        "name": "龙髓丹",
        "rarity": "中品",
        "pill_type": "qi_blood",
        "effect_value": 12,
        "poison_delta": 3,
        "description": "地龙精华灌注，气血大幅增长。",
        "materials": [("地龙髓", 1), ("龙涎香", 1), ("九转雪莲", 1)],
        "success": 61,
    },
    {
        "name": "净心丹",
        "rarity": "中品",
        "pill_type": "willpower",
        "effect_value": 8,
        "poison_delta": 2,
        "description": "净化心神，稳固道心。",
        "materials": [("净水莲心", 1), ("清心兰", 1), ("九转雪莲", 1)],
        "success": 65,
    },
    # ========== 新增：上品丹药 ==========
    {
        "name": "玄冰真丹",
        "rarity": "上品",
        "pill_type": "divine_sense",
        "effect_value": 16,
        "poison_delta": 4,
        "description": "万年玄冰凝成的丹药，服用后神识可洞察秋毫。",
        "materials": [("玄冰精髓", 1), ("冰魄珠", 1), ("天雷符骨", 1)],
        "success": 54,
    },
    {
        "name": "烈凤真丹",
        "rarity": "上品",
        "pill_type": "attack",
        "effect_value": 16,
        "poison_delta": 4,
        "description": "火凤心血炼制，服用后攻击带有灼烧之力。",
        "materials": [("烈凤心血", 1), ("火鸾羽", 2), ("涅槃火羽", 1)],
        "success": 52,
    },
    {
        "name": "乙木长青丹",
        "rarity": "上品",
        "pill_type": "cultivation",
        "effect_value": 120,
        "poison_delta": 3,
        "description": "乙木精华凝聚，修炼速度大幅提升。",
        "materials": [("乙木精华", 1), ("不死神树皮", 1), ("青龙帝藤", 1)],
        "success": 50,
    },
    {
        "name": "太白金刚丹",
        "rarity": "上品",
        "pill_type": "defense",
        "effect_value": 16,
        "poison_delta": 4,
        "description": "太白精金炼制，护体之力可抗天雷。",
        "materials": [("太白精金", 1), ("玄武龟甲", 1), ("白虎神金", 1)],
        "success": 51,
    },
    {
        "name": "幽冥养魂丹",
        "rarity": "上品",
        "pill_type": "comprehension",
        "effect_value": 14,
        "poison_delta": 4,
        "description": "幽冥魂晶炼制，服用后悟性大增且神魂稳固。",
        "materials": [("幽冥魂晶", 1), ("轮回冥晶", 1), ("人参果精", 1)],
        "success": 48,
    },
    # ========== 新增：极品丹药 ==========
    {
        "name": "九幽寒莲丹",
        "rarity": "极品",
        "pill_type": "divine_sense",
        "effect_value": 22,
        "poison_delta": 5,
        "description": "九幽寒莲为主药，服后可与天道共鸣。",
        "materials": [("九幽寒莲", 1), ("玄冰精髓", 1), ("轮回冥晶", 1)],
        "success": 40,
    },
    {
        "name": "涅槃真火丹",
        "rarity": "极品",
        "pill_type": "attack",
        "effect_value": 22,
        "poison_delta": 5,
        "description": "凤凰涅槃之火凝聚，攻击蕴含轮回之力。",
        "materials": [("涅槃火羽", 1), ("烈凤心血", 1), ("朱雀心核", 1)],
        "success": 38,
    },
    {
        "name": "建木长生丹",
        "rarity": "极品",
        "pill_type": "cultivation",
        "effect_value": 280,
        "poison_delta": 4,
        "description": "建木之种为主药，修为可一日千里。",
        "materials": [("建木之种", 1), ("人参果精", 1), ("太虚真金", 1)],
        "success": 36,
    },
    {
        "name": "天罚雷劫丹",
        "rarity": "极品",
        "pill_type": "attack",
        "effect_value": 24,
        "poison_delta": 6,
        "description": "天罚雷种炼制，服用后攻击带天道之威。",
        "materials": [("天罚雷种", 1), ("天雷符骨", 2), ("太虚真金", 1)],
        "success": 35,
    },
    # ========== 新增：仙品丹药 ==========
    {
        "name": "鸿蒙紫莲丹",
        "rarity": "仙品",
        "pill_type": "cultivation",
        "effect_value": 500,
        "poison_delta": 5,
        "description": "鸿蒙紫莲炼制，服用后可直入化神。",
        "materials": [("鸿蒙紫莲", 1), ("混沌祖气", 1), ("五行本源", 1)],
        "success": 28,
    },
    {
        "name": "凤凰涅盘丹",
        "rarity": "仙品",
        "pill_type": "true_yuan",
        "effect_value": 30,
        "poison_delta": 4,
        "description": "凤凰真血炼制，真元生生不息。",
        "materials": [("凤凰真血", 1), ("涅槃火羽", 2), ("阴阳无极水", 1)],
        "success": 26,
    },
    {
        "name": "混沌灵根丹",
        "rarity": "仙品",
        "pill_type": "comprehension",
        "effect_value": 26,
        "poison_delta": 5,
        "description": "混沌灵根炼制，可重塑完美灵根。",
        "materials": [("混沌灵根", 1), ("天道精华", 1), ("命运之种", 1)],
        "success": 24,
    },
    {
        "name": "天雷大道丹",
        "rarity": "仙品",
        "pill_type": "attack",
        "effect_value": 28,
        "poison_delta": 6,
        "description": "天道雷种炼制，攻击蕴含天道法则。",
        "materials": [("天道雷种", 1), ("混沌雷种", 1), ("天玄真银", 1)],
        "success": 22,
    },
    # ========== 新增：先天至宝丹药 ==========
    {
        "name": "开天造化丹",
        "rarity": "先天至宝",
        "pill_type": "cultivation",
        "effect_value": 1200,
        "poison_delta": 3,
        "description": "开天神石炼制，服用后可直入混元。",
        "materials": [("开天神石", 1), ("盘古精血", 1), ("造化玉蝶", 1)],
        "success": 15,
    },
    {
        "name": "轮回天道丹",
        "rarity": "先天至宝",
        "pill_type": "true_yuan",
        "effect_value": 50,
        "poison_delta": 2,
        "description": "轮回祖符炼制，真元可与天道轮回共鸣。",
        "materials": [("轮回祖符", 1), ("本源雷种", 1), ("天道玉髓", 1)],
        "success": 12,
    },
    {
        "name": "命运主宰丹",
        "rarity": "先天至宝",
        "pill_type": "fortune",
        "effect_value": 40,
        "poison_delta": 3,
        "description": "命运之种炼制，服用后可主宰自身命运。",
        "materials": [("命运之种", 1), ("时空源晶", 1), ("大道金莲", 1)],
        "success": 10,
    },
    # ========== 补齐：秘境与奇遇引用缺失丹药 ==========
    {
        "name": "聚灵丹",
        "rarity": "凡品",
        "pill_type": "cultivation",
        "effect_value": 80,
        "poison_delta": 4,
        "description": "以温和灵材凝炼而成，最适合初入仙途者聚拢灵气、稳固吐纳节奏。",
        "materials": [("灵露滴", 1), ("归元草", 2), ("灵木芯", 1)],
        "success": 78,
    },
    {
        "name": "疗伤丹",
        "rarity": "下品",
        "pill_type": "qi_blood",
        "effect_value": 75,
        "poison_delta": 5,
        "description": "药力温厚绵长，可修补筋络创口、平复气血翻涌，是外出历练常备之丹。",
        "materials": [("续骨藤", 1), ("凝露花", 1), ("归元草", 1)],
        "success": 72,
    },
    {
        "name": "强骨丹",
        "rarity": "下品",
        "pill_type": "bone",
        "effect_value": 4,
        "poison_delta": 6,
        "description": "服后药力沉入骨髓，能缓慢强化筋骨强度，是淬体修士常用的辅助丹药。",
        "materials": [("续骨藤", 1), ("地龙髓", 1), ("灵木芯", 1)],
        "success": 64,
    },
    {
        "name": "化毒丹",
        "rarity": "下品",
        "pill_type": "clear_poison",
        "effect_value": 30,
        "poison_delta": 0,
        "description": "专为化解丹毒与杂毒所炼，药性清凉，能迅速冲散体内积郁毒性。",
        "materials": [("化毒草", 2), ("残月水", 1), ("净水莲心", 1)],
        "success": 66,
    },
    {
        "name": "冰魄寒光丹",
        "rarity": "上品",
        "pill_type": "attack",
        "effect_value": 14,
        "poison_delta": 4,
        "description": "寒魄与冰辉并融，服下后攻势自带凛冽寒光，出手更显锋锐肃杀。",
        "materials": [("冰魄珠", 1), ("九转雪莲", 1), ("玄冰精髓", 1)],
        "success": 50,
    },
    {
        "name": "火鸾炽心丹",
        "rarity": "上品",
        "pill_type": "attack",
        "effect_value": 16,
        "poison_delta": 4,
        "description": "火鸾真焰熬炼出的炽心之丹，可激发修士心火与杀伐锐气，攻势凌厉炽烈。",
        "materials": [("火鸾羽", 1), ("凤尾草", 1), ("烈凤心血", 1)],
        "success": 48,
    },
    {
        "name": "玄冰破天丹",
        "rarity": "极品",
        "pill_type": "attack",
        "effect_value": 22,
        "poison_delta": 5,
        "description": "药力如极寒天锋贯体而过，服后灵力可凝作破天寒刃，杀伐之势更上一层。",
        "materials": [("玄冰精髓", 1), ("九幽寒莲", 1), ("天玄真银", 1)],
        "success": 36,
    },
    {
        "name": "凤涅槃丹",
        "rarity": "极品",
        "pill_type": "qi_blood",
        "effect_value": 140,
        "poison_delta": 4,
        "description": "内蕴涅槃生机，服后能大幅滋养气血本源，于濒危之际也可强行续住生机。",
        "materials": [("涅槃火羽", 1), ("烈凤心血", 1), ("朱雀心核", 1)],
        "success": 34,
    },
    {
        "name": "九幽轮回丹",
        "rarity": "极品",
        "pill_type": "divine_sense",
        "effect_value": 18,
        "poison_delta": 4,
        "description": "九幽寒意与轮回之力相合，最擅温养识海、稳固神魂，对神识提升尤为显著。",
        "materials": [("九幽寒莲", 1), ("轮回冥晶", 1), ("幽冥魂晶", 1)],
        "success": 32,
    },
    {
        "name": "万木逢春丹",
        "rarity": "极品",
        "pill_type": "qi_blood",
        "effect_value": 180,
        "poison_delta": 4,
        "description": "草木生机汇于一炉，服后如万木回春，能迅速恢复亏损气血并温养肉身根基。",
        "materials": [("建木之种", 1), ("乙木精华", 1), ("人参果精", 1)],
        "success": 30,
    },
    {
        "name": "天罚破境丹",
        "rarity": "仙品",
        "pill_type": "foundation",
        "effect_value": 22,
        "poison_delta": 5,
        "description": "借天罚雷威冲击修行桎梏，适合在大境界门槛前搏一次破境机缘。",
        "materials": [("天罚雷种", 1), ("天雷符骨", 1), ("天道雷种", 1)],
        "success": 26,
    },
    {
        "name": "轮回证道丹",
        "rarity": "仙品",
        "pill_type": "comprehension",
        "effect_value": 20,
        "poison_delta": 4,
        "description": "轮回意境与大道真痕并存，服后更易于参悟生死轮转与证道玄机。",
        "materials": [("轮回祖符", 1), ("轮回冥晶", 1), ("天道玉髓", 1)],
        "success": 22,
    },
    {
        "name": "鸿蒙混沌丹",
        "rarity": "仙品",
        "pill_type": "comprehension",
        "effect_value": 24,
        "poison_delta": 5,
        "description": "鸿蒙紫意与混沌本源同炉，药成时可洗涤心神，使悟道速度更进一步。",
        "materials": [("鸿蒙紫莲", 1), ("混沌灵根", 1), ("混沌祖气", 1)],
        "success": 20,
    },
    {
        "name": "天道大同丹",
        "rarity": "先天至宝",
        "pill_type": "karma",
        "effect_value": 18,
        "poison_delta": 3,
        "description": "融通五行与天道法则，服后因果流转更趋圆融，最适合参悟大同之道。",
        "materials": [("天道精华", 1), ("天道玉髓", 1), ("五行本源", 1)],
        "success": 16,
    },
    {
        "name": "开天辟地丹",
        "rarity": "先天至宝",
        "pill_type": "cultivation",
        "effect_value": 1500,
        "poison_delta": 3,
        "description": "取开天神石与盘古精血炼成，服后药力如重演开天，足以推动修为暴涨。",
        "materials": [("开天神石", 1), ("盘古精血", 1), ("创世神铁", 1)],
        "success": 14,
    },
    {
        "name": "天道永恒丹",
        "rarity": "先天至宝",
        "pill_type": "true_yuan",
        "effect_value": 60,
        "poison_delta": 3,
        "description": "时空与命运法则交织而成，服后真元悠长不绝，颇有永恒不灭之意。",
        "materials": [("天道玉髓", 1), ("时空源晶", 1), ("命运之种", 1)],
        "success": 12,
    },
]


