from __future__ import annotations

EXTRA_RECIPES = [
    {
        "name": "听潮玉壶炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "听潮玉壶",
        "result_quantity": 1,
        "base_success_rate": 52,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "潮音珊瑚", "quantity": 2},
            {"material_name": "龙门真水", "quantity": 1},
            {"material_name": "星潮玄砂", "quantity": 1},
        ],
    },
    {
        "name": "月魄垂纶钩炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "月魄垂纶钩",
        "result_quantity": 1,
        "base_success_rate": 42,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "月魄蚌珠", "quantity": 2},
            {"material_name": "海眼寒晶", "quantity": 1},
            {"material_name": "天雷符骨", "quantity": 1},
        ],
    },
    {
        "name": "碧波养元丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "碧波养元丹",
        "result_quantity": 1,
        "base_success_rate": 74,
        "broadcast_on_success": False,
        "description": "药性温和如春溪细流，最适合打坐前服下，慢慢把散乱灵气收拢归元。",
        "ingredients": [
            {"material_name": "溪纹石", "quantity": 1},
            {"material_name": "银鳞藻", "quantity": 2},
            {"material_name": "归元草", "quantity": 1},
        ],
    },
    {
        "name": "潮生承运丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "潮生承运丹",
        "result_quantity": 1,
        "base_success_rate": 46,
        "broadcast_on_success": False,
        "description": "以潮汐涨落之理温养运势，丹成后往往伴有潮声回响，是少见的承运灵丹。",
        "ingredients": [
            {"material_name": "海眼寒晶", "quantity": 1},
            {"material_name": "星潮玄砂", "quantity": 1},
            {"material_name": "承运木心", "quantity": 1},
        ],
    },
    {
        "name": "凝潮符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "凝潮符",
        "result_quantity": 2,
        "base_success_rate": 60,
        "broadcast_on_success": False,
        "description": "潮音珊瑚调墨、龙涡骨片压符，激发后会层层叠起潮幕，最擅缓冲硬拼冲击。",
        "ingredients": [
            {"material_name": "潮音珊瑚", "quantity": 1},
            {"material_name": "龙涡骨片", "quantity": 1},
            {"material_name": "朱砂", "quantity": 1},
        ],
    },
    {
        "name": "沸海裂岸符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "沸海裂岸符",
        "result_quantity": 2,
        "base_success_rate": 42,
        "broadcast_on_success": False,
        "description": "熔鳞砂与炎珀同绘，符成似有赤潮翻岸，最适合以爆裂火浪压碎对手护体。",
        "ingredients": [
            {"material_name": "熔鳞砂", "quantity": 1},
            {"material_name": "赤髓炎珀", "quantity": 1},
            {"material_name": "曜金雷髓", "quantity": 1},
        ],
    },
    {
        "name": "定海镇心佩炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "定海镇心佩",
        "result_quantity": 1,
        "base_success_rate": 50,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "定魄灵砂", "quantity": 2},
            {"material_name": "玄龟甲片", "quantity": 1},
            {"material_name": "地脉岩芯", "quantity": 1},
        ],
    },
    {
        "name": "流霞问心簪炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "流霞问心簪",
        "result_quantity": 1,
        "base_success_rate": 42,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "霓裳花露", "quantity": 2},
            {"material_name": "承运木心", "quantity": 1},
            {"material_name": "星辉砂", "quantity": 1},
        ],
    },
    {
        "name": "回澜符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "回澜符",
        "result_quantity": 2,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "description": "以龙门真水配合玄龟骨晶绘就，符成时似有海浪回澜之象。引动后可令攻来之势折返回敬敌人，以其人之道还治其人之身。",
        "ingredients": [
            {"material_name": "定魄灵砂", "quantity": 1},
            {"material_name": "龙门真水", "quantity": 1},
            {"material_name": "玄龟骨晶", "quantity": 1},
        ],
    },
    {
        "name": "惊鸿符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "惊鸿符",
        "result_quantity": 2,
        "base_success_rate": 44,
        "broadcast_on_success": False,
        "description": "取霓裳花露配合星命玉枝绘就，符成时如惊鸿掠影、翩若游龙。引动后身法快如闪电，可从任意角度发起致命一击，令敌措手不及。",
        "ingredients": [
            {"material_name": "霓裳花露", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
            {"material_name": "璇玑星砂", "quantity": 1},
        ],
    },
    {
        "name": "定心明台丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "定心明台丹",
        "result_quantity": 1,
        "base_success_rate": 58,
        "broadcast_on_success": False,
        "description": "丹成时似有清泉流过心田，服后心如止水、杂念全消，专治神识动摇与心魔丛生之症，令灵台始终保持清明无垢。",
        "ingredients": [
            {"material_name": "定魄灵砂", "quantity": 1},
            {"material_name": "凝露花", "quantity": 1},
            {"material_name": "玄冰胆", "quantity": 1},
        ],
    },
    {
        "name": "流霞驻颜丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "流霞驻颜丹",
        "result_quantity": 1,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "description": "丹成时隐有流光溢彩，如朝霞映雪、晚霞漫天。服后可保青春永驻、容颜不改，纵是岁月流转亦不改分毫，是修仙界最受欢迎的驻颜灵丹。",
        "ingredients": [
            {"material_name": "霓裳花露", "quantity": 2},
            {"material_name": "灵雾草心", "quantity": 1},
            {"material_name": "太乙木心", "quantity": 1},
        ],
    },
    {
        "name": "承运问天丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "承运问天丹",
        "result_quantity": 1,
        "base_success_rate": 46,
        "broadcast_on_success": True,
        "description": "丹成时似有天命所归之象，星辰流转其中。服用者可借天地气运于一身，于冥冥中洞察天机、感悟天命，寻得那一线突破的契机。",
        "ingredients": [
            {"material_name": "承运木心", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
            {"material_name": "太华灵液", "quantity": 1},
        ],
    },
    {
        "name": "太和解厄丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "太和解厄丹",
        "result_quantity": 1,
        "base_success_rate": 44,
        "broadcast_on_success": False,
        "description": "丹成时清气回旋，似有山河浊晦尽数洗去。服后可借太和之意化解体内丹毒与外来浊气，最适合久服灵药或深陷毒瘴者调息复元。",
        "ingredients": [
            {"material_name": "龙门真水", "quantity": 1},
            {"material_name": "造化玉露", "quantity": 1},
            {"material_name": "无垢净沙", "quantity": 1},
        ],
    },
    {
        "name": "聚宝含光丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "聚宝含光丹",
        "result_quantity": 1,
        "base_success_rate": 68,
        "broadcast_on_success": False,
        "description": "丹成时星砂流光内敛，似有财气汇拢成珠。服后可将散落灵机化作可感的灵石收益，最适合外出历练后回补囊中所需。",
        "ingredients": [
            {"material_name": "星河砂", "quantity": 1},
            {"material_name": "暖玉粉", "quantity": 1},
            {"material_name": "寒水露", "quantity": 1},
        ],
    },
    {
        "name": "补天丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "补天丹",
        "result_quantity": 1,
        "base_success_rate": 30,
        "broadcast_on_success": True,
        "description": "取天道精华调和五行本源，再以玉髓稳固药性，成丹后最善补缀灵根缺漏、稳步拔升资质层次。",
        "ingredients": [
            {"material_name": "天道精华", "quantity": 1},
            {"material_name": "五行本源", "quantity": 1},
            {"material_name": "天道玉髓", "quantity": 1},
        ],
    },
    {
        "name": "洗灵丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "洗灵丹",
        "result_quantity": 1,
        "base_success_rate": 24,
        "broadcast_on_success": True,
        "description": "以天道玉髓为骨、命运之种为引、时空源晶为锋，成丹后可洗去旧根旧障，为灵根重塑留出一线天机。",
        "ingredients": [
            {"material_name": "天道玉髓", "quantity": 1},
            {"material_name": "命运之种", "quantity": 1},
            {"material_name": "时空源晶", "quantity": 1},
        ],
    },
    {
        "name": "照骨问心镜炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "照骨问心镜",
        "result_quantity": 1,
        "base_success_rate": 42,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "镜尘玄晶", "quantity": 2},
            {"material_name": "承运木心", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
        ],
    },
    {
        "name": "赤霄逐日弓炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "赤霄逐日弓",
        "result_quantity": 1,
        "base_success_rate": 34,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "曜金雷髓", "quantity": 1},
            {"material_name": "烬天火纹石", "quantity": 1},
            {"material_name": "太虚陨铁", "quantity": 1},
        ],
    },
    {
        "name": "照影符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "照影符",
        "result_quantity": 2,
        "base_success_rate": 48,
        "broadcast_on_success": False,
        "description": "以镜尘玄晶配合星命玉枝绘就，符成时如明镜照影、真假难辨。引动后可分化数道幻影迷惑敌人，真身则隐于暗处伺机而动。",
        "ingredients": [
            {"material_name": "镜尘玄晶", "quantity": 1},
            {"material_name": "霓裳花露", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
        ],
    },
    {
        "name": "镇魄封脉符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "镇魄封脉符",
        "result_quantity": 2,
        "base_success_rate": 38,
        "broadcast_on_success": False,
        "description": "取离魄藤种配合天眷符骨炼就，符成时阴风阵阵似有鬼神低语。专封对手经脉穴位，令其真元流转受阻、战力大减。",
        "ingredients": [
            {"material_name": "离魄藤种", "quantity": 1},
            {"material_name": "天眷符骨", "quantity": 1},
            {"material_name": "曜金雷髓", "quantity": 1},
        ],
    },
    {
        "name": "镜心澄神丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "镜心澄神丹",
        "result_quantity": 1,
        "base_success_rate": 48,
        "broadcast_on_success": False,
        "description": "丹成时澄澈如镜，可照见本心。服后神识如经明镜之水洗涤，杂念不生、心魔不染，于修炼之中时刻保持通透明澈，悟道速度倍增。",
        "ingredients": [
            {"material_name": "镜尘玄晶", "quantity": 1},
            {"material_name": "定魄灵砂", "quantity": 1},
            {"material_name": "星命玉枝", "quantity": 1},
        ],
    },
    {
        "name": "离魄归元丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "离魄归元丹",
        "result_quantity": 1,
        "base_success_rate": 46,
        "broadcast_on_success": False,
        "description": "专治神魂离散、元气溃散之症。丹成时有灵光萦绕，服后散乱的神魂重新凝聚、游离的元气复归丹田，令修士恢复完整状态。",
        "ingredients": [
            {"material_name": "离魄藤种", "quantity": 1},
            {"material_name": "龙门真水", "quantity": 1},
            {"material_name": "承运木心", "quantity": 1},
        ],
    },
    {
        "name": "曜金焚脉丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "曜金焚脉丹",
        "result_quantity": 1,
        "base_success_rate": 40,
        "broadcast_on_success": True,
        "description": "丹成时金火交织、烈芒逼人。服后经脉如被金色火焰淬炼，锐金之气贯穿体脉，令出招时带有灼热难当的金系伤害，令人防不胜防。",
        "ingredients": [
            {"material_name": "曜金雷髓", "quantity": 1},
            {"material_name": "烬天火纹石", "quantity": 1},
            {"material_name": "赤霄铜髓", "quantity": 1},
        ],
    },
    # ========== 新增：凡品丹药炼制图 ==========
    {
        "name": "醒神丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "醒神丹",
        "result_quantity": 1,
        "base_success_rate": 78,
        "broadcast_on_success": False,
        "description": "丹成时散发清新草木香气，入口如被晨露润泽。服后昏沉尽去、神思清明，适合修士深夜修炼后恢复精力所用，为最基础的增益丹药。",
        "ingredients": [
            {"material_name": "灵露滴", "quantity": 2},
            {"material_name": "枯叶草", "quantity": 1},
        ],
    },
    {
        "name": "强身丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "强身丹",
        "result_quantity": 1,
        "base_success_rate": 76,
        "broadcast_on_success": False,
        "description": "丹体呈淡褐色，入口即有一股厚实之气流转脏腑。服后脾胃得健、体魄渐强，虽是凡品却是炼气初期修士强身健体的上佳选择。",
        "ingredients": [
            {"material_name": "碎石粉", "quantity": 2},
            {"material_name": "残月水", "quantity": 1},
        ],
    },
    # ========== 新增：下品丹药炼制图 ==========
    {
        "name": "冰心丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "冰心丹",
        "result_quantity": 1,
        "base_success_rate": 72,
        "broadcast_on_success": False,
        "description": "丹成时寒气内敛、外观如冰。入口如含寒泉，冰凉之意直透心脉，可平息体内燥热、清除经脉杂火，令修士在炎热环境中亦能保持灵台清明。",
        "ingredients": [
            {"material_name": "霜凌草", "quantity": 1},
            {"material_name": "残月水", "quantity": 1},
            {"material_name": "灵露滴", "quantity": 1},
        ],
    },
    {
        "name": "烈阳丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "烈阳丹",
        "result_quantity": 1,
        "base_success_rate": 70,
        "broadcast_on_success": False,
        "description": "丹成时如火球内蕴，散发灼热气息。入口如吞烈阳，热浪瞬间充斥丹田，可驱散体内寒气、温暖经脉脏腑，令冰寒之症不药而愈。",
        "ingredients": [
            {"material_name": "烈阳花", "quantity": 1},
            {"material_name": "碎石粉", "quantity": 1},
            {"material_name": "引路萤火", "quantity": 1},
        ],
    },
    {
        "name": "清风丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "清风丹",
        "result_quantity": 1,
        "base_success_rate": 71,
        "broadcast_on_success": False,
        "description": "丹成时似有清风拂面，入口即感神清气爽。服后身法愈发轻盈，举手投足间如清风拂柳，适合需要灵活走位与闪避的修士服用。",
        "ingredients": [
            {"material_name": "风灵石", "quantity": 1},
            {"material_name": "银丝草", "quantity": 1},
            {"material_name": "裂木甲", "quantity": 1},
        ],
    },
    {
        "name": "续命丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "续命丹",
        "result_quantity": 1,
        "base_success_rate": 74,
        "broadcast_on_success": False,
        "description": "丹体嫩绿如春芽，散发盎然生机。专治内外伤痛，服后可加速伤口愈合、修复损伤经脉，虽是凡品却能在危急时刻救人一命。",
        "ingredients": [
            {"material_name": "枯叶草", "quantity": 2},
            {"material_name": "续骨藤", "quantity": 1},
        ],
    },
    {
        "name": "化瘀丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "化瘀丹",
        "result_quantity": 1,
        "base_success_rate": 73,
        "broadcast_on_success": False,
        "description": "丹成时隐有草木清香，入口即有一股化解之力流布全身。可消散淤血、疏通经脉，对陈年旧疾与斗法淤伤皆有良好疗效。",
        "ingredients": [
            {"material_name": "化毒草", "quantity": 1},
            {"material_name": "清心兰", "quantity": 1},
        ],
    },
    # ========== 新增：中品丹药炼制图 ==========
    {
        "name": "冰魄丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "冰魄丹",
        "result_quantity": 1,
        "base_success_rate": 64,
        "broadcast_on_success": False,
        "description": "丹成时寒光四射，如千年寒潭凝结而成。入口后冰魄之气直入识海，可大幅提升神识抗性与寒冷伤害，并对神识类攻击有不错的防护效果。",
        "ingredients": [
            {"material_name": "冰魄珠", "quantity": 1},
            {"material_name": "霜凌草", "quantity": 1},
            {"material_name": "净水莲心", "quantity": 1},
        ],
    },
    {
        "name": "火鸾丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "火鸾丹",
        "result_quantity": 1,
        "base_success_rate": 62,
        "broadcast_on_success": False,
        "description": "丹成时火焰缭绕，如火鸾翔空。入口后火鸾之力融入真元，令真元带上烈焰特性，攻击时附带的灼烧效果可令敌人苦不堪言。",
        "ingredients": [
            {"material_name": "火鸾羽", "quantity": 1},
            {"material_name": "烈阳花", "quantity": 1},
            {"material_name": "龙涎香", "quantity": 1},
        ],
    },
    {
        "name": "木灵丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "木灵丹",
        "result_quantity": 1,
        "base_success_rate": 66,
        "broadcast_on_success": False,
        "description": "丹成时木气盎然、生机勃发。入口如沐春风，木灵精华滋养脏腑，可加速伤势恢复并小幅提升气血上限，令修士更加持久。",
        "ingredients": [
            {"material_name": "木灵精", "quantity": 1},
            {"material_name": "凤尾草", "quantity": 1},
            {"material_name": "千年阴沉木", "quantity": 1},
        ],
    },
    {
        "name": "金芒丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "金芒丹",
        "result_quantity": 1,
        "base_success_rate": 63,
        "broadcast_on_success": False,
        "description": "丹成时金光璀璨、锋芒逼人。入口后锐金之气贯穿经脉，令攻击带上金属性的锐利，穿透与破甲能力皆大幅提升。",
        "ingredients": [
            {"material_name": "金芒砂", "quantity": 1},
            {"material_name": "寒铁", "quantity": 1},
            {"material_name": "玄武岩", "quantity": 1},
        ],
    },
    {
        "name": "龙髓丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "龙髓丹",
        "result_quantity": 1,
        "base_success_rate": 61,
        "broadcast_on_success": False,
        "description": "丹成时隐有龙吟之声，药力磅礴如海。入口后龙之髓力融入骨骼，可大幅强化体质，令体魄如龙躯般强健，持久作战能力飙升。",
        "ingredients": [
            {"material_name": "地龙髓", "quantity": 1},
            {"material_name": "龙涎香", "quantity": 1},
            {"material_name": "九转雪莲", "quantity": 1},
        ],
    },
    {
        "name": "净心丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "净心丹",
        "result_quantity": 1,
        "base_success_rate": 65,
        "broadcast_on_success": False,
        "description": "丹成时如莲花出水，散发清香。专治心神不宁、杂念丛生之症，服后心如净水、杂念不生，修炼效率大幅提升，且能抵抗心魔入侵。",
        "ingredients": [
            {"material_name": "净水莲心", "quantity": 1},
            {"material_name": "清心兰", "quantity": 1},
            {"material_name": "九转雪莲", "quantity": 1},
        ],
    },
    # ========== 新增：上品丹药炼制图 ==========
    {
        "name": "玄冰真丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "玄冰真丹",
        "result_quantity": 1,
        "base_success_rate": 54,
        "broadcast_on_success": True,
        "description": "丹成时万里冰封，寒气足以冻裂金石。入口后玄冰真气充盈识海，令神识产生质变，不仅大幅提升冰系伤害，更能以寒气护体，令敌望而生畏。",
        "ingredients": [
            {"material_name": "玄冰精髓", "quantity": 1},
            {"material_name": "冰魄珠", "quantity": 1},
            {"material_name": "天雷符骨", "quantity": 1},
        ],
    },
    {
        "name": "烈凤真丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "烈凤真丹",
        "result_quantity": 1,
        "base_success_rate": 52,
        "broadcast_on_success": True,
        "description": "丹成时火焰蒸腾，如凤凰浴火重生。入口后烈凤真火融入丹田，真元与气血皆带烈焰特性，攻击时附带灼烧与持续伤害，令敌在火焰中化为灰烬。",
        "ingredients": [
            {"material_name": "烈凤心血", "quantity": 1},
            {"material_name": "火鸾羽", "quantity": 2},
            {"material_name": "涅槃火羽", "quantity": 1},
        ],
    },
    {
        "name": "乙木长青丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "乙木长青丹",
        "result_quantity": 1,
        "base_success_rate": 50,
        "broadcast_on_success": True,
        "description": "丹成时木气冲天，似有青龙盘旋其中。入口后乙木精华彻底激活生机本源，不仅伤势恢复速度倍增，更能延缓衰老、延长寿元，是修仙界难得的延寿灵丹。",
        "ingredients": [
            {"material_name": "乙木精华", "quantity": 1},
            {"material_name": "不死神树皮", "quantity": 1},
            {"material_name": "青龙帝藤", "quantity": 1},
        ],
    },
    {
        "name": "太白金刚丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "太白金刚丹",
        "result_quantity": 1,
        "base_success_rate": 51,
        "broadcast_on_success": True,
        "description": "丹成时金光万丈，如太白星君降临。入口后金刚不坏之气贯穿全身，体魄坚硬如神铁，防御力大幅提升，寻常攻击难伤分毫，堪称防御类丹药中的极品。",
        "ingredients": [
            {"material_name": "太白精金", "quantity": 1},
            {"material_name": "玄武龟甲", "quantity": 1},
            {"material_name": "白虎神金", "quantity": 1},
        ],
    },
    {
        "name": "幽冥养魂丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "幽冥养魂丹",
        "result_quantity": 1,
        "base_success_rate": 48,
        "broadcast_on_success": True,
        "description": "丹成时幽光闪烁，似有鬼神低语。入口后幽冥之力温养神魂，令魂魄愈发凝实强大，神识攻击与抵抗皆大幅提升，更能从幽冥中汲取力量。",
        "ingredients": [
            {"material_name": "幽冥魂晶", "quantity": 1},
            {"material_name": "轮回冥晶", "quantity": 1},
            {"material_name": "人参果精", "quantity": 1},
        ],
    },
    # ========== 新增：极品丹药炼制图 ==========
    {
        "name": "九幽寒莲丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "九幽寒莲丹",
        "result_quantity": 1,
        "base_success_rate": 40,
        "broadcast_on_success": True,
        "description": "丹成时九幽寒气弥漫，莲花瓣瓣绽放。取九幽寒莲为主材炼就，入口后至寒之力冰封经脉，不仅攻击带有刺骨寒意，更能在体内凝聚寒莲护体，攻防一体。",
        "ingredients": [
            {"material_name": "九幽寒莲", "quantity": 1},
            {"material_name": "玄冰精髓", "quantity": 1},
            {"material_name": "轮回冥晶", "quantity": 1},
        ],
    },
    {
        "name": "涅槃真火丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "涅槃真火丹",
        "result_quantity": 1,
        "base_success_rate": 38,
        "broadcast_on_success": True,
        "description": "丹成时火光冲天，似有凤凰涅槃之象。以朱雀心核配合涅槃火羽炼就，入口后浴火重生之意充斥全身，每次攻击皆带灭世真火，更可浴火复活一次。",
        "ingredients": [
            {"material_name": "涅槃火羽", "quantity": 1},
            {"material_name": "烈凤心血", "quantity": 1},
            {"material_name": "朱雀心核", "quantity": 1},
        ],
    },
    {
        "name": "建木长生丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "建木长生丹",
        "result_quantity": 1,
        "base_success_rate": 36,
        "broadcast_on_success": True,
        "description": "丹成时生机如海，隐约可见神树参天之影。服用后可获建木不朽之生机，白骨生肉、白发转黑，寿元大增，是修仙界可遇不可求的逆天延寿丹。",
        "ingredients": [
            {"material_name": "建木之种", "quantity": 1},
            {"material_name": "人参果精", "quantity": 1},
            {"material_name": "太虚真金", "quantity": 1},
        ],
    },
    {
        "name": "天罚雷劫丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "天罚雷劫丹",
        "result_quantity": 1,
        "base_success_rate": 35,
        "broadcast_on_success": True,
        "description": "丹成时雷声滚滚，似有天劫降临。以天罚雷种配合雷劫符骨炼就，入口后天雷之力融入丹田，攻击时天雷纵横、威能无量，更能引动天雷附身。",
        "ingredients": [
            {"material_name": "天罚雷种", "quantity": 1},
            {"material_name": "天雷符骨", "quantity": 2},
            {"material_name": "太虚真金", "quantity": 1},
        ],
    },
    # ========== 新增：仙品丹药炼制图 ==========
    {
        "name": "鸿蒙紫莲丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "鸿蒙紫莲丹",
        "result_quantity": 1,
        "base_success_rate": 28,
        "broadcast_on_success": True,
        "description": "丹成时紫气东来、莲香四溢，似有仙人大能隐于丹中讲道。服用者可借鸿蒙紫气洗涤全身凡胎，根骨悟性皆获升华，为登仙之路上无上神丹。",
        "ingredients": [
            {"material_name": "鸿蒙紫莲", "quantity": 1},
            {"material_name": "混沌祖气", "quantity": 1},
            {"material_name": "五行本源", "quantity": 1},
        ],
    },
    {
        "name": "凤凰涅盘丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "凤凰涅盘丹",
        "result_quantity": 1,
        "base_success_rate": 26,
        "broadcast_on_success": True,
        "description": "丹成时火光万丈、凤鸣九天，似有凤凰神兽重生之象。服用者可得凤凰涅槃之力，不仅修为突飞猛进，更能在陨落之时浴火重生，堪称逆天改命之神丹。",
        "ingredients": [
            {"material_name": "凤凰真血", "quantity": 1},
            {"material_name": "涅槃火羽", "quantity": 2},
            {"material_name": "阴阳无极水", "quantity": 1},
        ],
    },
    {
        "name": "混沌灵根丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "混沌灵根丹",
        "result_quantity": 1,
        "base_success_rate": 24,
        "broadcast_on_success": True,
        "description": "丹成时混沌气流萦绕，仿佛天地初开之景。服用者可将灵根彻底化为混沌属性，功法修炼再无属性相克之限，容纳天地万法，是灵根进化的极致之路。",
        "ingredients": [
            {"material_name": "混沌灵根", "quantity": 1},
            {"material_name": "天道精华", "quantity": 1},
            {"material_name": "命运之种", "quantity": 1},
        ],
    },
    {
        "name": "天雷大道丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "天雷大道丹",
        "result_quantity": 1,
        "base_success_rate": 22,
        "broadcast_on_success": True,
        "description": "丹成时天雷滚滚、大道轰鸣，似有天道法则降临。服用者可掌控天雷大道，雷霆之力随心所欲，更能以天雷淬体，令肉身如雷霆般刚猛无匹。",
        "ingredients": [
            {"material_name": "天道雷种", "quantity": 1},
            {"material_name": "混沌雷种", "quantity": 1},
            {"material_name": "天玄真银", "quantity": 1},
        ],
    },
    # ========== 新增：先天至宝丹药炼制图 ==========
    {
        "name": "开天造化丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "开天造化丹",
        "result_quantity": 1,
        "base_success_rate": 15,
        "broadcast_on_success": True,
        "description": "丹成时开天辟地之象隐现，仿佛混沌初分、天地初开。以盘古精血配合开天神石炼就，服用者可获开天造化之力，不仅修为直入化神，更能以造化之力重塑自身根基。",
        "ingredients": [
            {"material_name": "开天神石", "quantity": 1},
            {"material_name": "盘古精血", "quantity": 1},
            {"material_name": "造化玉蝶", "quantity": 1},
        ],
    },
    {
        "name": "轮回天道丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "轮回天道丹",
        "result_quantity": 1,
        "base_success_rate": 12,
        "broadcast_on_success": True,
        "description": "丹成时轮回之力弥漫，因果之道隐现其间。以轮回祖符配合天道法则炼就，服用者可掌控轮回大道，生死轮回皆在掌握，起死回生不过一念之间。",
        "ingredients": [
            {"material_name": "轮回祖符", "quantity": 1},
            {"material_name": "本源雷种", "quantity": 1},
            {"material_name": "天道玉髓", "quantity": 1},
        ],
    },
    {
        "name": "命运主宰丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "命运主宰丹",
        "result_quantity": 1,
        "base_success_rate": 10,
        "broadcast_on_success": True,
        "description": "丹成时星辰运转、命运长河浮现，仿佛万古因果皆系于丹中。服用者可一跃成为命运的主宰，寿元无限、境界无滞，修炼之路再无瓶颈，是超越天道之上的逆天禁丹。",
        "ingredients": [
            {"material_name": "命运之种", "quantity": 1},
            {"material_name": "时空源晶", "quantity": 1},
            {"material_name": "大道金莲", "quantity": 1},
        ],
    },
    # ========== 新增：凡品法宝炼制图 ==========
    {
        "name": "玄铁短剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "玄铁短剑",
        "result_quantity": 1,
        "base_success_rate": 80,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "碎石粉", "quantity": 3},
            {"material_name": "玄铁残片", "quantity": 1},
        ],
    },
    {
        "name": "布衣护腕炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "布衣护腕",
        "result_quantity": 1,
        "base_success_rate": 78,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "灵木碎屑", "quantity": 3},
            {"material_name": "引路萤火", "quantity": 1},
        ],
    },
    {
        "name": "翠竹杖炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "翠竹杖",
        "result_quantity": 1,
        "base_success_rate": 78,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "翠竹片", "quantity": 3},
            {"material_name": "枯叶草", "quantity": 2},
        ],
    },
    {
        "name": "草灵镯炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "草灵镯",
        "result_quantity": 1,
        "base_success_rate": 76,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "草灵纤维", "quantity": 3},
            {"material_name": "灵露滴", "quantity": 2},
        ],
    },
    # ========== 新增：下品法宝炼制图 ==========
    {
        "name": "寒霜剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "寒霜剑",
        "result_quantity": 1,
        "base_success_rate": 70,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "寒铁", "quantity": 2},
            {"material_name": "霜凌草", "quantity": 1},
            {"material_name": "精钢", "quantity": 1},
        ],
    },
    {
        "name": "烈阳刀炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "烈阳刀",
        "result_quantity": 1,
        "base_success_rate": 68,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "精钢", "quantity": 2},
            {"material_name": "烈阳花", "quantity": 1},
            {"material_name": "火牛角", "quantity": 1},
        ],
    },
    {
        "name": "清风靴炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "清风靴",
        "result_quantity": 1,
        "base_success_rate": 72,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "银丝草", "quantity": 2},
            {"material_name": "风灵石", "quantity": 1},
            {"material_name": "裂木甲", "quantity": 1},
        ],
    },
    {
        "name": "震雷锤炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "震雷锤",
        "result_quantity": 1,
        "base_success_rate": 66,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "雷击桃木心", "quantity": 2},
            {"material_name": "导电精金", "quantity": 2},
            {"material_name": "精钢", "quantity": 1},
        ],
    },
    {
        "name": "霜风剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "霜风剑",
        "result_quantity": 1,
        "base_success_rate": 68,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "寒铁", "quantity": 2},
            {"material_name": "霜风草", "quantity": 2},
            {"material_name": "精钢", "quantity": 1},
        ],
    },
    {
        "name": "厚土盾炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "厚土盾",
        "result_quantity": 1,
        "base_success_rate": 64,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "千年阴沉木", "quantity": 2},
            {"material_name": "玄武岩片", "quantity": 2},
            {"material_name": "浊煞泥", "quantity": 1},
        ],
    },
    # ========== 新增：中品法宝炼制图 ==========
    {
        "name": "冰魄剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "冰魄剑",
        "result_quantity": 1,
        "base_success_rate": 60,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "寒铁", "quantity": 2},
            {"material_name": "冰魄珠", "quantity": 1},
            {"material_name": "金芒砂", "quantity": 1},
        ],
    },
    {
        "name": "火鸾羽扇炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "火鸾羽扇",
        "result_quantity": 1,
        "base_success_rate": 58,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "火鸾羽", "quantity": 2},
            {"material_name": "火牛角", "quantity": 1},
            {"material_name": "千年阴沉木", "quantity": 1},
        ],
    },
    {
        "name": "金刚护甲炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "金刚护甲",
        "result_quantity": 1,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "玄武岩", "quantity": 2},
            {"material_name": "金芒砂", "quantity": 1},
            {"material_name": "寒铁", "quantity": 1},
        ],
    },
    {
        "name": "木灵珠炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "木灵珠",
        "result_quantity": 1,
        "base_success_rate": 62,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "木灵精", "quantity": 1},
            {"material_name": "千年阴沉木", "quantity": 2},
            {"material_name": "净水莲心", "quantity": 1},
        ],
    },
    {
        "name": "神鹤剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "神鹤剑",
        "result_quantity": 1,
        "base_success_rate": 58,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "仙鹤腿骨", "quantity": 2},
            {"material_name": "仙鹤羽", "quantity": 2},
            {"material_name": "寒铁", "quantity": 1},
        ],
    },
    {
        "name": "焰虎斧炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "焰虎斧",
        "result_quantity": 1,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "焰虎牙", "quantity": 2},
            {"material_name": "烈阳花", "quantity": 2},
            {"material_name": "精钢", "quantity": 2},
        ],
    },
    {
        "name": "玄风盾炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "玄风盾",
        "result_quantity": 1,
        "base_success_rate": 54,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "玄狐皮", "quantity": 2},
            {"material_name": "风灵石", "quantity": 2},
            {"material_name": "妖狐尾毛", "quantity": 1},
        ],
    },
    {
        "name": "根灵甲炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "根灵甲",
        "result_quantity": 1,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "ingredients": [
            {"material_name": "树灵根", "quantity": 2},
            {"material_name": "木灵精", "quantity": 1},
            {"material_name": "玄武岩", "quantity": 1},
        ],
    },
    # ========== 新增：上品法宝炼制图 ==========
    {
        "name": "玄冰剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "玄冰剑",
        "result_quantity": 1,
        "base_success_rate": 50,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "陨铁寒晶", "quantity": 2},
            {"material_name": "玄冰精髓", "quantity": 1},
            {"material_name": "金翅大鹏羽", "quantity": 1},
        ],
    },
    {
        "name": "烈凤杖炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "烈凤杖",
        "result_quantity": 1,
        "base_success_rate": 48,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "烈凤心血", "quantity": 1},
            {"material_name": "火鸾羽", "quantity": 2},
            {"material_name": "白虎神金", "quantity": 1},
        ],
    },
    {
        "name": "太白神盾炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "太白神盾",
        "result_quantity": 1,
        "base_success_rate": 46,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "太白精金", "quantity": 2},
            {"material_name": "玄武龟甲", "quantity": 1},
            {"material_name": "天雷符骨", "quantity": 1},
        ],
    },
    {
        "name": "幽冥魂锁炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "幽冥魂锁",
        "result_quantity": 1,
        "base_success_rate": 44,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "幽冥魂晶", "quantity": 1},
            {"material_name": "轮回冥晶", "quantity": 1},
            {"material_name": "青龙之鳞", "quantity": 1},
        ],
    },
    {
        "name": "寒月剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "寒月剑",
        "result_quantity": 1,
        "base_success_rate": 44,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "月华霜", "quantity": 2},
            {"material_name": "九转雪莲", "quantity": 1},
            {"material_name": "玄冰精髓", "quantity": 1},
        ],
    },
    {
        "name": "丹凤扇炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "丹凤扇",
        "result_quantity": 1,
        "base_success_rate": 42,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "朱雀心血", "quantity": 1},
            {"material_name": "凤尾草", "quantity": 2},
            {"material_name": "烈凤心血", "quantity": 1},
        ],
    },
    {
        "name": "玄冥甲炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "玄冥甲",
        "result_quantity": 1,
        "base_success_rate": 42,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "冥幽铁", "quantity": 2},
            {"material_name": "幽冥魂晶", "quantity": 1},
            {"material_name": "玄武龟甲", "quantity": 1},
        ],
    },
    # ========== 新增：极品法宝炼制图 ==========
    {
        "name": "九幽寒莲杖炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "九幽寒莲杖",
        "result_quantity": 1,
        "base_success_rate": 38,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "九幽寒莲", "quantity": 1},
            {"material_name": "玄冰精髓", "quantity": 2},
            {"material_name": "轮回冥晶", "quantity": 1},
        ],
    },
    {
        "name": "涅槃火羽扇炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "涅槃火羽扇",
        "result_quantity": 1,
        "base_success_rate": 36,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "涅槃火羽", "quantity": 1},
            {"material_name": "凤凰真血", "quantity": 1},
            {"material_name": "朱雀心核", "quantity": 1},
        ],
    },
    {
        "name": "建木扶桑冠炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "建木扶桑冠",
        "result_quantity": 1,
        "base_success_rate": 34,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "建木之种", "quantity": 1},
            {"material_name": "青龙帝藤", "quantity": 2},
            {"material_name": "人参果精", "quantity": 1},
        ],
    },
    {
        "name": "天裂剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "天裂剑",
        "result_quantity": 1,
        "base_success_rate": 32,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "天裂雷晶", "quantity": 2},
            {"material_name": "天罚雷种", "quantity": 1},
            {"material_name": "太虚真金", "quantity": 1},
        ],
    },
    {
        "name": "轮回镜炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "轮回镜",
        "result_quantity": 1,
        "base_success_rate": 30,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "六道轮回砂", "quantity": 2},
            {"material_name": "轮回冥晶", "quantity": 1},
            {"material_name": "天师传承符骨", "quantity": 1},
        ],
    },
    # ========== 新增：仙品法宝炼制图 ==========
    {
        "name": "鸿蒙紫莲剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "鸿蒙紫莲剑",
        "result_quantity": 1,
        "base_success_rate": 28,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "鸿蒙紫莲", "quantity": 1},
            {"material_name": "混沌祖气", "quantity": 1},
            {"material_name": "鲲鹏巨羽", "quantity": 1},
        ],
    },
    {
        "name": "凤凰真血冠炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "凤凰真血冠",
        "result_quantity": 1,
        "base_success_rate": 26,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "凤凰真血", "quantity": 1},
            {"material_name": "涅槃火羽", "quantity": 2},
            {"material_name": "麒麟神金", "quantity": 1},
        ],
    },
    {
        "name": "灭仙剑炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "灭仙剑",
        "result_quantity": 1,
        "base_success_rate": 22,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "混沌灵根", "quantity": 1},
            {"material_name": "天道雷种", "quantity": 1},
            {"material_name": "混沌祖气", "quantity": 1},
        ],
    },
    {
        "name": "星辰琴炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "星辰琴",
        "result_quantity": 1,
        "base_success_rate": 20,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "星辰之泪", "quantity": 2},
            {"material_name": "天玄真银", "quantity": 1},
            {"material_name": "鲲鹏巨羽", "quantity": 1},
        ],
    },
    # ========== 新增：先天至宝法宝炼制图 ==========
    {
        "name": "开天斧炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "开天斧",
        "result_quantity": 1,
        "base_success_rate": 15,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "开天神石", "quantity": 1},
            {"material_name": "盘古精血", "quantity": 1},
            {"material_name": "混沌羽毛", "quantity": 1},
        ],
    },
    {
        "name": "造化玉蝶镯炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "造化玉蝶镯",
        "result_quantity": 1,
        "base_success_rate": 12,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "造化玉蝶", "quantity": 1},
            {"material_name": "命运之种", "quantity": 1},
            {"material_name": "大道金莲", "quantity": 1},
        ],
    },
    {
        "name": "盘古战鼓炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "盘古战鼓",
        "result_quantity": 1,
        "base_success_rate": 8,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "盘古战鼓皮", "quantity": 1},
            {"material_name": "盘古精血", "quantity": 1},
            {"material_name": "本源雷种", "quantity": 1},
        ],
    },
    {
        "name": "女娲石炼制图",
        "recipe_kind": "artifact",
        "result_kind": "artifact",
        "result_name": "女娲石",
        "result_quantity": 1,
        "base_success_rate": 8,
        "broadcast_on_success": True,
        "ingredients": [
            {"material_name": "补天玉彩", "quantity": 1},
            {"material_name": "天道玉髓", "quantity": 1},
            {"material_name": "大道金莲", "quantity": 1},
        ],
    },
    # ========== 新增：凡品符箓炼制图 ==========
    {
        "name": "醒神符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "醒神符",
        "result_quantity": 2,
        "base_success_rate": 76,
        "broadcast_on_success": False,
        "description": "以黄纸符为基、朱砂点睛，符成时隐隐有清香醒神。贴于身上可驱散昏沉，令神识清明、反应敏捷，是修士日常修行的常用辅助符箓。",
        "ingredients": [
            {"material_name": "黄纸符", "quantity": 1},
            {"material_name": "朱砂", "quantity": 1},
        ],
    },
    {
        "name": "护身符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "护身符",
        "result_quantity": 2,
        "base_success_rate": 74,
        "broadcast_on_success": False,
        "description": "以多层黄纸符叠合朱砂绘制，符成时散发淡淡红光。引动后可令皮肤表面浮现一层柔光，抵挡部分物理与灵力攻击。",
        "ingredients": [
            {"material_name": "黄纸符", "quantity": 2},
            {"material_name": "朱砂", "quantity": 1},
        ],
    },
    # ========== 新增：下品符箓炼制图 ==========
    {
        "name": "寒冰符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "寒冰符",
        "result_quantity": 2,
        "base_success_rate": 68,
        "broadcast_on_success": False,
        "description": "以灵蚕丝配合霜凌草绘就，符成时寒气内敛。引动后寒芒飞溅，可冻结对手肢体并造成冰冻伤害，令其行动迟缓。",
        "ingredients": [
            {"material_name": "灵蚕丝", "quantity": 1},
            {"material_name": "霜凌草", "quantity": 1},
            {"material_name": "黑狗血", "quantity": 1},
        ],
    },
    {
        "name": "烈焰符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "烈焰符",
        "result_quantity": 2,
        "base_success_rate": 66,
        "broadcast_on_success": False,
        "description": "以灵蚕丝浸润烈阳花汁绘制，符成时火光隐隐。引动后烈焰腾空，可对敌人造成灼烧伤害，令其苦于火焰侵袭。",
        "ingredients": [
            {"material_name": "灵蚕丝", "quantity": 1},
            {"material_name": "烈阳花", "quantity": 1},
            {"material_name": "朱砂", "quantity": 1},
        ],
    },
    {
        "name": "清风符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "清风符",
        "result_quantity": 2,
        "base_success_rate": 70,
        "broadcast_on_success": False,
        "description": "以灵蚕丝缠绕风灵石绘就，符成时微风徐徐。引动后清风绕体，可提升身法轻盈度，令闪避与移动更加灵活自如。",
        "ingredients": [
            {"material_name": "灵蚕丝", "quantity": 1},
            {"material_name": "风灵石", "quantity": 1},
        ],
    },
    # ========== 新增：中品符箓炼制图 ==========
    {
        "name": "冰魄符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "冰魄符",
        "result_quantity": 2,
        "base_success_rate": 58,
        "broadcast_on_success": False,
        "description": "取妖狐尾毛配合冰魄珠绘就，符成时寒光凛冽如九幽冰窟。引动后冰魄之气铺天盖地，可将对手冻结于寒冰之中。",
        "ingredients": [
            {"material_name": "妖狐尾毛", "quantity": 1},
            {"material_name": "冰魄珠", "quantity": 1},
            {"material_name": "雷击桃木", "quantity": 1},
        ],
    },
    {
        "name": "火鸾符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "火鸾符",
        "result_quantity": 2,
        "base_success_rate": 56,
        "broadcast_on_success": False,
        "description": "以火鸾羽配合烈阳花汁绘就，符成时火焰缭绕如鸾鸟翔空。引动后火鸾展翅，灼热之息可将敌人焚为灰烬。",
        "ingredients": [
            {"material_name": "火鸾羽", "quantity": 1},
            {"material_name": "烈阳花", "quantity": 2},
            {"material_name": "鬼画符骨", "quantity": 1},
        ],
    },
    {
        "name": "金刚符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "金刚符",
        "result_quantity": 2,
        "base_success_rate": 54,
        "broadcast_on_success": False,
        "description": "取玄武岩配合金芒砂锤炼绘制，符成时金光万丈坚硬如铁。引动后金身加持，令修士防御力倍增，寻常攻击难伤分毫。",
        "ingredients": [
            {"material_name": "玄武岩", "quantity": 1},
            {"material_name": "金芒砂", "quantity": 1},
            {"material_name": "寒铁", "quantity": 1},
        ],
    },
    # ========== 新增：上品符箓炼制图 ==========
    {
        "name": "玄冰符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "玄冰符",
        "result_quantity": 2,
        "base_success_rate": 46,
        "broadcast_on_success": True,
        "description": "以玄冰精髓配合白虎胡须绘就，符成时万里冰封、寒气逼人。引动后天降大雪纷飞，可将战场上一切冻结成冰雕。",
        "ingredients": [
            {"material_name": "玄冰精髓", "quantity": 1},
            {"material_name": "冰魄珠", "quantity": 1},
            {"material_name": "白虎胡须", "quantity": 1},
        ],
    },
    {
        "name": "烈凤符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "烈凤符",
        "result_quantity": 2,
        "base_success_rate": 44,
        "broadcast_on_success": True,
        "description": "以烈凤心血配合朱雀神羽炼就，符成时火焰冲天似有凤凰涅槃。引动后烈凤翔空，焚尽一切敢于阻挡之物。",
        "ingredients": [
            {"material_name": "烈凤心血", "quantity": 1},
            {"material_name": "朱雀神羽", "quantity": 1},
            {"material_name": "真武水精", "quantity": 1},
        ],
    },
    {
        "name": "天师符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "天师符",
        "result_quantity": 2,
        "base_success_rate": 42,
        "broadcast_on_success": True,
        "description": "取天师袍角配合天雷符骨绘制，符成时天师威压笼罩四方。引动后天师法相显现，可镇邪驱魔、压制一切妖邪。",
        "ingredients": [
            {"material_name": "天师袍角", "quantity": 1},
            {"material_name": "天雷符骨", "quantity": 1},
            {"material_name": "青龙之鳞", "quantity": 1},
        ],
    },
    # ========== 新增：极品符箓炼制图 ==========
    {
        "name": "九幽寒莲符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "九幽寒莲符",
        "result_quantity": 2,
        "base_success_rate": 36,
        "broadcast_on_success": True,
        "description": "取九幽寒莲配合轮回冥晶炼就，符成时九幽寒气弥漫、莲花虚影浮现。引动后可冻结万物，连灵魂都要被冰封于九幽寒狱之中。",
        "ingredients": [
            {"material_name": "九幽寒莲", "quantity": 1},
            {"material_name": "玄冰精髓", "quantity": 1},
            {"material_name": "轮回冥晶", "quantity": 1},
        ],
    },
    {
        "name": "涅槃符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "涅槃符",
        "result_quantity": 2,
        "base_success_rate": 34,
        "broadcast_on_success": True,
        "description": "以凤凰真血配合涅槃火羽绘制，符成时火光冲天似有凤凰浴火重生。引动后可令修士在陨落之际浴火复活，重获新生。",
        "ingredients": [
            {"material_name": "涅槃火羽", "quantity": 1},
            {"material_name": "凤凰真血", "quantity": 1},
            {"material_name": "朱雀心核", "quantity": 1},
        ],
    },
    {
        "name": "建木符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "建木符",
        "result_quantity": 2,
        "base_success_rate": 32,
        "broadcast_on_success": True,
        "description": "以建木之种配合青龙帝藤绘就，符成时生机勃勃似神树参天。引动后可激发体内生机，白骨生肉、垂死复苏，寿元亦能缓缓增益。",
        "ingredients": [
            {"material_name": "建木之种", "quantity": 1},
            {"material_name": "青龙帝藤", "quantity": 1},
            {"material_name": "人参果精", "quantity": 1},
        ],
    },
    # ========== 新增：仙品符箓炼制图 ==========
    {
        "name": "鸿蒙符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "鸿蒙符",
        "result_quantity": 2,
        "base_success_rate": 26,
        "broadcast_on_success": True,
        "description": "以鸿蒙紫莲配合混沌祖气炼就，符成时紫气东来三万里。引动后鸿蒙之力笼罩战场，可将一切法则尽数扰乱，是为仙家至宝。",
        "ingredients": [
            {"material_name": "鸿蒙紫莲", "quantity": 1},
            {"material_name": "混沌祖气", "quantity": 1},
            {"material_name": "天外玄铁", "quantity": 1},
        ],
    },
    {
        "name": "天罚符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "天罚符",
        "result_quantity": 2,
        "base_success_rate": 24,
        "broadcast_on_success": True,
        "description": "以天罚雷种配合天道雷种炼就，符成时天雷滚滚似有天劫降临。引动后天道雷罚降世，斩杀一切逆天之辈。",
        "ingredients": [
            {"material_name": "天罚雷种", "quantity": 1},
            {"material_name": "天道雷种", "quantity": 1},
            {"material_name": "混沌雷种", "quantity": 1},
        ],
    },
    # ========== 新增：先天至宝符箓炼制图 ==========
    {
        "name": "开天符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "开天符",
        "result_quantity": 2,
        "base_success_rate": 15,
        "broadcast_on_success": True,
        "description": "以开天神石配合盘古精血绘制，符成时开天辟地之象隐现。引动后可重演混沌开天之威，一符既出天地分开，是为超越仙品的逆天禁符。",
        "ingredients": [
            {"material_name": "开天神石", "quantity": 1},
            {"material_name": "盘古精血", "quantity": 1},
            {"material_name": "造化玉蝶", "quantity": 1},
        ],
    },
    {
        "name": "轮回符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "轮回符",
        "result_quantity": 2,
        "base_success_rate": 12,
        "broadcast_on_success": True,
        "description": "以轮回祖符配合命运之种炼就，符成时轮回之力弥漫、因果之道显现。引动后可操控生死轮回，令敌人堕入无尽轮回之中。",
        "ingredients": [
            {"material_name": "轮回祖符", "quantity": 1},
            {"material_name": "本源雷种", "quantity": 1},
            {"material_name": "命运之种", "quantity": 1},
        ],
    },
    # ========== 补齐：秘境与奇遇引用缺失丹谱符谱 ==========
    {
        "name": "聚灵丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "聚灵丹",
        "result_quantity": 1,
        "base_success_rate": 78,
        "broadcast_on_success": False,
        "description": "最适合入门修士的聚灵丹方，可将零散灵气温和收束为可吸纳药力。",
        "ingredients": [
            {"material_name": "灵露滴", "quantity": 1},
            {"material_name": "归元草", "quantity": 2},
            {"material_name": "灵木芯", "quantity": 1},
        ],
    },
    {
        "name": "疗伤丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "疗伤丹",
        "result_quantity": 1,
        "base_success_rate": 72,
        "broadcast_on_success": False,
        "description": "续骨藤配合回气药引所成的常用疗伤丹方，最适合历练后的应急恢复。",
        "ingredients": [
            {"material_name": "续骨藤", "quantity": 1},
            {"material_name": "凝露花", "quantity": 1},
            {"material_name": "归元草", "quantity": 1},
        ],
    },
    {
        "name": "清心丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "清心丹",
        "result_quantity": 1,
        "base_success_rate": 70,
        "broadcast_on_success": False,
        "description": "以清心兰与净水莲心炼成，丹成后清气自生，可化解丹毒与杂念侵扰。",
        "ingredients": [
            {"material_name": "清心兰", "quantity": 1},
            {"material_name": "净水莲心", "quantity": 1},
            {"material_name": "残月水", "quantity": 1},
        ],
    },
    {
        "name": "强骨丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "强骨丹",
        "result_quantity": 1,
        "base_success_rate": 64,
        "broadcast_on_success": False,
        "description": "将骨血药力沉入骨髓的淬体丹方，适合早期稳步提升根骨底子。",
        "ingredients": [
            {"material_name": "续骨藤", "quantity": 1},
            {"material_name": "地龙髓", "quantity": 1},
            {"material_name": "灵木芯", "quantity": 1},
        ],
    },
    {
        "name": "化毒丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "化毒丹",
        "result_quantity": 1,
        "base_success_rate": 66,
        "broadcast_on_success": False,
        "description": "专用于化去体内丹毒与杂毒的稳妥丹方，药性清灵不伤根基。",
        "ingredients": [
            {"material_name": "化毒草", "quantity": 2},
            {"material_name": "残月水", "quantity": 1},
            {"material_name": "净水莲心", "quantity": 1},
        ],
    },
    {
        "name": "冰魄寒光丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "冰魄寒光丹",
        "result_quantity": 1,
        "base_success_rate": 50,
        "broadcast_on_success": True,
        "description": "冰魄珠与玄冰精髓同炼，丹成时寒光横空，最善淬出冷冽锋芒。",
        "ingredients": [
            {"material_name": "冰魄珠", "quantity": 1},
            {"material_name": "九转雪莲", "quantity": 1},
            {"material_name": "玄冰精髓", "quantity": 1},
        ],
    },
    {
        "name": "火鸾炽心丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "火鸾炽心丹",
        "result_quantity": 1,
        "base_success_rate": 48,
        "broadcast_on_success": True,
        "description": "火鸾羽、凤尾草与烈凤心血共熬，丹成若心火腾跃，最宜走攻伐一路。",
        "ingredients": [
            {"material_name": "火鸾羽", "quantity": 1},
            {"material_name": "凤尾草", "quantity": 1},
            {"material_name": "烈凤心血", "quantity": 1},
        ],
    },
    {
        "name": "镇魂符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "镇魂符",
        "result_quantity": 2,
        "base_success_rate": 44,
        "broadcast_on_success": False,
        "description": "以幽冥魂晶和鬼画符骨绘符，成符后幽光沉稳，专能镇压神魂波动。",
        "ingredients": [
            {"material_name": "幽冥魂晶", "quantity": 1},
            {"material_name": "鬼画符骨", "quantity": 1},
            {"material_name": "净水莲心", "quantity": 1},
        ],
    },
    {
        "name": "玄冰破天丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "玄冰破天丹",
        "result_quantity": 1,
        "base_success_rate": 36,
        "broadcast_on_success": True,
        "description": "玄冰与九幽寒意同炉，丹成后寒势直指天阙，是极重杀伐的高阶冰丹。",
        "ingredients": [
            {"material_name": "玄冰精髓", "quantity": 1},
            {"material_name": "九幽寒莲", "quantity": 1},
            {"material_name": "天玄真银", "quantity": 1},
        ],
    },
    {
        "name": "凤涅槃丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "凤涅槃丹",
        "result_quantity": 1,
        "base_success_rate": 34,
        "broadcast_on_success": True,
        "description": "借涅槃火羽引动凤血生机，丹成后火意不烈不散，专主浴火续命。",
        "ingredients": [
            {"material_name": "涅槃火羽", "quantity": 1},
            {"material_name": "烈凤心血", "quantity": 1},
            {"material_name": "朱雀心核", "quantity": 1},
        ],
    },
    {
        "name": "白虎破军符符谱",
        "recipe_kind": "talisman",
        "result_kind": "talisman",
        "result_name": "白虎破军符",
        "result_quantity": 2,
        "base_success_rate": 36,
        "broadcast_on_success": True,
        "description": "白虎杀伐意凝于符骨，一旦绘成便有破军之势，最善撕裂敌阵正锋。",
        "ingredients": [
            {"material_name": "白虎神金", "quantity": 1},
            {"material_name": "白虎胡须", "quantity": 1},
            {"material_name": "金芒砂", "quantity": 1},
        ],
    },
    {
        "name": "九幽轮回丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "九幽轮回丹",
        "result_quantity": 1,
        "base_success_rate": 32,
        "broadcast_on_success": True,
        "description": "九幽寒意与轮回真痕交织，成丹后可温养识海并稳固神魂本源。",
        "ingredients": [
            {"material_name": "九幽寒莲", "quantity": 1},
            {"material_name": "轮回冥晶", "quantity": 1},
            {"material_name": "幽冥魂晶", "quantity": 1},
        ],
    },
    {
        "name": "万木逢春丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "万木逢春丹",
        "result_quantity": 1,
        "base_success_rate": 30,
        "broadcast_on_success": True,
        "description": "建木灵种配合乙木生机炼就，丹成时草木回春之象自炉中升起。",
        "ingredients": [
            {"material_name": "建木之种", "quantity": 1},
            {"material_name": "乙木精华", "quantity": 1},
            {"material_name": "人参果精", "quantity": 1},
        ],
    },
    {
        "name": "天罚破境丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "天罚破境丹",
        "result_quantity": 1,
        "base_success_rate": 26,
        "broadcast_on_success": True,
        "description": "借天罚雷威撕开境界瓶颈的雷系丹方，丹成时常有雷声滚动炉外。",
        "ingredients": [
            {"material_name": "天罚雷种", "quantity": 1},
            {"material_name": "天雷符骨", "quantity": 1},
            {"material_name": "天道雷种", "quantity": 1},
        ],
    },
    {
        "name": "鸿蒙混沌丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "鸿蒙混沌丹",
        "result_quantity": 1,
        "base_success_rate": 20,
        "broadcast_on_success": True,
        "description": "鸿蒙紫意与混沌本源一同归炉，成丹后最利于拓宽悟境、参修大道。",
        "ingredients": [
            {"material_name": "鸿蒙紫莲", "quantity": 1},
            {"material_name": "混沌灵根", "quantity": 1},
            {"material_name": "混沌祖气", "quantity": 1},
        ],
    },
    {
        "name": "轮回证道丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "轮回证道丹",
        "result_quantity": 1,
        "base_success_rate": 22,
        "broadcast_on_success": True,
        "description": "轮回祖符和天道玉髓共熬，丹成者往往更易从生死轮转中窥见证道契机。",
        "ingredients": [
            {"material_name": "轮回祖符", "quantity": 1},
            {"material_name": "轮回冥晶", "quantity": 1},
            {"material_name": "天道玉髓", "quantity": 1},
        ],
    },
    {
        "name": "天道大同丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "天道大同丹",
        "result_quantity": 1,
        "base_success_rate": 16,
        "broadcast_on_success": True,
        "description": "融通五行本源与天道法则的先天丹方，成丹后有大道和鸣之异象。",
        "ingredients": [
            {"material_name": "天道精华", "quantity": 1},
            {"material_name": "天道玉髓", "quantity": 1},
            {"material_name": "五行本源", "quantity": 1},
        ],
    },
    {
        "name": "开天辟地丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "开天辟地丹",
        "result_quantity": 1,
        "base_success_rate": 14,
        "broadcast_on_success": True,
        "description": "盘古精血与开天神石同炉，丹成时隐有混沌开辟、天地初分之象。",
        "ingredients": [
            {"material_name": "开天神石", "quantity": 1},
            {"material_name": "盘古精血", "quantity": 1},
            {"material_name": "创世神铁", "quantity": 1},
        ],
    },
    {
        "name": "天道永恒丹丹谱",
        "recipe_kind": "pill",
        "result_kind": "pill",
        "result_name": "天道永恒丹",
        "result_quantity": 1,
        "base_success_rate": 12,
        "broadcast_on_success": True,
        "description": "天道玉髓、时空源晶与命运之种并炼，药成后自有永恒不坏之意流转。",
        "ingredients": [
            {"material_name": "天道玉髓", "quantity": 1},
            {"material_name": "时空源晶", "quantity": 1},
            {"material_name": "命运之种", "quantity": 1},
        ],
    },
]


