from __future__ import annotations

EXTRA_SCENES = [
    {
        "name": "流霞古渡",
        "description": "残桥横跨于云霞之间，朝霞与暮色交织成绚烂锦绣，灵雾升腾时隐时现诸多天材地宝，唯有缘者方能窥见。",
        "max_minutes": 46,
        "min_realm_stage": "筑基",
        "min_realm_layer": 3,
        "min_combat_power": 2200,
        "event_pool": [
            {
                "name": "霞桥残匣",
                "description": "霞光穿透断桥裂隙，照亮一只尘封已久的古旧匣子，匣中灵光隐隐，似藏先人遗泽。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "流霞驻颜丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 36,
            },
            {
                "name": "霞羽掠空",
                "description": "流霞深处一道华彩掠影划过天际，你凝神细观，竟从中学得一丝风雷迅捷之意。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "talisman",
                "bonus_reward_ref_id_name": "惊鸿符",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 22,
            },
            {
                "name": "渡口逆浪",
                "description": "古渡深处骤然掀起逆流，霞光与浪花交织成漩涡，护体灵光被冲击得摇摇欲坠。",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 18,
                "stone_bonus_max": 34,
                "stone_loss_min": 6,
                "stone_loss_max": 16,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "霓裳花露", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 8, "event_text": "霞雾在你周身缓缓流转，你伸手探入灵雾深处，凝出一瓶散发着七色虹光的霓裳花露，入手温润如玉。"},
            {"reward_kind": "material", "reward_ref_id_name": "定魄灵砂", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 9, "event_text": "断桥石缝间泛起莹莹微光，你拂去尘土，竟积着一层细腻如银的定魄灵砂。"},
            {"reward_kind": "material", "reward_ref_id_name": "星辉砂", "quantity_min": 1, "quantity_max": 2, "weight": 3, "stone_reward": 10, "event_text": "暮色四合之际，霞光将桥面染成绯金，你俯身细看，桥栏缝隙中正析出点点星辉砂。"},
        ],
    },
    {
        "name": "天书阁遗址",
        "description": "残破阁楼仍被天书气机环绕周身，泛黄书页在虚空中无风自翻，命数与神识之力在此地凝而不散，唯有缘者能取其精要。",
        "max_minutes": 60,
        "min_realm_stage": "元婴",
        "min_realm_layer": 1,
        "min_combat_power": 4200,
        "event_pool": [
            {
                "name": "命盘残页",
                "description": "残破命盘在梁柱缝隙间微微震颤，上古命理之术似在低语，诉说着某段被岁月掩埋的天机。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "承运问天丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 28,
            },
            {
                "name": "问心遗器",
                "description": "蒙尘案几之上，一支古簪静静横卧，簪身犹带温润灵光，似在等待故人归来。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "artifact",
                "bonus_reward_ref_id_name": "流霞问心簪",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 12,
            },
            {
                "name": "天书逆卷",
                "description": "泛黄书页骤然腾起，倒卷成狂飙向你的神魂席卷而来，阁中符阵亦随之激活，灵光如刃！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 28,
                "stone_bonus_max": 54,
                "stone_loss_min": 12,
                "stone_loss_max": 24,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "承运木心", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 12, "event_text": "阁中残柱在灵光拂过时骤然开裂，露出截取天地之运的承运木心，入手温热而沉重。"},
            {"reward_kind": "material", "reward_ref_id_name": "星命玉枝", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 14, "event_text": "倒塌书架深处，一段星命玉枝正散发着幽幽蓝光，仿佛在指引你拨开迷雾。"},
            {"reward_kind": "material", "reward_ref_id_name": "天眷符骨", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 18, "event_text": "阁楼阵眼处微光闪烁，你拂去尘土，一块刻满神秘纹路的天眷符骨静静躺在其中。"},
        ],
    },
    {
        "name": "镜湖遗台",
        "description": "破碎镜台静卧于湖心，湖水清澈却照不见真实倒影，镜中世界与现世交错缠绕，唯有道心坚定者方能分辨虚实，不被幻象所迷。",
        "max_minutes": 58,
        "min_realm_stage": "结丹",
        "min_realm_layer": 4,
        "min_combat_power": 3200,
        "event_pool": [
            {
                "name": "镜台旧图",
                "description": "镜面折射出不属于此刻的光景，一页完整炼图在反光中若隐若现，似在提示你翻转镜台。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "照骨问心镜炼制图",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 32,
            },
            {
                "name": "照影残符",
                "description": "镜面崩裂的刹那，一缕符意自碎片中飞出，在眼前幻化成诡异图案，你以神识将其截下。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "talisman",
                "bonus_reward_ref_id_name": "照影符",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 18,
            },
            {
                "name": "镜潮反噬",
                "description": "湖心骤然掀起惊涛，破碎镜面在浪中重组，四面八方的倒影化作利刃向你激射而来！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 24,
                "stone_bonus_max": 44,
                "stone_loss_min": 10,
                "stone_loss_max": 22,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "镜尘玄晶", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 12, "event_text": "镜湖碎光在你足下沉淀，化作几枚晶莹剔透的镜尘玄晶，折射出迷离的七色光芒。"},
            {"reward_kind": "material", "reward_ref_id_name": "星命玉枝", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 12, "event_text": "遗台裂隙间泄出幽蓝星芒，你探手入内，抽出一截温润如玉的星命玉枝。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "镜心澄神丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 18, "event_text": "湖底淤泥中微光浮动，你拨开泥沙，意外发现一页保存完好的镜心澄神丹丹谱。"},
        ],
    },
    {
        "name": "逆流龙门涧",
        "description": "断崖古涧之中灵潮倒灌、飞瀑逆卷，传说真龙曾在此借势越门而上，残留的龙门真水与归元秘法至今仍在潮心翻涌不息。",
        "max_minutes": 64,
        "min_realm_stage": "化神",
        "min_realm_layer": 2,
        "min_combat_power": 5400,
        "event_pool": [
            {
                "name": "龙门残谱",
                "description": "逆流瀑布忽然裂开一道水幕，幕后的石壁上残留着一页清气流转的丹谱，像是专为解厄而留。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "太和解厄丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 24,
            },
            {
                "name": "归元旧卷",
                "description": "潭心旋流卷起一只封存多年的玉匣，匣中旧卷仍带着归元镇魂的气机，似乎正等待后来者续写丹道。",
                "event_type": "recipe",
                "weight": 2,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "离魄归元丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 22,
            },
            {
                "name": "逆潮拍岸",
                "description": "古涧深处忽起万丈逆潮，飞瀑如龙尾横扫崖壁，护体灵光在轰鸣声中被拍得摇摇欲散。",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 34,
                "stone_bonus_max": 62,
                "stone_loss_min": 18,
                "stone_loss_max": 32,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "龙门真水", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 22, "event_text": "逆流瀑心忽然裂开一道灵缝，一滴晶莹剔透的龙门真水自浪心升起，你以玉瓶将其封存。"},
            {"reward_kind": "material", "reward_ref_id_name": "无垢净沙", "quantity_min": 1, "quantity_max": 2, "weight": 3, "stone_reward": 18, "event_text": "飞瀑反复冲刷崖底石槽，淘出一捧洁白无瑕的净沙，落入掌心时仍带着细微潮声。"},
            {"reward_kind": "material", "reward_ref_id_name": "玄龟骨晶", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 20, "event_text": "深潭底部埋着一截玄龟遗骨，潮水磨尽泥沙后露出温润如玉的玄龟骨晶。"},
        ],
    },
    {
        "name": "赤陨火域",
        "description": "天火陨坑烈焰经年不熄，熔岩如血脉流淌于地底深处，雷火交织之地将一切杂质尽数焚化，唯精纯灵材可在此地幸存。",
        "max_minutes": 62,
        "min_realm_stage": "化神",
        "min_realm_layer": 1,
        "min_combat_power": 5200,
        "event_pool": [
            {
                "name": "离火弓胎",
                "description": "熔坑深处火光冲天，一截通体赤红的古弓弓胎在烈焰中若隐若现，似在等待有缘者将其唤醒。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "赤霄逐日弓炼制图",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 26,
            },
            {
                "name": "封脉符痕",
                "description": "万年熔岩在石壁上凝结成神秘符痕，古老封禁之力在火光明灭间似要觉醒，你凝神将其中精要默记于心。",
                "event_type": "recipe",
                "weight": 2,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "镇魄封脉符符谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 22,
            },
            {
                "name": "焰雷并坠",
                "description": "火云与劫雷在苍穹激烈碰撞，漫天火雨夹带着紫色雷丝倾泻而下，熔岩巨浪随之咆哮翻涌！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 36,
                "stone_bonus_max": 68,
                "stone_loss_min": 16,
                "stone_loss_max": 30,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "曜金雷髓", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 16, "event_text": "雷火交锋之处迸出璀璨火花，一团蕴含金雷之精的曜金雷髓缓缓凝结，你以灵力将其强行拘入掌中。"},
            {"reward_kind": "material", "reward_ref_id_name": "烬天火纹石", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 15, "event_text": "熔岩流淌过古老岩层，将漫天火气凝入岩芯，你从凝固的熔流中敲出一块烬天火纹石，余温犹烫手心。"},
            {"reward_kind": "material", "reward_ref_id_name": "离魄藤种", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 18, "event_text": "焦黑岩缝深处透出点点绿意，你拨开炭化岩层，一枚散发着顽强生机的离魄藤种静静躺在其中。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "曜金焚脉丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 20, "event_text": "熔坑灰烬之下微光浮动，你拂去滚烫尘土，一页泛黄丹谱正静静等待知音。"},
        ],
    },
    # ========== 新增：凡品秘境 ==========
    {
        "name": "灵雾山谷",
        "description": "晨雾如轻纱缠绕于青山翠谷之间，露珠在草叶上折射出晶莹光芒，灵气虽淡却温养万物，是初入仙途者最佳的历练之地。",
        "max_minutes": 30,
        "min_realm_stage": "筑基",
        "min_realm_layer": 1,
        "min_combat_power": 800,
        "event_pool": [
            {
                "name": "露草惊喜",
                "description": "晨曦初照，草叶上的露珠折射出璀璨光芒，你俯身细看，竟是蕴含灵气的凝露挂于碧草之间。",
                "event_type": "oddity",
                "weight": 3,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "灵露滴",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 45,
            },
            {
                "name": "萤火指引",
                "description": "暮色四合之际，几点幽蓝萤火自灵草丛中升起，在前方若隐若现地飞舞，似在指引有缘人。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "引路萤火",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 40,
            },
            {
                "name": "薄雾迷途",
                "description": "山谷深处薄雾骤然大盛，伸手不见五指，你一时辨不清方向，心中不禁有些慌乱。",
                "event_type": "danger",
                "weight": 2,
                "stone_bonus_min": 5,
                "stone_bonus_max": 12,
                "stone_loss_min": 3,
                "stone_loss_max": 8,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "灵露滴", "quantity_min": 1, "quantity_max": 3, "weight": 8, "stone_reward": 5, "event_text": "晨雾在第一缕阳光照耀下化作晶莹露珠，你小心翼翼地将这些蕴含灵气的灵露滴收入玉瓶。"},
            {"reward_kind": "material", "reward_ref_id_name": "枯叶草", "quantity_min": 1, "quantity_max": 3, "weight": 7, "stone_reward": 4, "event_text": "山谷边缘湿润之地丛生着几株枯叶草，虽看似枯败，内里却蕴含着丝丝灵气，你顺手将其采撷。"},
            {"reward_kind": "material", "reward_ref_id_name": "碎石粉", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 3, "event_text": "山壁上的碎石在溪水冲刷下变得圆润，你拾起几块以灵力将其研磨成细腻粉末。"},
            {"reward_kind": "material", "reward_ref_id_name": "引路萤火", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 4, "event_text": "入夜后灵山中萤火点点，你以灵力轻轻包裹，将这几点引路萤火收入囊中。"},
            {"reward_kind": "material", "reward_ref_id_name": "残月水", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 5, "event_text": "月华如水倾泻而下，草叶上凝结的露珠携着月之精粹，你采集到这一滴珍贵的残月水。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "聚灵丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 8, "event_text": "古旧石台在灵光一闪下微微震动，你拂去尘土，发现台下竟压着一页先人遗留的丹谱。"},
        ],
    },
    {
        "name": "翠竹小径",
        "description": "万竿翠竹夹道成荫，清风徐来时竹叶沙沙作响，洒落满地斑驳光影，竹节间偶有灵液凝结，是寻求宁静机缘者的上佳之所。",
        "max_minutes": 28,
        "min_realm_stage": "筑基",
        "min_realm_layer": 2,
        "min_combat_power": 1200,
        "event_pool": [
            {
                "name": "竹下古卷",
                "description": "一阵清风卷起落叶，露出竹丛下压着的一卷泛黄古谱，隐约可见几味药材图样。",
                "event_type": "recipe",
                "weight": 3,
                "bonus_reward_kind": "recipe",
                "bonus_reward_ref_id_name": "疗伤丹丹谱",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 38,
            },
            {
                "name": "翠影摇光",
                "description": "竹影摇曳间，一抹碧色灵光在草木间闪烁，你凝神细观，发现竟是一株散发微光的灵草。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "枯叶草",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 42,
            },
            {
                "name": "竹风突袭",
                "description": "忽然一阵妖风自谷口呼啸而至，竹叶如雨般纷飞而下，刮得你面颊生疼。",
                "event_type": "danger",
                "weight": 2,
                "stone_bonus_min": 6,
                "stone_bonus_max": 14,
                "stone_loss_min": 4,
                "stone_loss_max": 10,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "枯叶草", "quantity_min": 1, "quantity_max": 3, "weight": 7, "stone_reward": 5, "event_text": "竹林深处湿润阴凉，你采集到几株叶片泛黄的枯叶草，入手却觉温润，蕴含灵气。"},
            {"reward_kind": "material", "reward_ref_id_name": "灵露滴", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 4, "event_text": "竹叶尖凝着点点露珠，你轻俯身形，将这清晨的第一滴灵露收入玉瓶。"},
            {"reward_kind": "material", "reward_ref_id_name": "残月水", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 5, "event_text": "月色穿透竹叶洒落一地碎银，你采集到叶心凝结的月华精粹，一滴残月水入手微凉。"},
            {"reward_kind": "material", "reward_ref_id_name": "碎石粉", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 3, "event_text": "你敲下几块竹节间堆积的碎石，以灵力将其细细研磨成粉末。"},
        ],
    },
    # ========== 新增：下品秘境 ==========
    {
        "name": "寒霜洞府",
        "description": "万年玄冰封冻而成的幽深洞窟，寒气凛冽如刀，洞壁之上霜华如花般绽放，唯有道心坚定者方能在其中寻得属于你的寒系灵材。",
        "max_minutes": 38,
        "min_realm_stage": "筑基",
        "min_realm_layer": 5,
        "min_combat_power": 1800,
        "event_pool": [
            {
                "name": "霜华凝结",
                "description": "洞壁深处透出幽蓝寒光，万年霜华凝结成晶莹花簇，在你的灵光照耀下折射出梦幻色彩。",
                "event_type": "oddity",
                "weight": 3,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "霜凌草",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 40,
            },
            {
                "name": "古修残丹",
                "description": "角落石台布满尘埃，其上静卧着几枚灵气将散的丹药，虽已走过漫长岁月，却仍泛着淡淡光泽。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "化毒草",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 30,
            },
            {
                "name": "寒气侵体",
                "description": "洞窟深处寒气如潮水般涌来，你护体灵光被冻得咔咔作响，经脉中传来阵阵刺痛。",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 12,
                "stone_bonus_max": 22,
                "stone_loss_min": 6,
                "stone_loss_max": 14,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "霜凌草", "quantity_min": 1, "quantity_max": 3, "weight": 7, "stone_reward": 8, "event_text": "寒泉之畔傲然挺立着几株霜凌草，叶片之上结着薄薄寒霜，你小心翼翼将其连根拔起。"},
            {"reward_kind": "material", "reward_ref_id_name": "烈阳花", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 9, "event_text": "洞窟中有一处温热泉眼，一朵烈阳花正傲然绽放于寒气之中，花瓣如火灼灼耀眼。"},
            {"reward_kind": "material", "reward_ref_id_name": "风灵石", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 10, "event_text": "穿堂风穴之中，灵气与风声交织凝结，你伸手探入，握住几枚温润的风灵石。"},
            {"reward_kind": "material", "reward_ref_id_name": "浊煞泥", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 8, "event_text": "阴湿之地散发着浑浊气息，你挖开稀泥，捧出一团蕴含阴煞之气的浊煞泥。"},
            {"reward_kind": "material", "reward_ref_id_name": "裂木甲", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 9, "event_text": "雷劫古木早已中空，你劈开焦黑树皮，自其中剥离出几块纹理清晰的裂木甲。"},
            {"reward_kind": "material", "reward_ref_id_name": "幽冥粉", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 8, "event_text": "幽暗角落散发着若有若无的荧光，你俯身采集到这难得一见的幽冥粉。"},
            {"reward_kind": "material", "reward_ref_id_name": "清心兰", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 10, "event_text": "万寒之中独开一株清心兰，清香淡雅沁人心脾，你弯腰将其轻轻折下。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "清心丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 12, "event_text": "古修坐化之地苔痕斑驳，你拂去尘土后发现石壁之上竟刻着一页丹谱。"},
        ],
    },
    {
        "name": "烈阳崖",
        "description": "赤红崖壁如火焰般冲天而立，烈日映照下热浪灼人，阳气之盛足以焦金化石，却在这炽烈之中孕育着稀世火系灵材与机缘。",
        "max_minutes": 42,
        "min_realm_stage": "筑基",
        "min_realm_layer": 6,
        "min_combat_power": 2000,
        "event_pool": [
            {
                "name": "阳燧取火",
                "description": "正午时分日光直射崖顶，岩缝间聚起一簇耀眼火苗，你窥见其中蕴含的纯阳真火之意。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "烈阳花",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 36,
            },
            {
                "name": "火牛遗角",
                "description": "崖壁之上挂着数支断裂牛角，虽已失去生机，却仍散发着炽热气息与火属灵韵。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "火牛角",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 28,
            },
            {
                "name": "烈日灼心",
                "description": "正午骄阳似火，热浪夹带着硫磺气息扑面而来，你灵力运转都变得滞涩艰涩。",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 14,
                "stone_bonus_max": 26,
                "stone_loss_min": 8,
                "stone_loss_max": 16,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "烈阳花", "quantity_min": 1, "quantity_max": 3, "weight": 7, "stone_reward": 10, "event_text": "崖壁裂隙深处绽开着丛丛烈阳花，花瓣赤红如血，你攀崖将其一一采下。"},
            {"reward_kind": "material", "reward_ref_id_name": "续骨藤", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 11, "event_text": "你攀于崖壁之上，无意间发现岩缝中缠绕着几根续骨藤，正散发着淡淡灵光。"},
            {"reward_kind": "material", "reward_ref_id_name": "精钢", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 9, "event_text": "崖底矿脉之中，你以灵力提炼出数块精钢，入手沉重而温热。"},
            {"reward_kind": "material", "reward_ref_id_name": "千年阴沉木", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 12, "event_text": "崖底深处挖掘出一截埋藏千年的阴沉木，入手冰凉却透着幽光。"},
            {"reward_kind": "material", "reward_ref_id_name": "银丝草", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 8, "event_text": "温热岩层缝隙间从生着几株银丝草，随风摇曳间泛着银光。"},
            {"reward_kind": "material", "reward_ref_id_name": "灵蚕丝", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 10, "event_text": "高温洞窟之中，你发现几缕灵蚕丝结于岩壁之间，轻盈却韧而不断。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "强骨丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 14, "event_text": "崖壁古穴之中微光闪烁，你拂去尘土，一页先人丹谱静静躺在岩穴深处。"},
        ],
    },
    {
        "name": "幽暗沼泽",
        "description": "阴气淤积而成的茫茫湿地，毒瘴如薄纱笼罩其上，腐败气息与阴湿水汽交织，却在这看似死寂之中生长着诸多罕见的阴系灵材。",
        "max_minutes": 40,
        "min_realm_stage": "结丹",
        "min_realm_layer": 1,
        "min_combat_power": 2500,
        "event_pool": [
            {
                "name": "瘴中灵芝",
                "description": "毒瘴最深处，一株散发幽光的灵芝在腐木之上缓缓绽放，其间蕴含着奇异生机。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "幽冥粉",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 32,
            },
            {
                "name": "灵狐遗毛",
                "description": "泥泞之中散落着几根银白毛发，在幽暗中泛着微微灵光，似乎是灵狐途经所留。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "妖狐尾毛",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 25,
            },
            {
                "name": "瘴气爆发",
                "description": "脚下淤泥骤然翻滚发烫，毒瘴如柱般冲天而起，腐败气息几乎将你熏晕！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 16,
                "stone_bonus_max": 30,
                "stone_loss_min": 10,
                "stone_loss_max": 20,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "幽冥粉", "quantity_min": 1, "quantity_max": 3, "weight": 6, "stone_reward": 12, "event_text": "毒瘴核心之处反而清明，你采集到这纯净的幽冥粉，入手如握星河。"},
            {"reward_kind": "material", "reward_ref_id_name": "浊煞泥", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 10, "event_text": "沼泽最深处淤泥沉积，你连根挖起这团浊煞泥，散发着古老阴气。"},
            {"reward_kind": "material", "reward_ref_id_name": "化毒草", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 11, "event_text": "解毒植物从生于清浊交界之处，你采下几株化毒草，叶片翠绿欲滴。"},
            {"reward_kind": "material", "reward_ref_id_name": "清心兰", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 12, "event_text": "瘴气边缘孤零零地绽放着一株清心兰，清香与毒瘴形成鲜明对比。"},
            {"reward_kind": "material", "reward_ref_id_name": "妖狐尾毛", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 15, "event_text": "古狐窝旁散落着几根妖狐尾毛，银白如玉，你小心翼翼地将它拾起。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "化毒丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 14, "event_text": "古修遗址残垣断壁之下，你翻开石板，发现一页被油布包裹的丹谱。"},
        ],
    },
    # ========== 新增：中品秘境 ==========
    {
        "name": "玄冰窟",
        "description": "万年寒冰层层覆盖的幽深冰窟，内蕴极寒之气足以冻裂金丹修士护体灵光，唯有修炼过冰系功法或服食过火属丹药者方能勉强支撑，是获取冰系至宝的绝佳之地。",
        "max_minutes": 48,
        "min_realm_stage": "结丹",
        "min_realm_layer": 4,
        "min_combat_power": 3000,
        "event_pool": [
            {
                "name": "冰魄凝结",
                "description": "冰层深处一抹幽蓝光芒若隐若现，散发彻骨寒意的冰魄珠似在向你召唤。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "冰魄珠",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 30,
            },
            {
                "name": "雪莲绽放",
                "description": "冰窟最深处，一朵晶莹剔透的九转雪莲在永夜中静静绽放，花瓣如冰晶凝成。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "九转雪莲",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 18,
            },
            {
                "name": "寒潮突袭",
                "description": "冰层在寂静中骤然炸裂，刺骨寒潮如刀锋般席卷而来，你护体灵光瞬间摇摇欲坠！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 22,
                "stone_bonus_max": 40,
                "stone_loss_min": 12,
                "stone_loss_max": 24,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "冰魄珠", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 15, "event_text": "冰窟最深处的冰壁之中，一枚散发幽蓝寒光的冰魄珠正在缓缓凝结，你以灵力将其小心翼翼地凿下。"},
            {"reward_kind": "material", "reward_ref_id_name": "寒铁", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 14, "event_text": "永冻岩层之中，你劈开层层寒冰，一块散发冷冽光芒的寒铁静静躺在其中。"},
            {"reward_kind": "material", "reward_ref_id_name": "九转雪莲", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 20, "event_text": "在万年冰层最深处，你发现了这朵传说中的九转雪莲，花瓣晶莹剔透，寒气逼人却芬香沁脾。"},
            {"reward_kind": "material", "reward_ref_id_name": "玄武岩", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 16, "event_text": "你劈开冰底岩层，层层叠叠的玄武岩赫然在目，入手沉重如山岳。"},
            {"reward_kind": "material", "reward_ref_id_name": "净水莲心", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 18, "event_text": "冰缝深处滴下一滴清冽寒露，这便是传说中的净水莲心，入手如握寒月。"},
            {"reward_kind": "material", "reward_ref_id_name": "龙涎香", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 22, "event_text": "在万年冰层之中，你意外发现一块散发异香的龙涎香，沁人心脾。"},
            {"reward_kind": "material", "reward_ref_id_name": "地龙髓", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 24, "event_text": "冰窟底部的冻裂地脉忽然渗出一缕金黄髓光，你顺着裂缝剥离出一团温热厚重的地龙髓。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "冰魄寒光丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 20, "event_text": "古修坐化之处，周围的冰层尽数融化，唯余一页丹谱在寒冰之中微微发光。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "龙髓丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 24, "event_text": "冰层深处封着一只玉匣，你破开寒封后发现其中静静躺着一页完整的龙髓丹丹谱。"},
        ],
    },
    {
        "name": "火鸾巢穴",
        "description": "火鸾妖禽的永恒巢穴，余烬炽烈，热浪滚滚，鸾羽与火系灵材散落于熔岩之间，唯有修有火属功法者方能在此自如行动，获得火中机缘。",
        "max_minutes": 50,
        "min_realm_stage": "结丹",
        "min_realm_layer": 6,
        "min_combat_power": 3400,
        "event_pool": [
            {
                "name": "火鸾残羽",
                "description": "巢穴边缘散落着数根火红羽毛，虽已脱落却仍散发着灼灼热意与火鸾余威。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "火鸾羽",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 28,
            },
            {
                "name": "凤尾草丛",
                "description": "火山口边缘岩浆流淌之处，一片赤红草丛如凤尾般铺散开来，散发着涅槃真火的余韵。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "凤尾草",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 24,
            },
            {
                "name": "地火喷发",
                "description": "巢穴深处隆隆作响，熔岩开始剧烈翻涌，热浪夹带着火星扑面而来！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 26,
                "stone_bonus_max": 48,
                "stone_loss_min": 14,
                "stone_loss_max": 28,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "火鸾羽", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 18, "event_text": "你俯身拾起散落在巢穴边缘的火鸾羽，入手滚烫却感觉灵力流转其间。"},
            {"reward_kind": "material", "reward_ref_id_name": "凤尾草", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 16, "event_text": "你采集到火山口旁的凤尾草，赤红的叶片如火焰跳动，散发着温暖而强大的气息。"},
            {"reward_kind": "material", "reward_ref_id_name": "火牛角", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 15, "event_text": "熔岩地带冷却之处，你发现几支遗留的火牛角，仍在散发着炽热气息。"},
            {"reward_kind": "material", "reward_ref_id_name": "烈阳花", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 14, "event_text": "在火山地热最旺盛之处，你采摘到几朵烈阳花，花瓣绽放如火。"},
            {"reward_kind": "material", "reward_ref_id_name": "木灵精", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 18, "event_text": "在岩浆与灰烬交界处，你扒出一团蕴含生机的木灵精，散发着柔和绿光。"},
            {"reward_kind": "material", "reward_ref_id_name": "金芒砂", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 20, "event_text": "你深入矿脉之中，以灵力淘得几粒璀璨的金芒砂，入手温热。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "火鸾炽心丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 22, "event_text": "巢穴最深处，火鸾遗留的玉简在灰烬中微微发光，你小心拾起，拂去尘土。"},
        ],
    },
    {
        "name": "天师遗址",
        "description": "古天师坐化之地，道统传承历历在目，符箓之力弥漫于断壁残垣之间，雷击桃木与符骨在时光中沉淀，是修道者梦寐以求的符箓传承圣地。",
        "max_minutes": 52,
        "min_realm_stage": "元婴",
        "min_realm_layer": 2,
        "min_combat_power": 3800,
        "event_pool": [
            {
                "name": "符骨显露",
                "description": "古阵在无人催动之下忽然运转，露出埋藏于土中的符骨，神秘纹路若隐若现。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "鬼画符骨",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 28,
            },
            {
                "name": "桃木引雷",
                "description": "古天师亲手种植的桃木林依旧繁茂，雷雨天时吸引无数天雷轰击，留下道道雷击痕迹。",
                "event_type": "oddity",
                "weight": 2,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "雷击桃木",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 2,
                "bonus_chance": 32,
            },
            {
                "name": "符阵反噬",
                "description": "遗址符阵突放光芒，神秘符文如活物般游走，你一时不察被符阵困住！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 28,
                "stone_bonus_max": 50,
                "stone_loss_min": 16,
                "stone_loss_max": 30,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "鬼画符骨", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 18, "event_text": "你轻拂去符骨上的尘土，古朴神秘的符文在掌心微微发亮，似乎蕴含着上古天师的传承。"},
            {"reward_kind": "material", "reward_ref_id_name": "雷击桃木", "quantity_min": 1, "quantity_max": 2, "weight": 6, "stone_reward": 16, "event_text": "雷击桃木林中，你选取几块雷劫痕迹最深的桃木，入手微微发麻却感觉灵力充沛。"},
            {"reward_kind": "material", "reward_ref_id_name": "天雷符骨", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 22, "event_text": "古阵核心之处，你发现一块蕴含天雷之力的符骨，散发着威严的雷霆气息。"},
            {"reward_kind": "material", "reward_ref_id_name": "灵蚕丝", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 14, "event_text": "天师织物残片之中，你剥离出几缕光洁如雪的灵蚕丝，柔韧而轻盈。"},
            {"reward_kind": "material", "reward_ref_id_name": "黑狗血", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 16, "event_text": "遗址祭祀之处，残留着古天师用以镇邪的黑狗血，虽已干涸却灵韵犹存。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "镇魂符符谱", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 20, "event_text": "你在天师玉简阁中仔细翻找，于一堆残破玉简之下发现一页完好的镇魂符符谱。"},
        ],
    },
    # ========== 新增：上品秘境 ==========
    {
        "name": "玄冰神宫",
        "description": "上古仙人以万年玄冰铸就的神圣宫殿，永恒寒气流转不息，宫门之上霜华凝结成神秘纹路，唯有真正的有缘者方能进入其中，获取超越凡俗的冰系仙材与无上机缘。",
        "max_minutes": 55,
        "min_realm_stage": "元婴",
        "min_realm_layer": 5,
        "min_combat_power": 4500,
        "event_pool": [
            {
                "name": "玄冰核心",
                "description": "宫殿最深处，万年玄冰汇聚之地，一块散发幽蓝寒光的玄冰精髓在冰芯中若隐若现。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "玄冰精髓",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 22,
            },
            {
                "name": "仙鹤遗蜕",
                "description": "宫殿梁柱之上，一只仙鹤的遗蜕静立其上，通体如冰晶雕琢，顶上红粒仍散发着灵光。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "仙鹤顶红",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 16,
            },
            {
                "name": "寒冰崩落",
                "description": "宫殿顶部万年寒冰忽然崩落，巨大冰棱如刀锋般向你砸落，你急忙闪避！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 35,
                "stone_bonus_max": 60,
                "stone_loss_min": 20,
                "stone_loss_max": 38,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "玄冰精髓", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 28, "event_text": "你深入神宫最深处，在万年寒冰核心之中获得一块散发幽蓝光芒的玄冰精髓，其寒气足以冻裂寻常金丹修士护体灵光。"},
            {"reward_kind": "material", "reward_ref_id_name": "仙鹤顶红", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 32, "event_text": "你轻触仙鹤遗蜕，从其头顶红粒处获取一撮散发灵光的仙鹤顶红。"},
            {"reward_kind": "material", "reward_ref_id_name": "太白精金", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 30, "event_text": "你深入金属性灵脉深处，提炼出数块散发璀璨金光的太白精金，入手如握破锋利刃。"},
            {"reward_kind": "material", "reward_ref_id_name": "乙木精华", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 28, "event_text": "神宫花园之中，一株存活万年的古木散发着勃勃生机，你自其核心抽取一缕碧绿欲滴的乙木精华。"},
            {"reward_kind": "material", "reward_ref_id_name": "不死神树皮", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 30, "event_text": "古木之上层层叠叠的不死神树皮在寒光中泛着微微灵光，你小心翼翼地剥下一块。"},
            {"reward_kind": "material", "reward_ref_id_name": "幽冥魂晶", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 32, "event_text": "幽冥阵法核心之处，轮回之力汇聚成晶莹晶体，你小心翼翼地将其收入掌中。"},
            {"reward_kind": "material", "reward_ref_id_name": "金翅大鹏羽", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 35, "event_text": "宫殿角落遗落着一根散发金光的羽毛，你认出这正是金翅大鹏之羽，轻盈却蕴含极速之灵。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "玄冰破天丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 38, "event_text": "仙人玉简阁中，你拂去万载尘埃，于一堆玉简之中发现一页完整的玄冰破天丹丹谱。"},
        ],
    },
    {
        "name": "凤栖神木",
        "description": "上古火凤栖息过的神木，树干参天如柱，枝叶遮天蔽日，蕴含极致火灵精华与凤凰血脉余韵，是火系修士梦寐以求的至高圣地。",
        "max_minutes": 58,
        "min_realm_stage": "化神",
        "min_realm_layer": 1,
        "min_combat_power": 5000,
        "event_pool": [
            {
                "name": "凤心血滴",
                "description": "神木最顶端，一滴散发着极致火光的血精静静悬浮，那是凤凰心脉所凝。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "烈凤心血",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 18,
            },
            {
                "name": "涅槃火羽",
                "description": "神木枝桠之间，一根浴火凤凰的羽毛静静嵌在其中，散发着不灭的涅槃真火。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "涅槃火羽",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 14,
            },
            {
                "name": "神火失控",
                "description": "神木中封印的涅槃真火忽然失控，滔天热浪席卷而来，你护体灵光在烈火中摇摇欲坠！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 40,
                "stone_bonus_max": 70,
                "stone_loss_min": 24,
                "stone_loss_max": 45,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "烈凤心血", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 38, "event_text": "你攀登神木之巅，在凤凰栖息之处获得一滴散发极致火光的烈凤心血，其温度足以熔金化铁。"},
            {"reward_kind": "material", "reward_ref_id_name": "涅槃火羽", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 40, "event_text": "你在神木枝桠之间发现这根浴火凤凰遗留的羽毛，虽已历经万载，其上真火仍流转不息。"},
            {"reward_kind": "material", "reward_ref_id_name": "朱雀心核", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 45, "event_text": "神木最核心处，你发现一枚散发南明离火的晶体，这正是朱雀心核，入手滚烫至极。"},
            {"reward_kind": "material", "reward_ref_id_name": "凤凰真血", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 50, "event_text": "传说中，唯有与凤有缘者方能得到这一滴凤凰真血，入手灼热却感觉神识清明。"},
            {"reward_kind": "material", "reward_ref_id_name": "火鸾羽", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 24, "event_text": "神木之上散落着无数火鸾羽毛，你一一拾取，每一根都散发着温暖的光芒。"},
            {"reward_kind": "material", "reward_ref_id_name": "凤尾草", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 22, "event_text": "神木根部丛生着一片赤红如火的草地，正是凤尾草，轻触即燃却灵韵悠长。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "凤涅槃丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 42, "event_text": "古凤凰传承玉简在神木深处微微发光，你小心翼翼地将其拾起，拂去万载尘埃。"},
        ],
    },
    {
        "name": "白虎神山",
        "description": "白虎神兽永镇之圣山，庚金之气冲天彻地，肃杀之意笼罩全山，金石类灵材在此凝聚而出，是修炼金系功法者的至高历练之地。",
        "max_minutes": 56,
        "min_realm_stage": "化神",
        "min_realm_layer": 3,
        "min_combat_power": 5200,
        "event_pool": [
            {
                "name": "白虎遗金",
                "description": "山巅之顶散发璀璨金光，数块白虎神金在庚金之气中若隐若现，凛然如神兽本体现世。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "白虎神金",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 20,
            },
            {
                "name": "虎须引风",
                "description": "山风呼啸之中，夹杂着几根坚硬如铁的白虎胡须，随风飘荡于山巅绝壁之间。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "白虎胡须",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 16,
            },
            {
                "name": "庚金反噬",
                "description": "白虎神山金气骤然暴走，无数金属性利刃如暴风骤雨般向你激射而来！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 42,
                "stone_bonus_max": 75,
                "stone_loss_min": 26,
                "stone_loss_max": 48,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "白虎神金", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 40, "event_text": "你攀登至山巅绝壁，在庚金之气最浓郁之处获得数块散发璀璨金光的白虎神金，入手沉重如山岳。"},
            {"reward_kind": "material", "reward_ref_id_name": "白虎胡须", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 35, "event_text": "你在山风之中收集到数根白虎胡须，银白如雪，坚硬似铁，可作为符箓无上引子。"},
            {"reward_kind": "material", "reward_ref_id_name": "太白精金", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 30, "event_text": "你深入庚金矿脉，以灵力提炼出数块散发锐利银光的太白精金，其锐不可当。"},
            {"reward_kind": "material", "reward_ref_id_name": "天雷符骨", "quantity_min": 1, "quantity_max": 1, "weight": 4, "stone_reward": 32, "event_text": "山巅雷击之处，你发现一块蕴含天雷之力的符骨，散发着威严的雷霆气息。"},
            {"reward_kind": "material", "reward_ref_id_name": "天师袍角", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 36, "event_text": "古天师遗迹之中，你获得一块残留道韵的天师袍角，上有点点符文若隐若现。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "白虎破军符符谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 40, "event_text": "白虎神像之下，你发现一页被金光笼罩的符谱，正是传说中的白虎破军符符谱。"},
        ],
    },
    # ========== 新增：极品秘境 ==========
    {
        "name": "九幽深渊",
        "description": "九幽之地最深处的禁地，轮回之力如雾弥漫，死寂之中蕴含万物归藏之大机缘，唯有真正超脱凡俗的渡劫大能方能在此存活，是获取幽冥至宝与轮回机缘的无上之地。",
        "max_minutes": 65,
        "min_realm_stage": "化神",
        "min_realm_layer": 7,
        "min_combat_power": 6000,
        "event_pool": [
            {
                "name": "九幽寒莲",
                "description": "幽冥池畔，一朵散发幽冷光芒的寒莲在水面上静静绽放，花瓣如九幽玄冰凝成。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "九幽寒莲",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 16,
            },
            {
                "name": "轮回冥晶",
                "description": "轮回之力在幽冥深处凝结成璀璨晶体，散发着生死轮回的深奥气机。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "轮回冥晶",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 12,
            },
            {
                "name": "幽冥反噬",
                "description": "九幽之力骤然侵蚀你的神魂，如同坠入无间深渊，剧痛从灵魂深处蔓延全身！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 50,
                "stone_bonus_max": 90,
                "stone_loss_min": 30,
                "stone_loss_max": 60,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "九幽寒莲", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 50, "event_text": "你涉足九幽池畔，在幽冥之力最浓郁之处获得这朵传说中的九幽寒莲，其寒气足以冻结万物生机。"},
            {"reward_kind": "material", "reward_ref_id_name": "轮回冥晶", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 55, "event_text": "你在轮回之力最浓之处发现这枚璀璨的轮回冥晶，其上似有生死流转，入手却沉重异常。"},
            {"reward_kind": "material", "reward_ref_id_name": "幽冥魂晶", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 38, "event_text": "幽冥最深处，你采获数枚散发幽光的魂晶，每一枚都蕴含着纯净的幽冥之力。"},
            {"reward_kind": "material", "reward_ref_id_name": "幽冥本源", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 60, "event_text": "九幽本源之地，一丝幽冥界最原始的力量缠绕指尖，你小心翼翼地将它收起。"},
            {"reward_kind": "material", "reward_ref_id_name": "天罚雷种", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 58, "event_text": "幽冥劫云之中，你发现一枚紫色雷种在劫云中跳动，散发天罚之威。"},
            {"reward_kind": "material", "reward_ref_id_name": "青龙之鳞", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 52, "event_text": "龙族遗迹之中，一枚散发碧绿神光的鳞片静静躺在尘埃之下，这正是青龙之鳞。"},
            {"reward_kind": "material", "reward_ref_id_name": "玄武龟甲", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 50, "event_text": "深渊最底层，你发现一块完整的玄武龟甲，其上纹理记载着水之极致的奥秘。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "九幽轮回丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 65, "event_text": "古修传承之地，一页泛黄的丹谱在幽光中微微发亮，你轻启尘封将其拾起。"},
        ],
    },
    {
        "name": "建木遗址",
        "description": "上古神木建木的永恒残骸，通天彻地之残躯虽已枯死，却蕴含开天辟地的磅礴生机与万木至尊的至高灵韵，是木系与生命系修士梦寐以求的至高圣地。",
        "max_minutes": 68,
        "min_realm_stage": "炼虚",
        "min_realm_layer": 1,
        "min_combat_power": 6500,
        "event_pool": [
            {
                "name": "建木之种",
                "description": "神木残根最深处，一枚散发苍茫生机的种子在沉寂中等待，似在等待亿万年后的某一天重新萌发。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "建木之种",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 14,
            },
            {
                "name": "人参果精",
                "description": "建木残留根系之间，一枚形如婴儿的果实散发灵光，那是万年人参修炼成精所化。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "人参果精",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 12,
            },
            {
                "name": "生机失控",
                "description": "建木残骸中沉睡的磅礴生机骤然觉醒，如怒潮般向你汹涌而来！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 55,
                "stone_bonus_max": 95,
                "stone_loss_min": 35,
                "stone_loss_max": 65,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "建木之种", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 65, "event_text": "你在神木残根最深处发现这枚蕴含开天辟地之力的种子，入手温热，似有生命在其中流转。"},
            {"reward_kind": "material", "reward_ref_id_name": "人参果精", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 55, "event_text": "你在神木根系间发现这枚形如婴儿的果实，其上散发灵光，正是传说中的万年人参果精。"},
            {"reward_kind": "material", "reward_ref_id_name": "乙木精华", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 40, "event_text": "神木核心之处你抽取到一缕乙木精华，碧绿晶莹，蕴含东方甲木之精粹。"},
            {"reward_kind": "material", "reward_ref_id_name": "不死神树皮", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 42, "event_text": "残骸之上层层叠叠的不死神树皮在时光中不朽，你小心翼翼地将其剥下。"},
            {"reward_kind": "material", "reward_ref_id_name": "青龙帝藤", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 58, "event_text": "神木最深处缠绕着一根散发帝威的藤蔓，你将其取下，正是青龙帝藤。"},
            {"reward_kind": "material", "reward_ref_id_name": "太虚真金", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 62, "event_text": "建木伴生矿脉之中，一块散发虚空之色的金属静静躺在其中，正是太虚真金。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "万木逢春丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 70, "event_text": "古修传承于神木核心处留下一页丹谱，你轻拂去尘埃，见其上载有万木逢春丹之炼制秘法。"},
        ],
    },
    {
        "name": "天罚雷渊",
        "description": "天道雷罚永恒降临之地，亿万年天劫雷霆交织成网，雷种与天劫之力在此凝聚成形，是雷系修士梦寐以求的至高雷道圣地，唯有渡劫者方能在其中存活。",
        "max_minutes": 70,
        "min_realm_stage": "炼虚",
        "min_realm_layer": 4,
        "min_combat_power": 7000,
        "event_pool": [
            {
                "name": "天罚雷种",
                "description": "雷渊最深处，紫色的天罚雷种在永恒的劫云之中跳动，散发天道最威严的惩罚之力。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "天罚雷种",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 12,
            },
            {
                "name": "九天玄玉",
                "description": "雷光劈开黑暗的间隙，一块散发幽蓝光芒的玄玉显露真容，其上似有雷劫痕迹。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "九天玄玉",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 10,
            },
            {
                "name": "雷劫降临",
                "description": "天劫忽然锁定你的气息，亿万钧天雷化作雷龙，张开巨口向你猛然扑来！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 60,
                "stone_bonus_max": 100,
                "stone_loss_min": 40,
                "stone_loss_max": 75,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "天罚雷种", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 70, "event_text": "你深入雷渊核心，在亿万钧雷霆之中获得这枚天罚雷种，入手如握天威，紫光流转。"},
            {"reward_kind": "material", "reward_ref_id_name": "九天玄玉", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 60, "event_text": "雷光劈开混沌之际，你获得这块蕴含九天玄冰之力的玄玉，入手奇寒却感觉灵力流转。"},
            {"reward_kind": "material", "reward_ref_id_name": "天雷符骨", "quantity_min": 1, "quantity_max": 2, "weight": 5, "stone_reward": 45, "event_text": "雷击岩层之中，你劈开被雷劫反复轰击的岩石，获得数块蕴含天雷之力的符骨。"},
            {"reward_kind": "material", "reward_ref_id_name": "天道雷种", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 80, "event_text": "雷渊最深处，你发现一枚超越天罚的雷种，其上缠绕着天道法则的纹路。"},
            {"reward_kind": "material", "reward_ref_id_name": "混沌雷种", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 90, "event_text": "传说之中，唯有在混沌之中方能诞生的混沌雷种，竟在雷渊最深处被你寻得。"},
            {"reward_kind": "material", "reward_ref_id_name": "本源雷种", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 110, "event_text": "万雷归寂的一瞬，雷渊中心浮现出一枚古老雷核，你屏息将其摄入掌心，正是雷道最本源的本源雷种。"},
            {"reward_kind": "material", "reward_ref_id_name": "天罚雷竹", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 55, "event_text": "雷竹林中，竹子在万载雷劫中屹立不倒，你选取其中雷痕最深的获取一根天罚雷竹。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "天罚破境丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 75, "event_text": "古修士渡劫坐化之处，一页丹谱在雷光中微微发亮，你小心翼翼地将它拾起。"},
        ],
    },
    # ========== 新增：仙品秘境 ==========
    {
        "name": "鸿蒙圣境",
        "description": "超越仙界的永恒圣地，鸿蒙紫气缭绕成海，混沌精华凝聚如云，万法之源在此交汇，是修行者梦寐以求的至高殿堂，唯有真正的大乘修士方能叩开圣境大门。",
        "max_minutes": 75,
        "min_realm_stage": "合体",
        "min_realm_layer": 1,
        "min_combat_power": 8000,
        "event_pool": [
            {
                "name": "鸿蒙紫莲",
                "description": "鸿蒙最深处的混沌之中，一朵散发紫色神光的圣莲在水面上轻轻摇曳，蕴含着创世前的原始精华。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "鸿蒙紫莲",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 10,
            },
            {
                "name": "混沌祖气",
                "description": "鸿蒙之中，一缕苍茫混沌原始之气缓缓流转，蕴含着开辟天地的无上伟力。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "混沌祖气",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 8,
            },
            {
                "name": "混沌挤压",
                "description": "鸿蒙之力忽然挤压而来，如同万物归宗的巨大力量要将你压成齑粉！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 80,
                "stone_bonus_max": 140,
                "stone_loss_min": 50,
                "stone_loss_max": 100,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "鸿蒙紫莲", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 90, "event_text": "你踏入鸿蒙最深处，混沌如海围绕周身，一朵散发紫色神光的圣莲在水面上轻轻摇曳，你伸手将其摘下，其间似有天地初开的景象。"},
            {"reward_kind": "material", "reward_ref_id_name": "混沌祖气", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 95, "event_text": "在混沌初开的核心之地，一缕苍茫如雾的祖气缓缓流转，你小心翼翼地将它封存于玉瓶之中。"},
            {"reward_kind": "material", "reward_ref_id_name": "混沌灵根", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 85, "event_text": "万法之源处，一株散发着混沌气息的灵根在虚空中摇曳，你将其小心翼翼地连根拔起。"},
            {"reward_kind": "material", "reward_ref_id_name": "凤凰真血", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 88, "event_text": "圣境某处微光闪烁，一滴散发金红光芒的精血悬浮半空，你认出这正是凤凰真血。"},
            {"reward_kind": "material", "reward_ref_id_name": "鲲鹏巨羽", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 80, "event_text": "圣境之中遗落着一根散发九彩神光的羽毛，其大如扇，你认出这正是鲲鹏巨羽。"},
            {"reward_kind": "material", "reward_ref_id_name": "天玄真银", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 75, "event_text": "圣境矿脉深处，一块散发银白光芒的金属在混沌之气中若隐若现，你将其收入囊中。"},
            {"reward_kind": "material", "reward_ref_id_name": "阴阳无极水", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 85, "event_text": "阴阳交汇之处，一瓶散发着黑白交融光芒的神水静静等待着你，你将其郑重收起。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "鸿蒙混沌丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 100, "event_text": "鸿蒙圣境核心之地，一页散发混沌光泽的玉简在虚空中浮现，你凝神将其映入脑海。"},
        ],
    },
    {
        "name": "六道轮回殿",
        "description": "掌管天地轮回的永恒神殿，六道法则交织成网，命运之力在此流转不息，蕴含完整的轮回法则与天命奥义，是参悟生死轮回之密的至高殿堂。",
        "max_minutes": 78,
        "min_realm_stage": "合体",
        "min_realm_layer": 5,
        "min_combat_power": 8500,
        "event_pool": [
            {
                "name": "轮回祖符",
                "description": "神殿最核心之地，一枚弥漫幽光的祖符悬浮于轮回之力中央，散发生死交替的无上法则。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "轮回祖符",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 8,
            },
            {
                "name": "六道轮回砂",
                "description": "轮回之地边缘，细如金粉的黄砂在六道之力中缓缓流转，每一粒都蕴含一丝轮回法则。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "六道轮回砂",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 10,
            },
            {
                "name": "轮回反噬",
                "description": "轮回之力骤然侵入你的神魂，你感到自己的寿命与命运都在被这法则之力强行剥离！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 85,
                "stone_bonus_max": 150,
                "stone_loss_min": 55,
                "stone_loss_max": 110,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "轮回祖符", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 100, "event_text": "你进入六道轮回殿核心之地，一枚弥漫幽光的祖符悬浮于轮回之力中央，你凝神将其映入神魂。"},
            {"reward_kind": "material", "reward_ref_id_name": "六道轮回砂", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 80, "event_text": "你在轮回之地边缘采集到数粒细如金粉的黄砂，每一粒都散发着轮回的微光。"},
            {"reward_kind": "material", "reward_ref_id_name": "幽冥本源", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 85, "event_text": "幽冥池畔，一丝幽冥界最原始的本源之力缠绕指尖，你小心翼翼地将它收起。"},
            {"reward_kind": "material", "reward_ref_id_name": "轮回冥晶", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 75, "event_text": "轮回阵核心处，数枚散发幽冷光芒的轮回冥晶在虚空中漂浮，你将它们尽数收入。"},
            {"reward_kind": "material", "reward_ref_id_name": "天道玉髓", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 95, "event_text": "神殿至深处，一块散发天道法则波动的玉髓静静躺在轮回之光中，你伸手将其拾起。"},
            {"reward_kind": "material", "reward_ref_id_name": "命运之种", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 110, "event_text": "传说中，唯有与命运有缘者方能在轮回之地深处获得这枚命运之种，你竟在此处寻得。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "轮回证道丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 105, "event_text": "古仙传承之地，一页散发轮回光泽的丹谱在虚空中浮现，你将其完整拓印于神魂之中。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "轮回天道丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 115, "event_text": "轮回天盘转到极尽之刻，一页兼具轮回与天道纹路的丹谱自虚空缓缓落下，被你完整收入识海。"},
        ],
    },
    {
        "name": "天道遗迹",
        "description": "天道意志永恒残留之地，天道法则在此显化为实质，命运与因果交织成网，蕴含完整的天道法则与天命奥义，唯有渡过天劫的至强者方能窥探其万一。",
        "max_minutes": 80,
        "min_realm_stage": "渡劫",
        "min_realm_layer": 1,
        "min_combat_power": 9000,
        "event_pool": [
            {
                "name": "大道符纸",
                "description": "遗迹最深处，一张散发金色光芒的符纸悬浮于天道法则交织之处，其上大道符文流转。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "大道符纸",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 8,
            },
            {
                "name": "天玄真银",
                "description": "天道熔炉之中，一块散发银白光芒的金属缓缓凝结，蕴含天道法则的精华。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "天玄真银",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 10,
            },
            {
                "name": "天道压制",
                "description": "天道遗迹的意志骤然觉醒，无上威压如山岳般镇压而下，你的修为在这威压之下竟有崩溃之兆！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 90,
                "stone_bonus_max": 160,
                "stone_loss_min": 60,
                "stone_loss_max": 120,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "大道符纸", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 100, "event_text": "你深入遗迹核心，一张散发金色光芒的符纸悬浮于天道法则交织之处，你凝神将其映入神魂。"},
            {"reward_kind": "material", "reward_ref_id_name": "天玄真银", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 85, "event_text": "天道熔炉深处，一块散发银白光芒的金属在天道之火的淬炼下缓缓成形，你伸手将它取下。"},
            {"reward_kind": "material", "reward_ref_id_name": "天道雷种", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 90, "event_text": "天罚雷罚核心处，一枚散发天道法则波动的雷种在混沌之中跳动，你小心翼翼地将它封存。"},
            {"reward_kind": "material", "reward_ref_id_name": "天道精华", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 105, "event_text": "遗迹至深处，一滴散发天道法则波动的精华在虚空中若隐若现，你以灵力将它封存于玉瓶之中。"},
            {"reward_kind": "material", "reward_ref_id_name": "天外玄铁", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 95, "event_text": "天外坠落之地，一块散发混沌气息的玄铁深深嵌入大地之中，你以灵力将它连根拔起。"},
            {"reward_kind": "material", "reward_ref_id_name": "五行本源", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 110, "event_text": "五行交汇之处，一缕散发五彩光芒的本源之力缠绕指尖，你将这一丝五行本源郑重收起。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "天道大同丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 115, "event_text": "天道遗迹核心之地，一页散发大道光泽的丹谱在虚空中缓缓浮现，你将其完整映入神魂。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "补天丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 125, "event_text": "遗迹深处忽现五色霞光，一页记载补天丹秘法的古丹谱自法则潮汐中缓缓显形，被你稳稳收入袖中。"},
        ],
    },
    # ========== 新增：先天至宝秘境 ==========
    {
        "name": "开天遗迹",
        "description": "盘古大神开天辟地的永恒圣地，创世之力如混沌之海弥漫其间，天地初开的第一缕光芒仍在遗迹之中流转，是超越一切认知的至高存在，唯有真正的真仙方能窥探其一二。",
        "max_minutes": 90,
        "min_realm_stage": "渡劫",
        "min_realm_layer": 7,
        "min_combat_power": 10000,
        "event_pool": [
            {
                "name": "开天神石",
                "description": "遗迹最深处，一块散发混沌创世光芒的神石悬浮于虚空之中，其上似有天地初开的第一道光芒流转。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "开天神石",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 6,
            },
            {
                "name": "盘古精血",
                "description": "创世之地最深处，一滴散发洪荒气息的精血静静悬浮，其内蕴含着开辟天地的无上大力。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "盘古精血",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 4,
            },
            {
                "name": "创世反噬",
                "description": "开天辟地的创世之力突然冲击你的肉身，你的每一个细胞都在这力量下发出悲鸣！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 120,
                "stone_bonus_max": 200,
                "stone_loss_min": 80,
                "stone_loss_max": 150,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "开天神石", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 150, "event_text": "你进入开天遗迹最深处，一块散发混沌创世光芒的神石悬浮于虚空之中，其内似有天地初开的第一道光芒流转，你凝神将它收入神魂之中。"},
            {"reward_kind": "material", "reward_ref_id_name": "盘古精血", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 200, "event_text": "传说中，唯有与盘古有缘者方能得到这一滴精血，你竟在此处寻得，其内蕴含的开天辟地之力让你心神震颤。"},
            {"reward_kind": "material", "reward_ref_id_name": "造化玉蝶", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 180, "event_text": "创世之地核心处，一只散发生灭之光的造化玉蝶缓缓飘落，你伸手将它迎接，其上似有造化天地的法则在流转。"},
            {"reward_kind": "material", "reward_ref_id_name": "创世神铁", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 160, "event_text": "遗迹之中，一块散发混沌重量的神铁静静躺在创世之地，其沉重足以压弯时空。"},
            {"reward_kind": "material", "reward_ref_id_name": "时空源晶", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 145, "event_text": "时空混乱之处，一枚散发银蓝光芒的晶体在时空裂隙中若隐若现，你伸手将它捉住，其内蕴含着逆转时空的法则。"},
            {"reward_kind": "material", "reward_ref_id_name": "混沌羽毛", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 140, "event_text": "混沌残留之处，一根散发九彩神光的羽毛静静漂浮，你将它小心拾起，入手如握混沌。"},
            {"reward_kind": "material", "reward_ref_id_name": "大道金莲", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 170, "event_text": "遗迹至深处，一朵散发大道的金莲在水面上绽放，你俯身将它采摘，其上似有万道法则在流转。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "开天辟地丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 180, "event_text": "盘古传承之地，一页散发混沌光泽的丹谱在虚空中缓缓浮现，你将其完整映入神魂。"},
        ],
    },
    {
        "name": "天道本源",
        "description": "天道的最终源头，宇宙法则的永恒起源，时间与空间在此交汇，过去与未来在此纠缠，唯有超越仙王的至强者方能触及这一存在，一切的彼岸。",
        "max_minutes": 100,
        "min_realm_stage": "真仙",
        "min_realm_layer": 1,
        "min_combat_power": 12000,
        "event_pool": [
            {
                "name": "天道玉髓",
                "description": "天道本源最核心处，一块完美无瑕的玉髓散发天道法则，其上似有时间长河与空间坐标在流转。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "天道玉髓",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 5,
            },
            {
                "name": "命运之种",
                "description": "因果命运交汇之处，一枚散发璀璨光芒的种子悬浮半空，其内蕴含着命运法则的本源。",
                "event_type": "oddity",
                "weight": 1,
                "bonus_reward_kind": "material",
                "bonus_reward_ref_id_name": "命运之种",
                "bonus_quantity_min": 1,
                "bonus_quantity_max": 1,
                "bonus_chance": 4,
            },
            {
                "name": "天道抹杀",
                "description": "天道的意志骤然觉醒，无上威压将你的存在彻底锁定，天道抹杀降临！你的神魂在这威压下几乎崩溃！",
                "event_type": "danger",
                "weight": 3,
                "stone_bonus_min": 150,
                "stone_bonus_max": 250,
                "stone_loss_min": 100,
                "stone_loss_max": 200,
            },
        ],
        "drops": [
            {"reward_kind": "material", "reward_ref_id_name": "天道玉髓", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 180, "event_text": "你进入天道本源核心，一块完美无瑕的玉髓散发天道法则，其上似有时间长河与空间坐标在流转，你凝神将它收入神魂。"},
            {"reward_kind": "material", "reward_ref_id_name": "命运之种", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 200, "event_text": "因果命运交汇之处，一枚散发璀璨光芒的种子悬浮半空，你伸手将它握住，其内蕴含着命运法则的本源。"},
            {"reward_kind": "material", "reward_ref_id_name": "天道精华", "quantity_min": 1, "quantity_max": 2, "weight": 3, "stone_reward": 160, "event_text": "本源各处散发天道法则的波动，你收集到数滴散发着法则之力的天道精华。"},
            {"reward_kind": "material", "reward_ref_id_name": "天道玉纸", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 170, "event_text": "本源某处一张散发天道光泽的玉纸在虚空中若隐若现，你将它小心收起。"},
            {"reward_kind": "material", "reward_ref_id_name": "混沌祖气", "quantity_min": 1, "quantity_max": 2, "weight": 4, "stone_reward": 150, "event_text": "混沌本源处，数缕散发苍茫气息的祖气在虚空中缓缓流转，你将它们尽数封存于玉瓶之中。"},
            {"reward_kind": "material", "reward_ref_id_name": "鸿蒙紫莲", "quantity_min": 1, "quantity_max": 1, "weight": 3, "stone_reward": 140, "event_text": "鸿蒙交汇之处，数朵散发紫色神光的圣莲在水面上绽放，你将它们一一采摘。"},
            {"reward_kind": "material", "reward_ref_id_name": "混沌灵根", "quantity_min": 1, "quantity_max": 1, "weight": 2, "stone_reward": 155, "event_text": "万法归宗之处，一株散发着混沌气息的灵根在虚空中摇曳，你小心翼翼地将它连根拔起。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "天道永恒丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 200, "event_text": "天道本源核心之地，一页散发永恒光泽的丹谱在虚空最深处缓缓浮现，你凝神将其完整映入神魂。"},
            {"reward_kind": "recipe", "reward_ref_id_name": "洗灵丹丹谱", "quantity_min": 1, "quantity_max": 1, "weight": 1, "stone_reward": 210, "event_text": "本源长河忽然回溯，一页写满洗灵秘纹的丹谱自时空褶皱中显现，被你完整烙入识海。"},
        ],
    },
]


