from __future__ import annotations

from typing import Any


DEFAULT_REALM_THRESHOLDS: list[dict[str, Any]] = [
    {"stage": "斗之气", "star_cap": 9, "douqi_per_star": 100},
    {"stage": "斗者", "star_cap": 9, "douqi_per_star": 220},
    {"stage": "斗师", "star_cap": 9, "douqi_per_star": 380},
    {"stage": "大斗师", "star_cap": 9, "douqi_per_star": 620},
    {"stage": "斗灵", "star_cap": 9, "douqi_per_star": 920},
    {"stage": "斗王", "star_cap": 9, "douqi_per_star": 1320},
    {"stage": "斗皇", "star_cap": 9, "douqi_per_star": 1850},
    {"stage": "斗宗", "star_cap": 9, "douqi_per_star": 2550},
    {"stage": "斗尊", "star_cap": 9, "douqi_per_star": 3400},
    {"stage": "半圣", "star_cap": 3, "douqi_per_star": 5200},
    {"stage": "斗圣", "star_cap": 9, "douqi_per_star": 7600},
    {"stage": "斗帝", "star_cap": 1, "douqi_per_star": 12000},
]

DEFAULT_DAILY_ACTION_LIMITS: dict[str, int] = {
    "adventure": 5,
    "alchemy": 3,
    "pill": 3,
    "fire": 3,
    "sect": 5,
    "auction": 3,
    "technique": 3,
    "faction": 3,
    "boss": 2,
    "tower": 2,
    "pet": 3,
    "black_corner": 3,
    "breakthrough": 3,
}

DEFAULT_ACTION_POINT_COSTS: dict[str, int] = {
    "train": 1,
    "expedition": 2,
    "adventure": 2,
    "alchemy": 1,
    "pill": 1,
    "fire": 2,
    "sect": 1,
    "auction": 1,
    "technique": 1,
    "faction": 1,
    "boss": 3,
    "tower": 3,
    "pet": 2,
    "black_corner": 2,
    "breakthrough": 2,
}

BREAKTHROUGH_RULES: dict[str, dict[str, Any]] = {
    "斗之气": {"gold_cost": 80, "success_percent": 75, "pity_after": 2, "item_costs": {"qi_gathering_powder": 1}},
    "斗者": {"gold_cost": 120, "success_percent": 68, "pity_after": 3, "item_costs": {"qi_gathering_powder": 1}},
    "斗师": {"gold_cost": 220, "success_percent": 60, "pity_after": 3, "item_costs": {"three_pattern_qingling_pill": 1}},
    "大斗师": {"gold_cost": 320, "success_percent": 55, "pity_after": 4, "item_costs": {"three_pattern_qingling_pill": 1}},
    "斗灵": {"gold_cost": 480, "success_percent": 50, "pity_after": 4, "item_costs": {"douling_pill": 1}},
    "斗王": {"gold_cost": 700, "success_percent": 45, "pity_after": 5, "item_costs": {"breaking_zong_pill": 1}},
    "斗皇": {"gold_cost": 950, "success_percent": 42, "pity_after": 5, "item_costs": {"breaking_zong_pill": 1}},
    "斗宗": {"gold_cost": 1300, "success_percent": 38, "pity_after": 6, "item_costs": {"breaking_zong_pill": 2}},
    "斗尊": {"gold_cost": 1800, "success_percent": 35, "pity_after": 6, "item_costs": {"breaking_zong_pill": 2}},
    "半圣": {"gold_cost": 2600, "success_percent": 30, "pity_after": 7, "item_costs": {"breaking_zong_pill": 3}},
    "斗圣": {"gold_cost": 4000, "success_percent": 25, "pity_after": 8, "item_costs": {"breaking_zong_pill": 5}},
}

DEFAULT_SETTINGS: dict[str, Any] = {
    "exchange_enabled": True,
    "exchange_rate": 100,
    "min_gold_to_exchange": 100,
    "gold_min_to_buy": 1,
    # Only action-generated positive gold is capped; exchange is backed by Emby currency.
    "daily_gold_action_cap": 650,
    "daily_train_limit": 5,
    "daily_expedition_limit": 3,
    "daily_action_points": 12,
    "daily_action_limits": DEFAULT_DAILY_ACTION_LIMITS,
    "action_point_costs": DEFAULT_ACTION_POINT_COSTS,
    "daily_douqi_soft_cap": 250,
    "daily_douqi_hard_cap": 400,
    "daily_douqi_overflow_percent": 20,
    "breakthrough_failure_douqi_loss_percent": 10,
    "duel_min_stake": 0,
    "duel_max_stake": 500,
    "duel_prepare_seconds": 8,
    "broadcast_enabled": True,
    "realm_thresholds": DEFAULT_REALM_THRESHOLDS,
}

ACTION_TYPE_LABELS = {
    "expedition": "游历",
    "train": "修炼",
    "adventure": "历练",
    "alchemy": "炼药",
    "fire": "异火",
    "sect": "宗门",
    "auction": "拍卖",
    "pill": "丹药",
    "technique": "斗技",
    "faction": "阵营",
    "boss": "魔兽Boss",
    "tower": "塔修",
    "pet": "伙伴",
    "black_corner": "黑角域",
    "breakthrough": "突破",
}

ALCHEMY_RANKS = [
    {"name": "未入品", "exp": 0},
    {"name": "一品炼药师", "exp": 80},
    {"name": "二品炼药师", "exp": 240},
    {"name": "三品炼药师", "exp": 560},
    {"name": "四品炼药师", "exp": 1100},
    {"name": "五品炼药师", "exp": 1900},
    {"name": "六品炼药师", "exp": 3100},
    {"name": "七品炼药师", "exp": 4800},
    {"name": "八品炼药师", "exp": 7200},
    {"name": "九品炼药师", "exp": 10800},
]

SECT_RANKS = [
    {"name": "外门弟子", "contribution": 0},
    {"name": "内门弟子", "contribution": 120},
    {"name": "执事", "contribution": 420},
    {"name": "长老", "contribution": 1100},
    {"name": "宗主候选", "contribution": 2600},
]

SECT_OPTIONS = [
    {
        "key": "jia_ma_alliance",
        "name": "加玛盟",
        "description": "适合稳健成长，宗门任务更偏向金币、贡献与基础材料。",
        "bonus": "宗门委托收益均衡",
        "realm_stage_min": "斗之气",
    },
    {
        "key": "canaan_academy",
        "name": "迦南学院",
        "description": "适合塔修和心火路线，后续更容易衔接天焚炼气塔。",
        "bonus": "塔修路线更顺滑",
        "realm_stage_min": "斗者",
    },
    {
        "key": "yunlan_sect",
        "name": "云岚宗",
        "description": "适合宗门任务和阵营战路线，贡献成长较稳定。",
        "bonus": "宗门声望与阵营任务",
        "realm_stage_min": "斗者",
    },
    {
        "key": "snake_people",
        "name": "蛇人族",
        "description": "适合塔戈尔沙漠、火属性材料和异火线索路线。",
        "bonus": "沙漠历练与护火材料",
        "realm_stage_min": "斗者",
    },
    {
        "key": "mitel_family",
        "name": "米特尔家族",
        "description": "适合拍卖、商队和材料流通，金币回收与拍卖声望更突出。",
        "bonus": "拍卖与商队路线",
        "realm_stage_min": "斗者",
    },
    {
        "key": "xingyun_pavilion",
        "name": "星陨阁",
        "description": "适合高阶斗技与异火路线，需要更高境界后加入。",
        "bonus": "斗技与异火成长",
        "realm_stage_min": "大斗师",
    },
    {
        "key": "danta",
        "name": "丹塔",
        "description": "适合高阶炼药师考核、丹方和中州路线。",
        "bonus": "炼药考核与丹方兑换",
        "realm_stage_min": "斗王",
    },
    {
        "key": "soul_palace",
        "name": "魂殿",
        "description": "高风险势力，适合黑角域、掠夺和限时冲突玩法。",
        "bonus": "高风险黑市与阵营冲突",
        "realm_stage_min": "斗皇",
    },
]

HEAVENLY_FIRES = [
    {
        "name": "青莲地心火",
        "progress": 100,
        "rank": 19,
        "clue": "塔戈尔沙漠、青莲地心火线索",
        "condition": "护火丹、血莲精与足够火候",
        "risk": "收服失败会火毒反噬",
        "effect": "炼药火候、修炼增幅、PVP 首段爆发",
    },
    {
        "name": "海心焰",
        "progress": 280,
        "rank": 15,
        "clue": "黑角域拍卖、黑市线人",
        "condition": "黑角域恶名与焚诀基础",
        "risk": "水火冲突会损失火候",
        "effect": "PVP 水火反制、降低被爆发压制",
    },
    {
        "name": "陨落心炎",
        "progress": 560,
        "rank": 14,
        "clue": "迦南学院、天焚炼气塔",
        "condition": "火能、塔层和心火残焰",
        "risk": "心火暴动会损失斗气",
        "effect": "塔修效率、火能收益、持续修炼速度",
    },
    {
        "name": "骨灵冷火",
        "progress": 780,
        "rank": 11,
        "clue": "中州、丹塔高阶考核",
        "condition": "高阶炼药经验与丹塔凭证",
        "risk": "冷火入体会消耗高阶药材",
        "effect": "炼药成功率、失败材料返还",
    },
    {
        "name": "三千焱炎火",
        "progress": 960,
        "rank": 9,
        "clue": "中州星域、三千焱炎火残图",
        "condition": "焚诀等级、阵营声望和异火掌控",
        "risk": "星焰反噬会削弱火候与金币",
        "effect": "PVP 爆发与恢复、长线修炼速度",
    },
]

TECHNIQUES = [
    {"key": "octane_burst", "name": "八极崩", "level": 1},
    {"key": "flame_divide", "name": "焰分噬浪尺", "level": 3},
    {"key": "skyfire_steps", "name": "三千雷动", "level": 6},
    {"key": "lotus_flame", "name": "佛怒火莲", "level": 9},
]

INVENTORY_CATEGORIES = [
    {"key": "pill", "name": "丹药", "description": "恢复、突破与短时爆发用丹。"},
    {"key": "herb", "name": "药材", "description": "炼药与异火收服的基础材料。"},
    {"key": "ore", "name": "矿材", "description": "炼器、装备修复与拍卖交易材料。"},
    {"key": "core", "name": "魔核", "description": "魔兽山脉和 Boss 讨伐产出的炼药材料。"},
    {"key": "fire", "name": "异火", "description": "天地灵火线索、残焰与已收服火种。"},
    {"key": "technique", "name": "斗技", "description": "身法、尺法与爆发斗技卷轴。"},
    {"key": "method", "name": "功法", "description": "斗气运转路线与火属性功法。"},
    {"key": "gear", "name": "装备", "description": "纳戒、重尺、护具等长期资产。"},
    {"key": "token", "name": "凭证", "description": "宗门、拍卖与塔修相关信物。"},
]

ITEM_CATALOG: dict[str, dict[str, Any]] = {
    "qi_gathering_powder": {
        "name": "聚气散",
        "category": "pill",
        "rarity": "一品",
        "description": "低阶修炼丹药，可辅助斗之气阶段稳定积累。",
    },
    "recovery_pill": {
        "name": "回气丹",
        "category": "pill",
        "rarity": "二品",
        "description": "历练后恢复斗气的常备丹药。",
    },
    "three_pattern_qingling_pill": {
        "name": "三纹青灵丹",
        "category": "pill",
        "rarity": "四品",
        "description": "冲击瓶颈时常用的进阶丹药。",
    },
    "breaking_zong_pill": {
        "name": "破宗丹",
        "category": "pill",
        "rarity": "六品",
        "description": "高阶突破材料，后续可接入拍卖与宗门兑换。",
    },
    "healing_powder": {
        "name": "疗伤散",
        "category": "pill",
        "rarity": "一品",
        "description": "历练后常用的低阶疗伤丹散。",
    },
    "fire_guard_pill": {
        "name": "护火丹",
        "category": "pill",
        "rarity": "三品",
        "description": "接触异火线索前服用，可降低火毒反噬。",
    },
    "lotus_body_pill": {
        "name": "血莲丹",
        "category": "pill",
        "rarity": "四品",
        "description": "以血莲精护体，适合异火淬体与塔修前准备。",
    },
    "douling_pill": {
        "name": "斗灵丹",
        "category": "pill",
        "rarity": "五品",
        "description": "高阶增长斗气的丹药，炼制成本较高。",
    },
    "ice_spirit_flame_grass": {
        "name": "冰灵焰草",
        "category": "herb",
        "rarity": "玄阶",
        "description": "火属性丹方常用药材。",
    },
    "blood_lotus_essence": {
        "name": "血莲精",
        "category": "herb",
        "rarity": "玄阶",
        "description": "承受异火灼炼时常见的护体材料。",
    },
    "seven_leaf_lotus": {
        "name": "七叶青莲",
        "category": "herb",
        "rarity": "地阶",
        "description": "青莲地心火线索相关的稀有药材。",
    },
    "snake_shed_grass": {
        "name": "蛇蜕草",
        "category": "herb",
        "rarity": "黄阶",
        "description": "蛇人沙漠常见药草，低阶丹散常用。",
    },
    "earth_core_fire_mushroom": {
        "name": "地心火芝",
        "category": "herb",
        "rarity": "玄阶",
        "description": "地火旺盛处生长的炼火药材。",
    },
    "dragon_beard_ice_fire_fruit": {
        "name": "龙须冰火果",
        "category": "herb",
        "rarity": "地阶",
        "description": "冰火药性并存，常用于高阶丹方。",
    },
    "purple_spirit_crystal": {
        "name": "紫灵晶",
        "category": "ore",
        "rarity": "玄阶",
        "description": "紫晶翼狮王领地附近产出的炼药炼器材料。",
    },
    "soul_warming_lotus": {
        "name": "温魂莲",
        "category": "herb",
        "rarity": "地阶",
        "description": "温养灵魂的稀有药材，高阶丹方材料。",
    },
    "bone_washing_flower": {
        "name": "洗骨花",
        "category": "herb",
        "rarity": "地阶",
        "description": "淬骨洗髓类丹方的关键药材。",
    },
    "black_iron_ore": {
        "name": "黑铁矿",
        "category": "ore",
        "rarity": "凡品",
        "description": "黑岩城常见炼器矿材。",
    },
    "flame_pattern_steel": {
        "name": "火纹钢",
        "category": "ore",
        "rarity": "玄阶",
        "description": "带火属性纹路的炼器材料。",
    },
    "monster_core_low": {
        "name": "一二阶魔核",
        "category": "core",
        "rarity": "凡品",
        "description": "低阶炼药与宗门任务材料。",
    },
    "monster_core_mid": {
        "name": "三四阶魔核",
        "category": "core",
        "rarity": "玄阶",
        "description": "中阶丹药与斗技修炼材料。",
    },
    "monster_core_high": {
        "name": "五阶以上魔核",
        "category": "core",
        "rarity": "地阶",
        "description": "Boss 与拍卖场产出的高阶材料。",
    },
    "qinglian_fire_map": {
        "name": "青莲地心火线索",
        "category": "fire",
        "rarity": "地阶",
        "description": "塔戈尔沙漠相关的异火踪迹。",
    },
    "fallen_heart_flame_trace": {
        "name": "陨落心炎残焰",
        "category": "fire",
        "rarity": "地阶",
        "description": "迦南塔修中积累的心火痕迹。",
    },
    "sea_heart_flame_trace": {
        "name": "海心焰线索",
        "category": "fire",
        "rarity": "地阶",
        "description": "黑角域拍卖与黑市流出的蓝焰线索。",
    },
    "bone_spirit_cold_fire_trace": {
        "name": "骨灵冷火线索",
        "category": "fire",
        "rarity": "天阶",
        "description": "丹塔高阶考核中出现的冷火残息。",
    },
    "three_thousand_flame_trace": {
        "name": "三千焱炎火残图",
        "category": "fire",
        "rarity": "天阶",
        "description": "中州星域相关的高阶异火残图。",
    },
    "qinglian_fire_seed": {
        "name": "青莲地心火",
        "category": "fire",
        "rarity": "异火",
        "description": "已收服的天地灵火火种。",
    },
    "sea_heart_flame_seed": {
        "name": "海心焰",
        "category": "fire",
        "rarity": "异火",
        "description": "已收服的蓝色异火火种。",
    },
    "fallen_heart_flame_seed": {
        "name": "陨落心炎",
        "category": "fire",
        "rarity": "异火",
        "description": "可提升塔修效率和心火修炼速度的异火。",
    },
    "bone_spirit_cold_fire_seed": {
        "name": "骨灵冷火",
        "category": "fire",
        "rarity": "异火",
        "description": "极适合炼药师掌控火候的冷火。",
    },
    "three_thousand_flame_seed": {
        "name": "三千焱炎火",
        "category": "fire",
        "rarity": "异火",
        "description": "星域异火，适合 PVP 爆发与恢复。",
    },
    "baji_beng_scroll": {
        "name": "八极崩卷轴",
        "category": "technique",
        "rarity": "玄阶",
        "description": "近身爆发斗技。",
    },
    "flame_divide_scroll": {
        "name": "焰分噬浪尺卷轴",
        "category": "technique",
        "rarity": "地阶",
        "description": "重尺斗技卷轴。",
    },
    "thunder_steps_scroll": {
        "name": "三千雷动残卷",
        "category": "technique",
        "rarity": "地阶",
        "description": "高阶身法残卷。",
    },
    "buddha_lotus_scroll": {
        "name": "佛怒火莲残卷",
        "category": "technique",
        "rarity": "天阶",
        "description": "多种异火融合的爆发斗技残卷。",
    },
    "flame_method_fragment": {
        "name": "火属性功法残篇",
        "category": "method",
        "rarity": "玄阶",
        "description": "提升火属性修炼效率的功法残篇。",
    },
    "burning_method_fragment": {
        "name": "焚诀残篇",
        "category": "method",
        "rarity": "天阶",
        "description": "吞噬异火提升功法等级的核心功法残篇。",
    },
    "xuan_heavy_ruler": {
        "name": "玄重尺",
        "category": "gear",
        "rarity": "地阶",
        "description": "重尺修炼与斗技加成装备。",
    },
    "black_iron_sword": {
        "name": "黑铁剑",
        "category": "gear",
        "rarity": "凡品",
        "description": "佣兵常用武器，前期过渡装备。",
    },
    "cloud_step_boots": {
        "name": "踏云靴",
        "category": "gear",
        "rarity": "玄阶",
        "description": "提升身法与历练机动性的轻靴。",
    },
    "scale_guard_armor": {
        "name": "蛇鳞护甲",
        "category": "gear",
        "rarity": "玄阶",
        "description": "蛇人沙漠产出的护甲，抗火性不错。",
    },
    "purple_cloud_wings": {
        "name": "紫云翼",
        "category": "gear",
        "rarity": "地阶",
        "description": "飞行类秘宝，来源极少。",
    },
    "flame_guard_bracer": {
        "name": "炎纹护腕",
        "category": "gear",
        "rarity": "玄阶",
        "description": "以火纹钢打造的护腕。",
    },
    "low_grade_storage_ring": {
        "name": "低阶纳戒",
        "category": "gear",
        "rarity": "凡品",
        "description": "初入斗气大陆的随身储物道具。",
    },
    "mitel_auction_token": {
        "name": "米特尔拍卖牌",
        "category": "token",
        "rarity": "玄阶",
        "description": "参与拍卖与商队护送的声望凭证。",
    },
    "inner_academy_badge": {
        "name": "内院火能牌",
        "category": "token",
        "rarity": "地阶",
        "description": "迦南学院塔修相关凭证。",
    },
    "fire_energy_crystal": {
        "name": "火能晶",
        "category": "token",
        "rarity": "玄阶",
        "description": "迦南学院内院流通的火能结晶。",
    },
    "black_corner_black_card": {
        "name": "黑角域黑卡",
        "category": "token",
        "rarity": "地阶",
        "description": "黑市交易和悬赏玩法的身份凭证。",
    },
    "danta_exam_token": {
        "name": "丹塔考核令",
        "category": "token",
        "rarity": "地阶",
        "description": "参与高阶炼药师考核的凭证。",
    },
    "yunlan_token": {
        "name": "云岚令",
        "category": "token",
        "rarity": "玄阶",
        "description": "云岚宗阵营任务凭证。",
    },
    "snake_people_token": {
        "name": "蛇人族信物",
        "category": "token",
        "rarity": "玄阶",
        "description": "蛇人族声望与沙漠任务凭证。",
    },
    "starfall_token": {
        "name": "星陨令",
        "category": "token",
        "rarity": "地阶",
        "description": "星陨阁高阶斗技任务凭证。",
    },
    "soul_palace_token": {
        "name": "魂殿密令",
        "category": "token",
        "rarity": "天阶",
        "description": "高风险阵营与黑角域事件凭证。",
    },
    "alchemist_badge_1": {"name": "一品炼药师徽章", "category": "token", "rarity": "一品", "description": "一品炼药考核凭证。"},
    "alchemist_badge_2": {"name": "二品炼药师徽章", "category": "token", "rarity": "二品", "description": "二品炼药考核凭证。"},
    "alchemist_badge_3": {"name": "三品炼药师徽章", "category": "token", "rarity": "三品", "description": "三品炼药考核凭证。"},
    "alchemist_badge_4": {"name": "四品炼药师徽章", "category": "token", "rarity": "四品", "description": "四品炼药考核凭证。"},
    "alchemist_badge_5": {"name": "五品炼药师徽章", "category": "token", "rarity": "五品", "description": "五品炼药考核凭证。"},
    "alchemist_badge_6": {"name": "六品炼药师徽章", "category": "token", "rarity": "六品", "description": "六品炼药考核凭证。"},
    "alchemist_badge_7": {"name": "七品炼药师徽章", "category": "token", "rarity": "七品", "description": "七品炼药考核凭证。"},
    "alchemist_badge_8": {"name": "八品炼药师徽章", "category": "token", "rarity": "八品", "description": "八品炼药考核凭证。"},
    "alchemist_badge_9": {"name": "九品炼药师徽章", "category": "token", "rarity": "九品", "description": "九品炼药考核凭证。"},
    "star_mist_grass": {
        "name": "星雾草",
        "category": "herb",
        "rarity": "地阶",
        "description": "中州星域附近出现的高阶药材。",
    },
    "dragon_blood_branch": {
        "name": "龙血枝",
        "category": "herb",
        "rarity": "天阶",
        "description": "太虚古龙相关的稀有药材。",
    },
    "void_spirit_leaf": {
        "name": "虚灵叶",
        "category": "herb",
        "rarity": "天阶",
        "description": "高阶丹药和空间类伙伴任务材料。",
    },
    "bodhi_seed": {
        "name": "菩提子",
        "category": "herb",
        "rarity": "天阶",
        "description": "中州高阶机缘材料。",
    },
    "amethyst_lion_cub": {
        "name": "小紫晶翼狮",
        "category": "token",
        "rarity": "地阶",
        "description": "可作为伙伴培养的紫晶翼狮幼崽。",
    },
    "phoenix_plume": {
        "name": "天妖凰翎",
        "category": "token",
        "rarity": "天阶",
        "description": "天妖凰族相关伙伴线索。",
    },
    "taixu_dragon_scale": {
        "name": "太虚古龙鳞",
        "category": "token",
        "rarity": "天阶",
        "description": "太虚古龙伙伴与中州任务线索。",
    },
}

DEFAULT_ACTIONS: list[dict[str, Any]] = [
    {
        "action_key": "train_breath",
        "name": "静室凝气",
        "description": "沉心运转斗气，稳定积累修为。",
        "action_type": "train",
        "cooldown_seconds": 15,
        "reward_config": {"douqi_min": 28, "douqi_max": 66, "gold_min": 2, "gold_max": 8},
        "requirement_config": {},
        "enabled": True,
        "sort_order": 10,
    },
    {
        "action_key": "mountain_hunt",
        "name": "魔兽山脉历练",
        "description": "深入山脉猎取魔核，炼药需要的魔核主要从这里获取。",
        "action_type": "adventure",
        "cooldown_seconds": 35,
        "reward_config": {
            "drop_table_version": 4,
            "douqi_min": 55,
            "douqi_max": 140,
            "gold_min": -10,
            "gold_max": 34,
            "core_min": 0,
            "core_max": 2,
            "item_drops": [
                {"item_key": "monster_core_low", "min": 1, "max": 2, "chance": 78},
                {"item_key": "monster_core_mid", "min": 1, "max": 1, "chance": 14},
                {"item_key": "monster_core_high", "min": 1, "max": 1, "chance": 3},
                {"item_key": "ice_spirit_flame_grass", "min": 1, "max": 2, "chance": 45},
                {"item_key": "blood_lotus_essence", "min": 1, "max": 1, "chance": 18},
                {"item_key": "black_iron_ore", "min": 1, "max": 2, "chance": 28},
                {"item_key": "black_iron_sword", "min": 1, "max": 1, "chance": 5},
            ],
        },
        "requirement_config": {},
        "enabled": True,
        "sort_order": 20,
    },
    {
        "action_key": "herb_gather_yaolao",
        "name": "药老指点采药",
        "description": "按药性采集炼药材料，金币收益很低，但能稳定补充药材。",
        "action_type": "adventure",
        "cooldown_seconds": 50,
        "reward_config": {
            "drop_table_version": 4,
            "douqi_min": 24,
            "douqi_max": 72,
            "gold_min": -6,
            "gold_max": 8,
            "alchemy_min": 3,
            "alchemy_max": 8,
            "item_drops": [
                {"item_key": "ice_spirit_flame_grass", "min": 1, "max": 3, "chance": 90},
                {"item_key": "blood_lotus_essence", "min": 1, "max": 2, "chance": 55},
                {"item_key": "seven_leaf_lotus", "min": 1, "max": 1, "chance": 12},
                {"item_key": "snake_shed_grass", "min": 1, "max": 2, "chance": 62},
                {"item_key": "earth_core_fire_mushroom", "min": 1, "max": 1, "chance": 22},
                {"item_key": "dragon_beard_ice_fire_fruit", "min": 1, "max": 1, "chance": 4},
            ],
        },
        "requirement_config": {},
        "enabled": True,
        "sort_order": 22,
    },
    {
        "action_key": "snake_desert_patrol",
        "name": "蛇人沙漠巡行",
        "description": "前往塔戈尔边缘搜寻蛇蜕草、血莲精与沙漠护具。",
        "action_type": "adventure",
        "cooldown_seconds": 80,
        "reward_config": {
            "drop_table_version": 1,
            "douqi_min": 44,
            "douqi_max": 110,
            "gold_min": -18,
            "gold_max": 18,
            "item_drops": [
                {"item_key": "snake_shed_grass", "min": 1, "max": 3, "chance": 82},
                {"item_key": "blood_lotus_essence", "min": 1, "max": 2, "chance": 46},
                {"item_key": "earth_core_fire_mushroom", "min": 1, "max": 1, "chance": 18},
                {"item_key": "scale_guard_armor", "min": 1, "max": 1, "chance": 6},
            ],
        },
        "requirement_config": {"realm_stage_min": "斗者"},
        "enabled": True,
        "sort_order": 24,
    },
    {
        "action_key": "lion_king_cave_scout",
        "name": "紫晶洞府探查",
        "description": "探查紫晶翼狮王洞府外围，获取紫灵晶与稀有矿材。",
        "action_type": "adventure",
        "cooldown_seconds": 140,
        "reward_config": {
            "drop_table_version": 1,
            "douqi_min": 72,
            "douqi_max": 150,
            "gold_min": -28,
            "gold_max": 24,
            "item_drops": [
                {"item_key": "purple_spirit_crystal", "min": 1, "max": 2, "chance": 58},
                {"item_key": "flame_pattern_steel", "min": 1, "max": 1, "chance": 28},
                {"item_key": "dragon_beard_ice_fire_fruit", "min": 1, "max": 1, "chance": 10},
                {"item_key": "purple_cloud_wings", "min": 1, "max": 1, "chance": 2},
            ],
        },
        "requirement_config": {"realm_stage_min": "斗师", "gold_min": 28},
        "enabled": True,
        "sort_order": 26,
    },
    {
        "action_key": "arena_drill",
        "name": "斗技切磋",
        "description": "用实战打磨斗技，额外提升突破把握。",
        "action_type": "adventure",
        "cooldown_seconds": 45,
        "reward_config": {"douqi_min": 70, "douqi_max": 160, "gold_min": 8, "gold_max": 28, "alchemy_min": 0, "alchemy_max": 1},
        "requirement_config": {"realm_stage_min": "斗者"},
        "enabled": True,
        "sort_order": 30,
    },
    {
        "action_key": "alchemy_refine",
        "name": "炼制聚气散",
        "description": "一品丹方：冰灵焰草与低阶魔核炼成聚气散，材料需先外出历练获取。",
        "action_type": "alchemy",
        "cooldown_seconds": 60,
        "reward_config": {
            "recipe_version": 3,
            "alchemy_min": 18,
            "alchemy_max": 42,
            "douqi_min": 10,
            "douqi_max": 25,
            "gold_cost": 20,
            "item_costs": {"ice_spirit_flame_grass": 2, "monster_core_low": 1},
            "item_drops": [{"item_key": "qi_gathering_powder", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"gold_min": 20},
        "enabled": True,
        "sort_order": 40,
    },
    {
        "action_key": "alchemy_recovery_pill",
        "name": "炼制回气丹",
        "description": "二品丹方：冰灵焰草、血莲精与低阶魔核炼成回气丹。",
        "action_type": "alchemy",
        "cooldown_seconds": 90,
        "reward_config": {
            "recipe_version": 3,
            "alchemy_min": 26,
            "alchemy_max": 58,
            "douqi_min": 16,
            "douqi_max": 36,
            "gold_cost": 35,
            "item_costs": {"ice_spirit_flame_grass": 1, "blood_lotus_essence": 1, "monster_core_low": 1},
            "item_drops": [{"item_key": "recovery_pill", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"realm_stage_min": "斗者", "gold_min": 35, "alchemy_min": 40},
        "enabled": True,
        "sort_order": 41,
    },
    {
        "action_key": "alchemy_healing_powder",
        "name": "炼制疗伤散",
        "description": "一品丹方：蛇蜕草与冰灵焰草炼成疗伤散，适合历练补给。",
        "action_type": "alchemy",
        "cooldown_seconds": 70,
        "reward_config": {
            "recipe_version": 1,
            "alchemy_min": 20,
            "alchemy_max": 46,
            "gold_cost": 18,
            "item_costs": {"snake_shed_grass": 1, "ice_spirit_flame_grass": 1},
            "item_drops": [{"item_key": "healing_powder", "min": 1, "max": 2, "chance": 100}],
        },
        "requirement_config": {"gold_min": 18},
        "enabled": True,
        "sort_order": 41,
    },
    {
        "action_key": "alchemy_fire_guard_pill",
        "name": "炼制护火丹",
        "description": "三品丹方：地心火芝、血莲精与低阶魔核炼成护火丹。",
        "action_type": "alchemy",
        "cooldown_seconds": 120,
        "reward_config": {
            "recipe_version": 1,
            "alchemy_min": 34,
            "alchemy_max": 72,
            "fire_min": 1,
            "fire_max": 4,
            "gold_cost": 55,
            "item_costs": {"earth_core_fire_mushroom": 1, "blood_lotus_essence": 1, "monster_core_low": 1},
            "item_drops": [{"item_key": "fire_guard_pill", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"realm_stage_min": "斗者", "gold_min": 55, "alchemy_min": 90},
        "enabled": True,
        "sort_order": 42,
    },
    {
        "action_key": "alchemy_qingling",
        "name": "炼制三纹青灵丹",
        "description": "四品丹方：血莲精、七叶青莲与三四阶魔核炼成三纹青灵丹。",
        "action_type": "alchemy",
        "cooldown_seconds": 150,
        "reward_config": {
            "recipe_version": 3,
            "alchemy_min": 46,
            "alchemy_max": 92,
            "gold_cost": 90,
            "item_costs": {"blood_lotus_essence": 2, "seven_leaf_lotus": 1, "monster_core_mid": 1},
            "item_drops": [{"item_key": "three_pattern_qingling_pill", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"realm_stage_min": "斗师", "gold_min": 90, "alchemy_min": 160},
        "enabled": True,
        "sort_order": 43,
    },
    {
        "action_key": "alchemy_douling_pill",
        "name": "炼制斗灵丹",
        "description": "五品丹方：龙须冰火果、紫灵晶与高阶魔核炼成斗灵丹。",
        "action_type": "alchemy",
        "cooldown_seconds": 210,
        "reward_config": {
            "recipe_version": 1,
            "alchemy_min": 80,
            "alchemy_max": 150,
            "douqi_min": 60,
            "douqi_max": 140,
            "gold_cost": 180,
            "item_costs": {"dragon_beard_ice_fire_fruit": 1, "purple_spirit_crystal": 1, "monster_core_high": 1},
            "item_drops": [{"item_key": "douling_pill", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 180, "alchemy_min": 360},
        "enabled": True,
        "sort_order": 44,
    },
    {
        "action_key": "alchemy_breaking_zong_pill",
        "name": "炼制破宗丹",
        "description": "六品丹方：温魂莲、洗骨花与高阶魔核炼成破宗丹。",
        "action_type": "alchemy",
        "cooldown_seconds": 320,
        "reward_config": {
            "recipe_version": 1,
            "alchemy_min": 120,
            "alchemy_max": 220,
            "gold_cost": 320,
            "item_costs": {"soul_warming_lotus": 1, "bone_washing_flower": 2, "monster_core_high": 2},
            "item_drops": [{"item_key": "breaking_zong_pill", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"realm_stage_min": "斗王", "gold_min": 320, "alchemy_min": 760},
        "enabled": True,
        "sort_order": 45,
    },
    {
        "action_key": "pill_consume",
        "name": "服用聚气散",
        "description": "消耗背包中的聚气散，短时间内快速增长斗气。",
        "action_type": "pill",
        "cooldown_seconds": 50,
        "reward_config": {"recipe_version": 3, "douqi_min": 160, "douqi_max": 320, "item_costs": {"qi_gathering_powder": 1}},
        "requirement_config": {},
        "enabled": True,
        "sort_order": 49,
    },
    {
        "action_key": "fire_temper",
        "name": "异火淬体",
        "description": "以火劲淬炼经脉，提升火候并获得斗气。",
        "action_type": "fire",
        "cooldown_seconds": 75,
        "reward_config": {"fire_min": 8, "fire_max": 22, "douqi_min": 80, "douqi_max": 180, "gold_min": -20, "gold_max": -8},
        "requirement_config": {"realm_stage_min": "斗师", "alchemy_min": 60},
        "enabled": True,
        "sort_order": 50,
    },
    {
        "action_key": "fire_capture",
        "name": "异火线索",
        "description": "追踪天地灵火踪迹，累积收服进度。",
        "action_type": "fire",
        "cooldown_seconds": 120,
        "reward_config": {
            "fire_progress_min": 18,
            "fire_progress_max": 38,
            "fire_min": 2,
            "fire_max": 8,
            "gold_min": -45,
            "gold_max": -18,
            "item_drops": [{"item_key": "qinglian_fire_map", "min": 1, "max": 1, "chance": 45}],
        },
        "requirement_config": {"realm_stage_min": "斗师", "gold_min": 45},
        "enabled": True,
        "sort_order": 55,
    },
    {
        "action_key": "desert_fire_trace",
        "name": "塔戈尔沙漠寻火",
        "description": "消耗护体药材追踪沙漠异象，推进青莲地心火收服进度。",
        "action_type": "fire",
        "cooldown_seconds": 180,
        "reward_config": {
            "fire_progress_min": 32,
            "fire_progress_max": 72,
            "fire_min": 4,
            "fire_max": 12,
            "gold_cost": 80,
            "item_costs": {"blood_lotus_essence": 1},
            "item_drops": [
                {"item_key": "qinglian_fire_map", "min": 1, "max": 2, "chance": 72},
                {"item_key": "seven_leaf_lotus", "min": 1, "max": 1, "chance": 18},
            ],
        },
        "requirement_config": {"realm_stage_min": "斗师", "gold_min": 80, "alchemy_min": 80},
        "enabled": True,
        "sort_order": 56,
    },
    {
        "action_key": "sect_mission",
        "name": "宗门任务",
        "description": "完成宗门委托，获取贡献与修炼资源。",
        "action_type": "sect",
        "cooldown_seconds": 70,
        "reward_config": {
            "sect_min": 24,
            "sect_max": 58,
            "gold_min": 8,
            "gold_max": 26,
            "douqi_min": 45,
            "douqi_max": 95,
            "item_drops": [{"item_key": "mitel_auction_token", "min": 1, "max": 1, "chance": 18}],
        },
        "requirement_config": {"realm_stage_min": "斗者"},
        "enabled": True,
        "sort_order": 58,
    },
    {
        "action_key": "technique_study",
        "name": "研习斗技",
        "description": "消耗宗门贡献打磨斗技等级，提升战力。",
        "action_type": "technique",
        "cooldown_seconds": 85,
        "reward_config": {
            "technique_min": 1,
            "technique_max": 1,
            "contribution_cost": 35,
            "douqi_min": 20,
            "douqi_max": 55,
            "item_drops": [
                {"item_key": "baji_beng_scroll", "min": 1, "max": 1, "chance": 45},
                {"item_key": "flame_method_fragment", "min": 1, "max": 1, "chance": 22},
            ],
        },
        "requirement_config": {"sect_contribution_min": 35},
        "enabled": True,
        "sort_order": 62,
    },
    {
        "action_key": "technique_archive",
        "name": "斗技阁拓印",
        "description": "花费贡献与金币拓印高阶斗技残卷，偏向长期战力沉淀。",
        "action_type": "technique",
        "cooldown_seconds": 140,
        "reward_config": {
            "technique_min": 1,
            "technique_max": 2,
            "contribution_cost": 90,
            "gold_cost": 70,
            "item_drops": [
                {"item_key": "flame_divide_scroll", "min": 1, "max": 1, "chance": 32},
                {"item_key": "thunder_steps_scroll", "min": 1, "max": 1, "chance": 16},
            ],
        },
        "requirement_config": {"realm_stage_min": "斗师", "sect_contribution_min": 90, "gold_min": 70},
        "enabled": True,
        "sort_order": 64,
    },
    {
        "action_key": "tower_train",
        "name": "塔中淬炼",
        "description": "借火塔压迫修炼，斗气增长显著。",
        "action_type": "tower",
        "cooldown_seconds": 90,
        "reward_config": {
            "douqi_min": 180,
            "douqi_max": 360,
            "gold_min": -45,
            "gold_max": -20,
            "fire_min": 2,
            "fire_max": 6,
            "tower_min": 1,
            "tower_max": 1,
            "item_drops": [
                {"item_key": "fallen_heart_flame_trace", "min": 1, "max": 1, "chance": 28},
                {"item_key": "inner_academy_badge", "min": 1, "max": 1, "chance": 16},
            ],
        },
        "requirement_config": {"realm_stage_min": "大斗师", "gold_min": 45},
        "enabled": True,
        "sort_order": 60,
    },
    {
        "action_key": "fallen_heart_retreat",
        "name": "天焚炼气塔闭关",
        "description": "消耗丹药与金币进行塔修闭关，产出斗气和陨落心炎残焰。",
        "action_type": "tower",
        "cooldown_seconds": 210,
        "reward_config": {
            "douqi_min": 360,
            "douqi_max": 720,
            "fire_min": 8,
            "fire_max": 18,
            "tower_min": 1,
            "tower_max": 2,
            "gold_cost": 150,
            "pill_cost": 1,
            "item_drops": [{"item_key": "fallen_heart_flame_trace", "min": 1, "max": 2, "chance": 66}],
        },
        "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 150, "pill_min": 1, "tower_floor_min": 3},
        "enabled": True,
        "sort_order": 61,
    },
    {
        "action_key": "auction_bid",
        "name": "拍卖场竞价",
        "description": "以金币竞拍丹药、魔核和异火线索。",
        "action_type": "auction",
        "cooldown_seconds": 110,
        "reward_config": {
            "gold_cost": 120,
            "auction_min": 18,
            "auction_max": 42,
            "pill_min": 0,
            "pill_max": 2,
            "core_min": 1,
            "core_max": 3,
            "fire_progress_min": 0,
            "fire_progress_max": 12,
            "item_drops": [
                {"item_key": "monster_core_mid", "min": 1, "max": 1, "chance": 35},
                {"item_key": "three_pattern_qingling_pill", "min": 1, "max": 1, "chance": 20},
                {"item_key": "qinglian_fire_map", "min": 1, "max": 1, "chance": 28},
                {"item_key": "fire_guard_pill", "min": 1, "max": 1, "chance": 18},
                {"item_key": "flame_pattern_steel", "min": 1, "max": 2, "chance": 22},
                {"item_key": "cloud_step_boots", "min": 1, "max": 1, "chance": 5},
            ],
        },
        "requirement_config": {"gold_min": 120},
        "enabled": True,
        "sort_order": 70,
    },
    {
        "action_key": "mitel_caravan_guard",
        "name": "护送米特尔商队",
        "description": "用战力换取拍卖声望和材料，金币产出受每日上限约束。",
        "action_type": "auction",
        "cooldown_seconds": 130,
        "reward_config": {
            "douqi_min": 72,
            "douqi_max": 160,
            "gold_min": 18,
            "gold_max": 46,
            "auction_min": 28,
            "auction_max": 60,
            "item_drops": [
                {"item_key": "mitel_auction_token", "min": 1, "max": 2, "chance": 70},
                {"item_key": "low_grade_storage_ring", "min": 1, "max": 1, "chance": 8},
                {"item_key": "black_iron_ore", "min": 1, "max": 3, "chance": 42},
                {"item_key": "healing_powder", "min": 1, "max": 2, "chance": 26},
                {"item_key": "black_iron_sword", "min": 1, "max": 1, "chance": 7},
            ],
        },
        "requirement_config": {"realm_stage_min": "斗者"},
        "enabled": True,
        "sort_order": 72,
    },
    {
        "action_key": "black_rock_medicine_market",
        "name": "黑岩城药市淘货",
        "description": "消耗金币在药市淘药材、矿材、低阶丹药和装备胚子。",
        "action_type": "auction",
        "cooldown_seconds": 95,
        "reward_config": {
            "drop_table_version": 1,
            "gold_cost": 60,
            "auction_min": 12,
            "auction_max": 30,
            "item_drops": [
                {"item_key": "snake_shed_grass", "min": 1, "max": 3, "chance": 64},
                {"item_key": "ice_spirit_flame_grass", "min": 1, "max": 2, "chance": 52},
                {"item_key": "black_iron_ore", "min": 1, "max": 3, "chance": 48},
                {"item_key": "healing_powder", "min": 1, "max": 2, "chance": 30},
                {"item_key": "flame_pattern_steel", "min": 1, "max": 1, "chance": 16},
            ],
        },
        "requirement_config": {"gold_min": 60},
        "enabled": True,
        "sort_order": 73,
    },
    {
        "action_key": "forge_flame_bracer",
        "name": "炼器坊打磨护腕",
        "description": "消耗矿材打造炎纹护腕，是装备线的稳定合成入口。",
        "action_type": "auction",
        "cooldown_seconds": 160,
        "reward_config": {
            "recipe_version": 1,
            "gold_cost": 95,
            "auction_min": 18,
            "auction_max": 38,
            "item_costs": {"black_iron_ore": 2, "flame_pattern_steel": 1},
            "item_drops": [{"item_key": "flame_guard_bracer", "min": 1, "max": 1, "chance": 100}],
        },
        "requirement_config": {"gold_min": 95},
        "enabled": True,
        "sort_order": 74,
    },
    {
        "action_key": "boss_challenge",
        "name": "魔兽Boss讨伐",
        "description": "挑战高阶魔兽，按战果获取魔核与声望。",
        "action_type": "boss",
        "cooldown_seconds": 180,
        "reward_config": {
            "boss_min": 28,
            "boss_max": 70,
            "core_min": 2,
            "core_max": 6,
            "gold_min": 20,
            "gold_max": 62,
            "douqi_min": 90,
            "douqi_max": 210,
            "item_drops": [
                {"item_key": "monster_core_mid", "min": 1, "max": 2, "chance": 65},
                {"item_key": "monster_core_high", "min": 1, "max": 1, "chance": 18},
                {"item_key": "xuan_heavy_ruler", "min": 1, "max": 1, "chance": 5},
                {"item_key": "bone_washing_flower", "min": 1, "max": 1, "chance": 12},
                {"item_key": "purple_cloud_wings", "min": 1, "max": 1, "chance": 1},
            ],
        },
        "requirement_config": {"realm_stage_min": "大斗师", "technique_level_min": 2},
        "enabled": True,
        "sort_order": 80,
    },
    {
        "action_key": "lotus_flame_drill",
        "name": "火莲雏形推演",
        "description": "消耗异火线索、丹药和金币推演爆发技，偏向高阶 Boss 与突破准备。",
        "action_type": "boss",
        "cooldown_seconds": 240,
        "reward_config": {
            "boss_min": 60,
            "boss_max": 130,
            "douqi_min": 180,
            "douqi_max": 380,
            "fire_min": 10,
            "fire_max": 24,
            "gold_cost": 180,
            "pill_cost": 1,
            "item_costs": {"qinglian_fire_map": 1},
            "item_drops": [{"item_key": "flame_divide_scroll", "min": 1, "max": 1, "chance": 18}],
        },
        "requirement_config": {"realm_stage_min": "斗王", "gold_min": 180, "pill_min": 1, "fire_progress_min": 80},
        "enabled": True,
        "sort_order": 82,
    },
    {
        "action_key": "breakthrough_try",
        "name": "冲击瓶颈",
        "description": "九星且斗气圆满后冲击下一境界，按境界消耗丹药与金币；连续失败会触发保底。",
        "action_type": "breakthrough",
        "cooldown_seconds": 45,
        "reward_config": {"balance_version": 1, "dynamic_breakthrough": True},
        "requirement_config": {},
        "enabled": True,
        "sort_order": 90,
    },
]

DEFAULT_ACTIONS.extend(
    [
        {
            "action_key": "wutan_city_patrol",
            "name": "乌坦城巡历",
            "description": "在乌坦城周边接取委托，获取前期药材、矿材和少量金币。",
            "action_type": "adventure",
            "cooldown_seconds": 35,
            "reward_config": {
                "drop_table_version": 1,
                "douqi_min": 35,
                "douqi_max": 88,
                "gold_min": 4,
                "gold_max": 18,
                "item_drops": [
                    {"item_key": "snake_shed_grass", "min": 1, "max": 2, "chance": 48},
                    {"item_key": "ice_spirit_flame_grass", "min": 1, "max": 2, "chance": 40},
                    {"item_key": "black_iron_ore", "min": 1, "max": 2, "chance": 34},
                    {"item_key": "low_grade_storage_ring", "min": 1, "max": 1, "chance": 4},
                ],
            },
            "requirement_config": {},
            "enabled": True,
            "sort_order": 18,
        },
        {
            "action_key": "tagor_desert_expedition",
            "name": "塔戈尔沙漠历练",
            "description": "深入沙漠寻找血莲精、地心火芝和青莲地心火线索。",
            "action_type": "adventure",
            "cooldown_seconds": 120,
            "reward_config": {
                "drop_table_version": 1,
                "douqi_min": 68,
                "douqi_max": 148,
                "gold_min": -25,
                "gold_max": 20,
                "fire_progress_min": 6,
                "fire_progress_max": 18,
                "item_drops": [
                    {"item_key": "blood_lotus_essence", "min": 1, "max": 2, "chance": 56},
                    {"item_key": "earth_core_fire_mushroom", "min": 1, "max": 2, "chance": 44},
                    {"item_key": "qinglian_fire_map", "min": 1, "max": 1, "chance": 34},
                    {"item_key": "snake_people_token", "min": 1, "max": 1, "chance": 14},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗师", "gold_min": 25},
            "enabled": True,
            "sort_order": 25,
        },
        {
            "action_key": "canaan_outer_trial",
            "name": "迦南学院外院试炼",
            "description": "完成外院试炼积累火能牌、药材和陨落心炎残焰。",
            "action_type": "adventure",
            "cooldown_seconds": 120,
            "reward_config": {
                "drop_table_version": 1,
                "douqi_min": 90,
                "douqi_max": 210,
                "fire_energy_min": 18,
                "fire_energy_max": 42,
                "faction_min": 6,
                "faction_max": 16,
                "item_drops": [
                    {"item_key": "inner_academy_badge", "min": 1, "max": 1, "chance": 30},
                    {"item_key": "fire_energy_crystal", "min": 1, "max": 2, "chance": 42},
                    {"item_key": "fallen_heart_flame_trace", "min": 1, "max": 1, "chance": 16},
                ],
            },
            "requirement_config": {"realm_stage_min": "大斗师"},
            "enabled": True,
            "sort_order": 27,
        },
        {
            "action_key": "central_plains_expedition",
            "name": "中州游历",
            "description": "前往中州打探丹塔、星陨阁和星域异火消息，产出高阶材料。",
            "action_type": "adventure",
            "cooldown_seconds": 260,
            "reward_config": {
                "drop_table_version": 1,
                "douqi_min": 180,
                "douqi_max": 420,
                "gold_min": -90,
                "gold_max": 55,
                "faction_min": 24,
                "faction_max": 58,
                "item_drops": [
                    {"item_key": "star_mist_grass", "min": 1, "max": 2, "chance": 48},
                    {"item_key": "dragon_blood_branch", "min": 1, "max": 1, "chance": 18},
                    {"item_key": "void_spirit_leaf", "min": 1, "max": 1, "chance": 16},
                    {"item_key": "bodhi_seed", "min": 1, "max": 1, "chance": 6},
                    {"item_key": "three_thousand_flame_trace", "min": 1, "max": 1, "chance": 10},
                    {"item_key": "danta_exam_token", "min": 1, "max": 1, "chance": 18},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗王", "gold_min": 90},
            "enabled": True,
            "sort_order": 29,
        },
        {
            "action_key": "alchemy_exam_rank_1",
            "name": "一品炼药师考核",
            "description": "按指定丹方炼制聚气散，成功后获得一品炼药师徽章。",
            "action_type": "alchemy",
            "cooldown_seconds": 180,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 86,
                "refund_percent": 40,
                "alchemy_min": 45,
                "alchemy_max": 90,
                "gold_cost": 45,
                "item_costs": {"ice_spirit_flame_grass": 2, "monster_core_low": 1},
                "item_drops": [{"item_key": "alchemist_badge_1", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"gold_min": 45, "alchemy_min": 40},
            "enabled": True,
            "sort_order": 46,
        },
        {
            "action_key": "alchemy_exam_rank_2",
            "name": "二品炼药师考核",
            "description": "炼制回气丹并稳定火候，考核成功后进入二品。",
            "action_type": "alchemy",
            "cooldown_seconds": 220,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 82,
                "refund_percent": 35,
                "alchemy_min": 70,
                "alchemy_max": 135,
                "gold_cost": 80,
                "item_costs": {"ice_spirit_flame_grass": 2, "blood_lotus_essence": 1, "monster_core_low": 2},
                "item_drops": [{"item_key": "alchemist_badge_2", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗者", "gold_min": 80, "alchemy_min": 160},
            "enabled": True,
            "sort_order": 47,
        },
        {
            "action_key": "alchemy_exam_rank_3",
            "name": "三品炼药师考核",
            "description": "炼制护火丹，考验药材配比和火毒处理。",
            "action_type": "alchemy",
            "cooldown_seconds": 260,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 78,
                "refund_percent": 35,
                "alchemy_min": 95,
                "alchemy_max": 180,
                "gold_cost": 130,
                "item_costs": {"earth_core_fire_mushroom": 2, "blood_lotus_essence": 2, "monster_core_mid": 1},
                "item_drops": [{"item_key": "alchemist_badge_3", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗师", "gold_min": 130, "alchemy_min": 360},
            "enabled": True,
            "sort_order": 48,
        },
        {
            "action_key": "alchemy_exam_rank_4",
            "name": "四品炼药师考核",
            "description": "炼制三纹青灵丹，开始要求稳定处理中阶魔核。",
            "action_type": "alchemy",
            "cooldown_seconds": 320,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 74,
                "refund_percent": 32,
                "alchemy_min": 130,
                "alchemy_max": 240,
                "gold_cost": 190,
                "item_costs": {"blood_lotus_essence": 2, "seven_leaf_lotus": 1, "monster_core_mid": 2},
                "item_drops": [{"item_key": "alchemist_badge_4", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "大斗师", "gold_min": 190, "alchemy_min": 760},
            "enabled": True,
            "sort_order": 49,
        },
        {
            "action_key": "alchemy_exam_rank_5",
            "name": "五品炼药师考核",
            "description": "炼制斗灵丹，失败会返还部分材料但金币不返还。",
            "action_type": "alchemy",
            "cooldown_seconds": 380,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 70,
                "refund_percent": 30,
                "alchemy_min": 180,
                "alchemy_max": 320,
                "auction_min": 16,
                "auction_max": 32,
                "gold_cost": 280,
                "item_costs": {"dragon_beard_ice_fire_fruit": 1, "purple_spirit_crystal": 2, "monster_core_high": 1},
                "item_drops": [{"item_key": "alchemist_badge_5", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 280, "alchemy_min": 1300},
            "enabled": True,
            "sort_order": 50,
        },
        {
            "action_key": "alchemy_exam_rank_6",
            "name": "六品炼药师考核",
            "description": "炼制破宗丹，进入高阶丹药与拍卖流通核心。",
            "action_type": "alchemy",
            "cooldown_seconds": 460,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 66,
                "refund_percent": 30,
                "alchemy_min": 240,
                "alchemy_max": 420,
                "auction_min": 24,
                "auction_max": 50,
                "gold_cost": 420,
                "item_costs": {"soul_warming_lotus": 1, "bone_washing_flower": 2, "monster_core_high": 2},
                "item_drops": [{"item_key": "alchemist_badge_6", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗王", "gold_min": 420, "alchemy_min": 2200},
            "enabled": True,
            "sort_order": 51,
        },
        {
            "action_key": "alchemy_exam_rank_7",
            "name": "七品炼药师考核",
            "description": "丹塔高阶考核，开始需要中州药材和丹塔考核令。",
            "action_type": "alchemy",
            "cooldown_seconds": 560,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 62,
                "refund_percent": 25,
                "alchemy_min": 320,
                "alchemy_max": 560,
                "faction_min": 18,
                "faction_max": 42,
                "gold_cost": 650,
                "item_costs": {"danta_exam_token": 1, "star_mist_grass": 2, "dragon_blood_branch": 1, "monster_core_high": 2},
                "item_drops": [{"item_key": "alchemist_badge_7", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗皇", "gold_min": 650, "alchemy_min": 3600},
            "enabled": True,
            "sort_order": 52,
        },
        {
            "action_key": "alchemy_exam_rank_8",
            "name": "八品炼药师考核",
            "description": "模拟丹雷压力下完成高阶丹药，成功可获得八品徽章。",
            "action_type": "alchemy",
            "cooldown_seconds": 680,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 58,
                "refund_percent": 22,
                "alchemy_min": 450,
                "alchemy_max": 760,
                "fire_rank_min": 0,
                "fire_rank_max": 1,
                "gold_cost": 900,
                "item_costs": {"danta_exam_token": 2, "void_spirit_leaf": 1, "dragon_blood_branch": 1, "monster_core_high": 3},
                "item_drops": [{"item_key": "alchemist_badge_8", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗宗", "gold_min": 900, "alchemy_min": 5200, "fire_rank_min": 1},
            "enabled": True,
            "sort_order": 53,
        },
        {
            "action_key": "alchemy_exam_rank_9",
            "name": "九品炼药师考核",
            "description": "丹塔巅峰考核，需要异火掌控、菩提子和极高炼药经验。",
            "action_type": "alchemy",
            "cooldown_seconds": 900,
            "reward_config": {
                "recipe_version": 1,
                "success_percent": 52,
                "refund_percent": 20,
                "alchemy_min": 680,
                "alchemy_max": 1100,
                "faction_min": 36,
                "faction_max": 72,
                "gold_cost": 1500,
                "item_costs": {"danta_exam_token": 3, "bodhi_seed": 1, "void_spirit_leaf": 2, "monster_core_high": 4},
                "item_drops": [{"item_key": "alchemist_badge_9", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗尊", "gold_min": 1500, "alchemy_min": 8200, "fire_rank_min": 2},
            "enabled": True,
            "sort_order": 54,
        },
        {
            "action_key": "burning_method_devour_qinglian",
            "name": "焚诀吞噬青莲地心火",
            "description": "消耗青莲地心火线索、护火丹和血莲精尝试吞火，成功提升焚诀、异火掌控和 PVP 爆发。",
            "action_type": "fire",
            "cooldown_seconds": 420,
            "reward_config": {
                "recipe_version": 1,
                "risk_percent": 28,
                "backlash_douqi_loss": 120,
                "backlash_gold_loss": 45,
                "method_min": 1,
                "method_max": 1,
                "fire_rank_min": 1,
                "fire_rank_max": 1,
                "fire_min": 80,
                "fire_max": 150,
                "fire_progress_min": 30,
                "fire_progress_max": 60,
                "gold_cost": 160,
                "item_costs": {"qinglian_fire_map": 3, "fire_guard_pill": 1, "blood_lotus_essence": 2},
                "item_drops": [
                    {"item_key": "qinglian_fire_seed", "min": 1, "max": 1, "chance": 100},
                    {"item_key": "burning_method_fragment", "min": 1, "max": 1, "chance": 45},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗师", "gold_min": 160, "alchemy_min": 120, "fire_progress_min": 90},
            "enabled": True,
            "sort_order": 57,
        },
        {
            "action_key": "subdue_sea_heart_flame",
            "name": "收服海心焰",
            "description": "从黑角域线索中反推海心焰位置，水火冲突会带来明显反噬风险。",
            "action_type": "fire",
            "cooldown_seconds": 520,
            "reward_config": {
                "recipe_version": 1,
                "risk_percent": 34,
                "backlash_fire_loss": 40,
                "backlash_gold_loss": 80,
                "method_min": 1,
                "method_max": 1,
                "fire_rank_min": 1,
                "fire_rank_max": 1,
                "fire_min": 110,
                "fire_max": 210,
                "gold_cost": 280,
                "item_costs": {"sea_heart_flame_trace": 3, "fire_guard_pill": 2, "black_corner_black_card": 1},
                "item_drops": [{"item_key": "sea_heart_flame_seed", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 280, "method_level_min": 1, "black_corner_infamy_min": 80},
            "enabled": True,
            "sort_order": 58,
        },
        {
            "action_key": "refine_fallen_heart_flame",
            "name": "炼化陨落心炎",
            "description": "在天焚炼气塔压制心火，消耗火能和残焰炼化陨落心炎。",
            "action_type": "fire",
            "cooldown_seconds": 620,
            "reward_config": {
                "recipe_version": 1,
                "risk_percent": 30,
                "backlash_douqi_loss": 180,
                "backlash_fire_loss": 35,
                "method_min": 1,
                "method_max": 1,
                "fire_rank_min": 1,
                "fire_rank_max": 1,
                "fire_min": 140,
                "fire_max": 260,
                "fire_energy_cost": 160,
                "gold_cost": 360,
                "item_costs": {"fallen_heart_flame_trace": 5, "inner_academy_badge": 1},
                "item_drops": [{"item_key": "fallen_heart_flame_seed", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗王", "gold_min": 360, "method_level_min": 2, "academy_fire_energy_min": 160, "tower_floor_min": 6},
            "enabled": True,
            "sort_order": 59,
        },
        {
            "action_key": "subdue_bone_spirit_cold_fire",
            "name": "收服骨灵冷火",
            "description": "以丹塔线索与高阶炼药经验压制冷火，提高后续炼药成功率。",
            "action_type": "fire",
            "cooldown_seconds": 760,
            "reward_config": {
                "recipe_version": 1,
                "risk_percent": 26,
                "backlash_fire_loss": 50,
                "backlash_gold_loss": 120,
                "method_min": 1,
                "method_max": 1,
                "fire_rank_min": 1,
                "fire_rank_max": 1,
                "fire_min": 180,
                "fire_max": 320,
                "gold_cost": 520,
                "item_costs": {"bone_spirit_cold_fire_trace": 3, "danta_exam_token": 2, "alchemist_badge_6": 1},
                "item_drops": [{"item_key": "bone_spirit_cold_fire_seed", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗皇", "gold_min": 520, "alchemy_min": 3200, "method_level_min": 3, "fire_rank_min": 2},
            "enabled": True,
            "sort_order": 60,
        },
        {
            "action_key": "subdue_three_thousand_flame",
            "name": "收服三千焱炎火",
            "description": "进入中州星域收服三千焱炎火，成功后显著提升 PVP 爆发和恢复。",
            "action_type": "fire",
            "cooldown_seconds": 900,
            "reward_config": {
                "recipe_version": 1,
                "risk_percent": 38,
                "backlash_douqi_loss": 300,
                "backlash_fire_loss": 80,
                "backlash_gold_loss": 180,
                "method_min": 1,
                "method_max": 2,
                "fire_rank_min": 1,
                "fire_rank_max": 1,
                "fire_min": 260,
                "fire_max": 460,
                "gold_cost": 900,
                "item_costs": {"three_thousand_flame_trace": 3, "starfall_token": 2, "bodhi_seed": 1},
                "item_drops": [{"item_key": "three_thousand_flame_seed", "min": 1, "max": 1, "chance": 100}],
            },
            "requirement_config": {"realm_stage_min": "斗宗", "gold_min": 900, "method_level_min": 4, "fire_rank_min": 3, "faction_reputation_min": 300},
            "enabled": True,
            "sort_order": 61,
        },
        {
            "action_key": "academy_fire_energy_hunt",
            "name": "内院火能猎赛",
            "description": "参加迦南学院火能猎赛，刷火能并获得天焚塔兑换资源。",
            "action_type": "tower",
            "cooldown_seconds": 120,
            "reward_config": {
                "drop_table_version": 1,
                "douqi_min": 80,
                "douqi_max": 170,
                "fire_energy_min": 36,
                "fire_energy_max": 82,
                "tower_min": 0,
                "tower_max": 1,
                "item_drops": [
                    {"item_key": "fire_energy_crystal", "min": 1, "max": 3, "chance": 64},
                    {"item_key": "inner_academy_badge", "min": 1, "max": 1, "chance": 30},
                ],
            },
            "requirement_config": {"realm_stage_min": "大斗师"},
            "enabled": True,
            "sort_order": 62,
        },
        {
            "action_key": "inner_rank_challenge",
            "name": "内院强榜挑战",
            "description": "挑战内院强榜，火能、战绩和塔修资源同步增长。",
            "action_type": "tower",
            "cooldown_seconds": 180,
            "reward_config": {
                "douqi_min": 120,
                "douqi_max": 260,
                "fire_energy_min": 48,
                "fire_energy_max": 110,
                "boss_min": 12,
                "boss_max": 30,
                "tower_min": 1,
                "tower_max": 1,
                "gold_cost": 60,
                "item_drops": [{"item_key": "fallen_heart_flame_trace", "min": 1, "max": 1, "chance": 24}],
            },
            "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 60, "technique_level_min": 2},
            "enabled": True,
            "sort_order": 63,
        },
        {
            "action_key": "tower_fire_energy_exchange",
            "name": "火能兑换塔修",
            "description": "消耗火能兑换天焚炼气塔修炼次数，是火能系统的核心消耗口。",
            "action_type": "tower",
            "cooldown_seconds": 160,
            "reward_config": {
                "douqi_min": 260,
                "douqi_max": 540,
                "fire_min": 8,
                "fire_max": 20,
                "tower_min": 1,
                "tower_max": 2,
                "fire_energy_cost": 120,
                "item_drops": [{"item_key": "fallen_heart_flame_trace", "min": 1, "max": 2, "chance": 52}],
            },
            "requirement_config": {"realm_stage_min": "斗灵", "academy_fire_energy_min": 120},
            "enabled": True,
            "sort_order": 65,
        },
        {
            "action_key": "mitel_fire_clue_auction",
            "name": "米特尔异火线索拍卖",
            "description": "在米特尔拍卖场竞价异火线索和丹方，稳定回收金币。",
            "action_type": "auction",
            "cooldown_seconds": 220,
            "reward_config": {
                "drop_table_version": 1,
                "gold_cost": 260,
                "auction_min": 38,
                "auction_max": 82,
                "fire_progress_min": 12,
                "fire_progress_max": 32,
                "item_drops": [
                    {"item_key": "qinglian_fire_map", "min": 1, "max": 2, "chance": 48},
                    {"item_key": "sea_heart_flame_trace", "min": 1, "max": 1, "chance": 16},
                    {"item_key": "danta_exam_token", "min": 1, "max": 1, "chance": 10},
                    {"item_key": "flame_divide_scroll", "min": 1, "max": 1, "chance": 12},
                ],
            },
            "requirement_config": {"gold_min": 260},
            "enabled": True,
            "sort_order": 75,
        },
        {
            "action_key": "black_corner_auction",
            "name": "黑角域拍卖会",
            "description": "高价竞拍魔核、异火线索和黑市凭证，金币回收更重但稀有产出更高。",
            "action_type": "auction",
            "cooldown_seconds": 260,
            "reward_config": {
                "drop_table_version": 1,
                "gold_cost": 420,
                "auction_min": 42,
                "auction_max": 96,
                "infamy_min": 12,
                "infamy_max": 28,
                "item_drops": [
                    {"item_key": "black_corner_black_card", "min": 1, "max": 1, "chance": 46},
                    {"item_key": "sea_heart_flame_trace", "min": 1, "max": 2, "chance": 30},
                    {"item_key": "monster_core_high", "min": 1, "max": 2, "chance": 34},
                    {"item_key": "thunder_steps_scroll", "min": 1, "max": 1, "chance": 18},
                    {"item_key": "bone_spirit_cold_fire_trace", "min": 1, "max": 1, "chance": 8},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 420},
            "enabled": True,
            "sort_order": 76,
        },
        {
            "action_key": "faction_daily_mission",
            "name": "势力声望任务",
            "description": "为已加入势力完成日常委托，提升声望并产出阵营信物。",
            "action_type": "faction",
            "cooldown_seconds": 110,
            "reward_config": {
                "faction_min": 28,
                "faction_max": 64,
                "sect_min": 12,
                "sect_max": 30,
                "douqi_min": 40,
                "douqi_max": 95,
                "item_drops": [
                    {"item_key": "yunlan_token", "min": 1, "max": 1, "chance": 20},
                    {"item_key": "snake_people_token", "min": 1, "max": 1, "chance": 20},
                    {"item_key": "starfall_token", "min": 1, "max": 1, "chance": 12},
                    {"item_key": "danta_exam_token", "min": 1, "max": 1, "chance": 10},
                ],
            },
            "requirement_config": {"sect_required": True},
            "enabled": True,
            "sort_order": 77,
        },
        {
            "action_key": "faction_war_supply",
            "name": "阵营战备",
            "description": "消耗金币和贡献筹备阵营战，获得声望、斗技资源和高阶信物。",
            "action_type": "faction",
            "cooldown_seconds": 240,
            "reward_config": {
                "faction_min": 60,
                "faction_max": 140,
                "technique_min": 1,
                "technique_max": 1,
                "gold_cost": 180,
                "contribution_cost": 80,
                "item_drops": [
                    {"item_key": "starfall_token", "min": 1, "max": 2, "chance": 28},
                    {"item_key": "soul_palace_token", "min": 1, "max": 1, "chance": 7},
                    {"item_key": "buddha_lotus_scroll", "min": 1, "max": 1, "chance": 5},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗王", "gold_min": 180, "sect_contribution_min": 80, "sect_required": True},
            "enabled": True,
            "sort_order": 78,
        },
        {
            "action_key": "technique_baji_mastery",
            "name": "八极崩熟练",
            "description": "消耗八极崩卷轴和贡献，提升斗技熟练度。",
            "action_type": "technique",
            "cooldown_seconds": 140,
            "reward_config": {
                "technique_min": 1,
                "technique_max": 2,
                "contribution_cost": 60,
                "item_costs": {"baji_beng_scroll": 1},
            },
            "requirement_config": {"sect_contribution_min": 60},
            "enabled": True,
            "sort_order": 79,
        },
        {
            "action_key": "technique_three_thousand_steps",
            "name": "三千雷动修习",
            "description": "以三千雷动残卷提升身法，适合 PVP 与高阶历练。",
            "action_type": "technique",
            "cooldown_seconds": 220,
            "reward_config": {
                "technique_min": 2,
                "technique_max": 3,
                "douqi_min": 60,
                "douqi_max": 140,
                "gold_cost": 160,
                "item_costs": {"thunder_steps_scroll": 1, "starfall_token": 1},
            },
            "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 160, "technique_level_min": 4},
            "enabled": True,
            "sort_order": 80,
        },
        {
            "action_key": "technique_buddha_lotus_mastery",
            "name": "佛怒火莲推演",
            "description": "融合异火与焚诀推演佛怒火莲，显著增强斗战爆发。",
            "action_type": "technique",
            "cooldown_seconds": 420,
            "reward_config": {
                "technique_min": 3,
                "technique_max": 5,
                "fire_min": 18,
                "fire_max": 42,
                "gold_cost": 360,
                "item_costs": {"buddha_lotus_scroll": 1, "qinglian_fire_seed": 1},
            },
            "requirement_config": {"realm_stage_min": "斗王", "gold_min": 360, "method_level_min": 2, "fire_rank_min": 1, "technique_level_min": 6},
            "enabled": True,
            "sort_order": 81,
        },
        {
            "action_key": "amethyst_lion_tame",
            "name": "驯养小紫晶翼狮",
            "description": "以紫灵晶和魔核培养小紫晶翼狮，伙伴会提升战力与 PVP 稳定性。",
            "action_type": "pet",
            "cooldown_seconds": 220,
            "reward_config": {
                "pet_key": "amethyst_lion",
                "pet_min": 1,
                "pet_max": 2,
                "boss_min": 8,
                "boss_max": 18,
                "gold_cost": 120,
                "item_costs": {"purple_spirit_crystal": 2, "monster_core_mid": 1},
                "item_drops": [{"item_key": "amethyst_lion_cub", "min": 1, "max": 1, "chance": 38}],
            },
            "requirement_config": {"realm_stage_min": "斗师", "gold_min": 120},
            "enabled": True,
            "sort_order": 83,
        },
        {
            "action_key": "phoenix_partner_trace",
            "name": "天妖凰踪迹",
            "description": "追查天妖凰族线索，适合中后期伙伴和坐骑路线。",
            "action_type": "pet",
            "cooldown_seconds": 320,
            "reward_config": {
                "pet_key": "heavenly_phoenix",
                "pet_min": 1,
                "pet_max": 2,
                "faction_min": 14,
                "faction_max": 30,
                "gold_cost": 220,
                "item_drops": [{"item_key": "phoenix_plume", "min": 1, "max": 1, "chance": 36}],
            },
            "requirement_config": {"realm_stage_min": "斗王", "gold_min": 220, "faction_reputation_min": 120},
            "enabled": True,
            "sort_order": 84,
        },
        {
            "action_key": "taixu_dragon_trial",
            "name": "太虚古龙试炼",
            "description": "以龙血枝和古龙鳞推进太虚古龙伙伴线，成本高但战力沉淀强。",
            "action_type": "pet",
            "cooldown_seconds": 520,
            "reward_config": {
                "pet_key": "taixu_dragon",
                "pet_min": 2,
                "pet_max": 4,
                "douqi_min": 160,
                "douqi_max": 360,
                "gold_cost": 520,
                "item_costs": {"taixu_dragon_scale": 1, "dragon_blood_branch": 1, "monster_core_high": 2},
            },
            "requirement_config": {"realm_stage_min": "斗宗", "gold_min": 520, "pet_level_min": 4},
            "enabled": True,
            "sort_order": 85,
        },
        {
            "action_key": "black_corner_bounty",
            "name": "黑角域悬赏",
            "description": "接受黑角域悬赏，获得恶名、黑卡和材料，也会成为冲突目标。",
            "action_type": "black_corner",
            "cooldown_seconds": 180,
            "reward_config": {
                "drop_table_version": 1,
                "infamy_min": 38,
                "infamy_max": 86,
                "gold_min": 18,
                "gold_max": 58,
                "boss_min": 14,
                "boss_max": 34,
                "item_drops": [
                    {"item_key": "black_corner_black_card", "min": 1, "max": 1, "chance": 34},
                    {"item_key": "monster_core_mid", "min": 1, "max": 2, "chance": 50},
                    {"item_key": "sea_heart_flame_trace", "min": 1, "max": 1, "chance": 12},
                ],
            },
            "requirement_config": {"realm_stage_min": "大斗师"},
            "enabled": True,
            "sort_order": 86,
        },
        {
            "action_key": "black_market_trade",
            "name": "黑市交易",
            "description": "消耗金币和恶名购买稀缺材料、魔核和异火线索，是金币回收口。",
            "action_type": "black_corner",
            "cooldown_seconds": 220,
            "reward_config": {
                "drop_table_version": 1,
                "gold_cost": 300,
                "infamy_cost": 30,
                "auction_min": 10,
                "auction_max": 22,
                "item_drops": [
                    {"item_key": "monster_core_high", "min": 1, "max": 2, "chance": 45},
                    {"item_key": "sea_heart_flame_trace", "min": 1, "max": 2, "chance": 34},
                    {"item_key": "bone_spirit_cold_fire_trace", "min": 1, "max": 1, "chance": 10},
                    {"item_key": "soul_palace_token", "min": 1, "max": 1, "chance": 8},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗灵", "gold_min": 300, "black_corner_infamy_min": 30},
            "enabled": True,
            "sort_order": 87,
        },
        {
            "action_key": "black_corner_herb_contest",
            "name": "药材争夺",
            "description": "在黑角域争夺高阶药材，适合帮派冲突和限时事件扩展。",
            "action_type": "black_corner",
            "cooldown_seconds": 260,
            "reward_config": {
                "risk_percent": 18,
                "backlash_douqi_loss": 100,
                "infamy_min": 24,
                "infamy_max": 58,
                "gold_min": -80,
                "gold_max": 35,
                "item_drops": [
                    {"item_key": "soul_warming_lotus", "min": 1, "max": 2, "chance": 42},
                    {"item_key": "bone_washing_flower", "min": 1, "max": 2, "chance": 38},
                    {"item_key": "star_mist_grass", "min": 1, "max": 1, "chance": 18},
                    {"item_key": "void_spirit_leaf", "min": 1, "max": 1, "chance": 7},
                ],
            },
            "requirement_config": {"realm_stage_min": "斗王", "black_corner_infamy_min": 60},
            "enabled": True,
            "sort_order": 88,
        },
    ]
)

GAMEPLAY_MODULES = [
    {"key": "expedition", "name": "斗气大陆游历", "status": "已开放", "description": "选择区域连续处理随机事件，在风险、体力与暂存战利品之间决定深入或撤离。"},
    {"key": "realm", "name": "境界修炼", "status": "已开放", "description": "斗气、星级、境界成长线。"},
    {"key": "inventory", "name": "纳戒背包", "status": "已开放", "description": "丹药、药材、魔核、异火、斗技、功法和装备分组管理。"},
    {"key": "adventure", "name": "魔兽历练", "status": "已开放", "description": "山脉历练与采药产出材料，金币收益受每日上限控制。"},
    {"key": "alchemy", "name": "炼药师", "status": "已开放", "description": "药材、魔核和金币合成丹药，形成材料消耗。"},
    {"key": "pill", "name": "丹药系统", "status": "已开放", "description": "炼药产丹，服丹快速增长斗气，高阶丹药可作为突破材料。"},
    {"key": "heavenly_fire", "name": "异火收服", "status": "已开放", "description": "追踪线索并收服异火，火候参与战力和突破加成。"},
    {"key": "sect", "name": "宗门势力", "status": "已开放", "description": "宗门贡献、职位和斗技成长。"},
    {"key": "technique", "name": "斗技功法", "status": "已开放", "description": "贡献研习与斗技阁拓印，提升等级与战力。"},
    {"key": "auction", "name": "拍卖场", "status": "已开放", "description": "金币竞拍丹药、魔核和异火线索，是主要金币回收口。"},
    {"key": "boss", "name": "魔兽Boss", "status": "已开放", "description": "挑战高阶魔兽，获取魔核和声望。"},
    {"key": "tower", "name": "迦南塔修", "status": "已开放", "description": "塔层推进，带来高收益修炼行动。"},
    {"key": "economy", "name": "经济控制", "status": "已开放", "description": "行动金币每日封顶，炼药、拍卖、突破和塔修持续回收金币。"},
]


def clamp_int(value: Any, default: int = 0, *, minimum: int | None = None, maximum: int | None = None) -> int:
    try:
        resolved = int(value)
    except (TypeError, ValueError):
        resolved = default
    if minimum is not None:
        resolved = max(resolved, int(minimum))
    if maximum is not None:
        resolved = min(resolved, int(maximum))
    return resolved


def realm_rank(stage: str | None, thresholds: list[dict[str, Any]] | None = None) -> int:
    rows = thresholds or DEFAULT_REALM_THRESHOLDS
    normalized = str(stage or "").strip()
    for index, row in enumerate(rows):
        if str(row.get("stage") or "").strip() == normalized:
            return index
    return 0
